### ISSUE TITLE
Improving request handling performance

### ISSUE THREAD

**Issue by l3utterfly** [hyperium/tonic#1001]
I've done some testing on a large aws instance: (c6i.24xlarge, with 96 vCPU).

I've setup a grpc server that simply echoes the input. The client attempts to query the endpoint as fast as possible concurrently, logging the time taken per request. I'm also running both the client and server on the same machine, using loopback address to eliminate network issues.

It seems the maximum request rate of that the tonic GRPC server can handle is around 75K requests per second.

During max load, the cpu and memory of the server are not heavily utilised at all (max only around 10%).

I've done a quick performance profiling of the grpc server, and it shows most of the time is spent waiting on a Mutex. I've screengrabbed the callstack for the most heavily waited operation here

<img width="852" alt="image" src="https://user-images.githubusercontent.com/6970347/167295235-fe098241-f432-4502-8ab0-0802251ba0f5.png">

I wonder what the bottleneck is? Can the request rate be further improved?

**Comment by LucioFranco** [comment]
Ah I believe this is a performance issue with windows based mio needing a mutex. I would imagine this mutex doesn't show up on unix. That said, this does seem like an issue to open in `mio` rather than here?

**Comment by l3utterfly** [comment]
Understood, thanks for your response!
