### ISSUE TITLE
Make prettyplease optional

### ISSUE THREAD

**Issue by Kixunil** [hyperium/tonic#1018]
### Crates

tonic-build

### Motivation
`prettyplease` uses edition 2021 which makes building on 1.48 impossible. It could also needlessly increase compile times for people who don't need it.

### Proposal

Make `prettyplease` optional and just don't format anything when it's off.

### Alternatives

Persuade the author of `prettyplease` to make it 1.48-compatible. This still leaves larger compile times.

**Comment by LucioFranco** [comment]
Tonic's msrv is 1.56 as stated in the readme so I am not sure if just disabling that will allow things to work on 1.48

**Comment by davidpdrsn** [comment]
> It could also needlessly increase compile times for people who don't need it.

Do you have some data on that? `prettyplease` only has a few deps, the biggest being `syn` but `tonic-build` already depends on that.

**Comment by Kixunil** [comment]
I tried to give it a shot and found out it doesn't actually help with MSRV because there is a bunch of other issues. I will just stay on older version.
