### ISSUE TITLE
enum field not showing up in response when 0

### ISSUE THREAD

**Issue by onx2** [hyperium/tonic#1028]
### Version
├── tonic v0.7.2
└── tonic-build v0.7.2

### Platform
Linux ubuntu 5.13.0-51-generic #58~20.04.1-Ubuntu SMP Tue Jun 14 11:29:12 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Crates
prost = "0.10.4"
prost-types = "0.10.1"

### Description

I have an enum field in proto that I'd like to have returned when I make a request in Postman. I verified the enum will return when not a `0`.

```proto
message User {
  string id = 1;
  enum Status {
    ENABLED = 0;
    DISABLED = 1;
    DELETED = 2;
  }

  Status status = 2;
}
``` 

and in postgres the column definition is
```sql
status INT NOT NULL DEFAULT 0,
```

When I return a `Response::new(User { id, status })`, the field `status` is missing when set to `0`. This is the case for the default value applied from postgres as well as an update to the row to set it to `0`. I also verified the data returned from the db, before inserted into the `User` struct includes the `status: 0`.

Am I doing something wrong? I'd expect all `enum` values to return in the JSON. Could this possibly be a Postman issue or Prost issue?

**Comment by davidpdrsn** [comment]
I'm not sure the discriminant will be used like that when generating the rust enum, however try asking here https://github.com/tokio-rs/prost

**Comment by onx2** [comment]
It seems that `proto3` doesn't serialize default values. https://developers.google.com/protocol-buffers/docs/proto3#default
