### ISSUE TITLE
tonic report invalid flag err but it's not

### ISSUE THREAD

**Issue by TENX-S** [hyperium/tonic#1029]
env:
tonic v0.7.2
tonic-build v0.7.2

macOS 12.4

Hi,
I'm trying to make a tool like [bloomRPC](https://github.com/bloomrpc/bloomrpc). And I prefer to implement the core API with rust.
Here is my [attempt](https://github.com/TENX-S/attempt). Start the server first, then the client. And I get:
```shell
request: {"name": "World"}
reply: {"message": "Hello World!"}
Err(
    Status {
        code: Internal,
        message: "protocol error: received message with invalid compression flag: 10 (valid flags are 0 and 1) while receiving response with status: 200 OK",
        source: None,
    },
)
```

This error is confusing. I use Wireshark to get the packet and the compression flag is not corrupted:

<img width="2880" alt="WeChatb9a6711a0a68355539af8edde50c453d" src="https://user-images.githubusercontent.com/40336192/176588254-93f7a749-f291-4865-ab2f-9993286f423a.png">

**Comment by TENX-S** [comment]
I didn't get it. I guess there is no h1 come into my program?

**Comment by TENX-S** [comment]
The length of the last stream that tonic read is different to the stream in the packet. Is that correct?

<img width="1098" alt="WeChat870723c1e38e2df2c37292590179b63d" src="https://user-images.githubusercontent.com/40336192/176911230-22683d2b-1441-48f3-8c35-f16a582ef060.png">

<img width="1094" alt="WeChat730cec07e10b460d79f3c0d5965dda92" src="https://user-images.githubusercontent.com/40336192/176911264-8c2e6112-19dc-4f45-9b60-86002fdec406.png">

**Comment by TENX-S** [comment]
I've captured the packet by using default client and server. And found that the packet is exactly the same as the previous one, except the date. So, I guess there's a problem with my [decoder](https://github.com/TENX-S/attempt/blob/d9ad7c257697b85c6e829db5109c28a6d4415ab8/src/bin/client.rs#L96)?

**Comment by TENX-S** [comment]
I made it, but I don't know why:
just change my decoder to:
```rust
fn decode(&mut self, src: &mut DecodeBuf<'_>) -> Result<Option<Self::Item>, Self::Error> {
        let buf = src.chunk();
        let length = buf.len();
        let resp = get_hello_response(buf);
        src.advance(length);
        Ok(Some(resp))
}
```

**Comment by timvw01** [comment]
Hello, i have a similar error. May i ask what your decode function looked like before you fixed it? It can give some inspiration on what is going wrong.

Thanks
