### ISSUE TITLE
Improve gRPC richer error model support

### ISSUE THREAD

**Issue by flemosr** [hyperium/tonic#1034]
### Motivation

The [gRPC richer error model] is quite useful to send additional feedback to clients, and is supported by many gRPC libraries in other languages. Implementing it using the [standard error messages] directly (as shown in [#401]) is not very convenient. Specially when sending multiple additional error detail messages.

### Proposal

I recently created a crate ([tonic-richer-error]) that implements a trait to `Status` (and provides some structs) aiming to make the implementation of the richer error model more straightforward. It seems to me that incorporating this crate to tonic as an auxiliary crate would be fairly simple. I could transfer the ownership of the released crate or it could be published after revision with another name.

### Alternatives

A trait similar to [WithErrorDetails] could be implemented on the tonic crate itself.

[gRPC richer error model]: https://www.grpc.io/docs/guides/error/
[standard error messages]: https://github.com/googleapis/googleapis/blob/master/google/rpc/error_details.proto
[#401]: https://github.com/hyperium/tonic/issues/401
[tonic-richer-error]: https://github.com/flemosr/tonic-richer-error
[WithErrorDetails]: https://docs.rs/tonic-richer-error/0.2.1/tonic_richer_error/trait.WithErrorDetails.html

**Comment by LucioFranco** [comment]
Hey! Sorry for the delay on this but I finally got some time to fully understand what you're proposing. I think this fits very well into `tonic-types` in similar vain to `prost-types` but for gRPC. I would totally accept a PR that adds this support there. Happy to mentor and help out.

**Comment by flemosr** [comment]
Hi! Yes, I believe it would fit nicely into `tonic-types` too. I will start working on this PR.

**Comment by flemosr** [comment]
Solved by #1317 .
