### ISSUE TITLE
Either implement Eq where possible or supress clippy lint

### ISSUE THREAD

**Issue by vringar** [hyperium/tonic#1056]
### Version

v0.8.0

### Platform

Linux 5.18.16-200.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Aug 3 15:44:49 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Crates
tonic-build

### Description

When running clippy on [zeebe-client-rust](https://github.com/camunda-community-hub/zeebe-client-rust) the code generated from [this .proto file](https://github.com/camunda-community-hub/zeebe-client-rust/blob/main/client/proto/gateway.proto) generates the following error:

```
warning: you are deriving `PartialEq` and can implement `Eq`
   --> /path/to/project/zeebe-client-rust/target/debug/build/zeebe-client-d9e9efdd95594674/out/gateway_protocol.rs:503:17
    |
503 | #[derive(Clone, PartialEq, ::prost::Message)]
    |                 ^^^^^^^^^ help: consider deriving `Eq` as well: `PartialEq, Eq`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#derive_partial_eq_without_eq
```

The generated struct is:

```rust
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateJobRetriesResponse {
}
```

I would like clippy to run without errors on this project and from what I gathered the only way to do this is to put some attributes in the file or on the struct.

**Comment by LucioFranco** [comment]
I suggest adding the allow macro for this lint (and any others) to the module that imports your proto. Related issue https://github.com/tokio-rs/prost/issues/661#issuecomment-1156606409

**Comment by g0hl1n** [comment]
Is there a reason not to add `Eq` where it's applicable according to clippy?

**Comment by BratSinot** [comment]
> Is there a reason not to add `Eq` where it's applicable according to clippy?

Yeah, same question here. I can call `<something>.eq(other)`, but can't use `<something> == other`.
