### ISSUE TITLE
Allow docstrings for generated modules 

### ISSUE THREAD

**Issue by sezna** [hyperium/tonic#106]
### Crates
`tonic_build`

### Motivation
In all of my company's projects, we use `#![deny(missing_docs)]`. With protobuf codegen, we are able to document all the fields because prost turns `// regular comments` into `/// rust docstrings`. But I still get denied for the overall module which I cannot figure out how to document:

```
missing documentation for module foo:
pub mod foo {

}
```

### Proposal
I'm not sure if this is already possible, and if it would be a part of Tonic, Prost, or somewhere in the middle, but it'd be great to be able to generate code that is compatible with `#![deny(missing_docs)]`. One potential solution is to allow a top-level comment of the form `//!` that then gets transformed into a module docstring.

### Alternatives
Any format to address the missing documentation would be valid. 

After codegen, I can solve the problem by editing the code in my target directory. I've automated this in my `build.rs` for now to get around it, but it is suboptimal. I have tried every combination of `//`, `//!`, and `///` in both my protobuf file and around `tonic::include_proto!` but to no avail.

**Comment by LucioFranco** [comment]
@sezna Hi! So quick and easy fix is to annotate the overall module with `#[allow(missing_docs]`.

Do you by chance know which module is causing the error? is it the client/server mod?

**Comment by sezna** [comment]
I haven't actually used the client or the server yet. Right now I'm just generating structs from .proto files. When I run codegen like this:
```rust
tonic_build::configure().compile(&["foo.proto"], &["../protocol"]).unwrap()
```
it generates code like this:
```rust
#[allow(non_snake_case, unused_attributes)]
mod foo_MESSAGE {
    extern crate bytes as _bytes;
    extern crate prost as _prost;
    use super::*;
    impl _prost::Message for Foo {
       // ... lots of methods
    }
}
// <-- there is no way for me to put a docstring here
pub mod foo { // missing doc warning happens here
    // ... lots of methods and things
}
```

I could wrap the import macro with another module and allow missing docs on it for now, but that doesn't seem optimal, because I would like to have doc enforcement on all of my protobuf fields as I currently do.

**Comment by LucioFranco** [comment]
This sounds like something prost is doing, we add doc comments to all the mods we generate and we just append that to the file that prost generates.

As for wrapping it in a mod I generally tend to do that anyways.

**Comment by sezna** [comment]
Hm, ok. I will wrap it for now and talk to the prost people about this. Thanks!
