### ISSUE TITLE
Use `cleanup-markdown` `prost_build` feature 

### ISSUE THREAD

**Issue by cortopy** [hyperium/tonic#1073]
### Crates

tonic-build

### Motivation

I just saw the new feature in `prost_build` to clean up the markup of generated code using `cleanup-markdown` feature. This has been a problem for me for a long time because googleapis protobuf files are picked up in tests and fail. This would allow for easier test flows

### Proposal

Enable `cleanup-markdown` feature of prost-build

### Alternatives

Not that I know of as prost-build is a dependency of tonic-build, not direct from my project

**Comment by LucioFranco** [comment]
Good idea, we can add a new feature to `tonic-build` that just forwards that specific feature. I would accept a PR for this.

**Comment by cortopy** [comment]
thanks @LucioFranco  I can do a PR but I didn't know enabling a future conditionally was possible with rust. Is there any doc I can read on how it could be done?

**Comment by LucioFranco** [comment]
I believe the best spot to read about it is here https://doc.rust-lang.org/cargo/reference/features.html
