### ISSUE TITLE
question about high availability and hot restart

### ISSUE THREAD

**Issue by GOVYANSONG** [hyperium/tonic#1082]
thanks for the great library. We heavily rely on tonic for our grpc services. Now, a requirement has been debated to explore possibility of making our service high available and support hot restart e.g. no downtime and live connection migration. according to our limited research, existing solutions have been battle tested with other software systems such as envoy, HAProxy, ngingx etc. We would like to get feedback on following points:

* would potential implementation need to be made in tonic or hyper?
* does tonic or hyper expose necessary API for such implementation? since we use unix domain socket, i am hoping that tokio::net::UnixListener be sufficient.

**Comment by LucioFranco** [comment]
Tonic is really just a wrapper around `hyper` so I think its probably better to ask there since it handles all the connections etc.

**Comment by GOVYANSONG** [comment]
cross posted at https://github.com/vercel/hyper/issues/6779. closing.

**Comment by GOVYANSONG** [comment]
https://github.com/hyperium/hyper/issues/2992
