### ISSUE TITLE
[Question] How to call RPC over the same RPC request repeatedly without cloning/creating a new request every time?

### ISSUE THREAD

**Issue by crazyboycjr** [hyperium/tonic#1083]
Let's say I create a `struct HelloRequest { data: Vec<u8> } ` over a large piece of data and want to call `client.say_hello(req)` over the same `req` repeatedly. It seems that the current tonic's API consumes the input parameter which means I must create a new `HelloRequest` each time.

How can I avoid cloning the data when making the RPC (e.g., by passing a reference)? Thanks!

**Comment by crazyboycjr** [comment]
Or please let me know if this need is unreasonable.

**Comment by crazyboycjr** [comment]
cc @LucioFranco

**Comment by LucioFranco** [comment]
@crazyboycjr this is more related to `prost` which provides the protobuf messages. Its possible to enable the bytes feature and configure your message to generate a `Bytes` type which would all you to clone the inner data cheaply.

**Comment by crazyboycjr** [comment]
Thanks for the advice @LucioFranco! This is helpful. I was trying to give a toy example. In a more general case where the `HelloRequest` is more complex and contains many other fields, is it still possible to pass in the same RPC argument without cloning? I feel this question would relate to tonic more.

**Comment by LucioFranco** [comment]
Tonic just accepts an owned message from `prost`. So cloning the inner fields etc relates to prost. As for that, it depends expensive big fields like bytes/vec<u8> are able to be swapped but other fields are not but some just implement Copy like integers etc.

**Comment by crazyboycjr** [comment]
I see. TL;DR: As long as we can avoid data copy of the inner fields (e.g., bytes can do the trick, a few integers are cheap to copy, but strings and hashmaps would require more investigation), we are good.

The following discussion might be a little off-topic and might be worth a separate issue, but it is quite related to the original question.

I believe that it makes a lot of sense to let tonic accept an owned message. Have you also considered an alternative API where the input parameter is passed by a shared reference, and the output parameter is returned by an owned value? An example without `Request/Response` and `IntoRequest` wrappers could be similar to `async fn call(_: &SomeRequest) -> Result<SomeResponse, Status>`. Would you mind sharing some original design decisions?

Just some quick answers of pros and cons would be great, but feel free to close the issue and move the discussion elsewhere if you have more to share. Thanks so much!

**Comment by LucioFranco** [comment]
This mostly revolves around the fact that hyper accepts an owned `Request` type and tonic is just a small layer ontop of that providing the grpc protocol. So the reason its not shared is because of that and rust's ownership system with stuff moving around on threads etc.

**Comment by crazyboycjr** [comment]
Make sense! That solves all my questions. Thanks so much @LucioFranco!
