### ISSUE TITLE
[Question] How to modify `tonic::Response` struct to add custom headers using `metadata_mut()` within the service?

### ISSUE THREAD

**Issue by thatsbrandon** [hyperium/tonic#1098]
I'm writing a session auth microserivce & so far tonic has been a breeze to work with but I recently came upon a road block when I wanted to pass a session cookie as a header inside a `tonic::Response` back to the client. Looking at the [docs](https://docs.rs/tonic/latest/tonic/struct.Response.html) I can't seem to find a way to add a header unless I write
```rs
let response = Response::new(SessionResponse {
      session_id: session_token.to_string()
}).metadata_mut().into_headers().insert("Location", "/test".parse().unwrap());
```
This clearly doesn't work since I need to return a `tonic::Response` & not  a `Option<HeaderValue>`.

Does anyone know way of modifying the `tonic::Response` struct? I'm not sure if an `interceptor` would work but that seems to be designed for manipulating incoming request.

**Comment by davidpdrsn** [comment]
Metadata becomes http headers. So you don't need to call `into_headers`. Just do

```rust
let mut res = Response::new(...);
res.metadata_mut().insert(...);
```

**Comment by thatsbrandon** [comment]
@davidpdrsn Solution was so simple, a mutable variable completely wen't over my head. Thank you mate :)
