### ISSUE TITLE
Why do we need to set port here?

### ISSUE THREAD

**Issue by nikt12** [hyperium/tonic#1099]
Hello folks! Could somebody explain why do we need to use port here even we are using uds?
https://github.com/hyperium/tonic/blob/0b03b30cccc67d517b05587614405d63d942b1bb/examples/src/uds/client.rs#L20

**Comment by davidpdrsn** [comment]
Its just an inconvenience with the current API. Its ignored internally but you still have to set it. Something we should fix at some point probably 😬

**Comment by nikt12** [comment]
thanks for response!
