### ISSUE TITLE
Remove `NamedService` bound for `tonic_web::enable`

### ISSUE THREAD

**Issue by slinkydeveloper** [hyperium/tonic#1115]
## Bug Report

`tonic_web::enable` has a bound on `NamedService` used only for logging purposes.

### Version

```
➜ cargo tree | grep tonic
│   ├── tonic v0.8.0
│   ├── tonic v0.8.0 (*)
├── tonic v0.8.0 (*)
├── tonic-web v0.4.0
│   ├── tonic v0.8.0 (*)
└── tonic-build v0.8.0
├── tonic v0.8.0 (*)
```

### Crates

* `tonic-web`

### Description

This bound is not really needed, and requires to be implemented in cases such as when users manually implement the underlying service. Does it makes sense to remove it?

**Comment by LucioFranco** [comment]
Yeah, seems fair to remove, I believe we could just pull the path for logging to check the service.

**Comment by slinkydeveloper** [comment]
WDYM by pulling the path? Removing it altogether?

**Comment by LucioFranco** [comment]
The path from the http Request type that comes in, it should contain something like`/package/ServceName`
