### ISSUE TITLE
Improve stringified result of `transport::Error`

### ISSUE THREAD

**Issue by drHuangMHT** [hyperium/tonic#1135]
Current result can't give enough information about the cause of the error. Will there be some way to access it's internal beside using `{:#?}` template? Or is it intentional?

**Comment by davidpdrsn** [comment]
You can call https://doc.rust-lang.org/stable/std/error/trait.Error.html#method.source to access the source.

**Comment by drHuangMHT** [comment]
> You can call https://doc.rust-lang.org/stable/std/error/trait.Error.html#method.source to access the source.

Oops I did not import the trait, that's why I didn't see the method. I do apologize for my ignorance. Thanks for your help!
