### ISSUE TITLE
How can I send request from server to client?

### ISSUE THREAD

**Issue by HHoflittlefish777** [hyperium/tonic#1157]
Now I need to let the server send messages to the client actively. Do you have any specific examples ?Thanks.

**Comment by davidpdrsn** [comment]
You can use a server to client stream. See the guides in the examples folder for more info.

**Comment by HHoflittlefish777** [comment]
The reason why I raised the question was that I did not find a specific path in examples folder，can you tell me where I can refer? 
 @davidpdrsn

**Comment by davidpdrsn** [comment]
https://github.com/hyperium/tonic/blob/master/examples/routeguide-tutorial.md

**Comment by HHoflittlefish777** [comment]
thanks
