### ISSUE TITLE
Unhandled unwrap()

### ISSUE THREAD

**Issue by amsmith-pro** [hyperium/tonic#1172]
https://github.com/hyperium/tonic/blob/c4525ba6ad21cf9db8d1857931f430cbe924aeb5/tonic-build/src/server.rs#L163

We'd like to prune unhandled `unwrap()`s from our codebase, we see that this unwrap() is used in autogenerated server code

I can submit a PR from a fork if you have a preferred method for handling this, e.g. `unwrap_or_else`.

Thank you!

**Comment by davidpdrsn** [comment]
IMO this unwrap is totally fine. The headers being added [here](https://github.com/hyperium/tonic/blob/c4525ba6ad21cf9db8d1857931f430cbe924aeb5/tonic-build/src/server.rs#L160-L161) are valid so it'll never panic.

**Comment by LucioFranco** [comment]
Yeah, this unwrap is never going to trigger since its been statically verified. We could change it to an expect if that makes detection of these things easier but generally speaking unwraps that are verified to not happen are ok to have!

**Comment by AmeliaRose802** [comment]
Hey, I'm running into a similar issue and landed here from google. 

I'm trying to enable clippy lints to prevent unhandled unwraps and expects in our codebase. I'm running into issues as the linter is flagging the tonic autogenerated code. 

I found this [closed issue on the clippy repo ](https://github.com/rust-lang/rust-clippy/issues/2305) which suggests adding a supress statement to the generated code. It dosn't seem to be possible to suppress clippy for an folder without modifying the files themselves. 

I see that other lints are suppressed in the autogenerated code. Would it be possible to add `#[allow(clippy::unwrap_used)]` before the unwrap? 

If not, is there any way using the tonic builder in my build file to insert this?

**Comment by LucioFranco** [comment]
@AmeliaRose802 hi, we can probably add the lint to the generated code allow's list. I would happily accept a PR for this.

**Comment by dswij** [comment]
Seems easier just to change it to use `expect`, no?
