### ISSUE TITLE
Possible memory leak? 

### ISSUE THREAD

**Issue by mikemiles-dev** [hyperium/tonic#1175]
## Bug Report
Consider this code:
```
async fn send_event(&self, event) {
        let request = tonic::Request::new(EventRequest {
            event: event.clone(),
        });

        let result = self.client.report_event(request).await;
}
```
self.client is my Proto Client using a InterceptedService<Channel, BearerTokenInterceptor>.

Not sure if this is an issue with Tonic or gRPC in general.  If, let's say, my gRPC service can't keep up with with these requests and since you are using futures with async, is tonic going to hold on to these requests in memory?  Especially if more requests keep coming in?  I am seeing a memory issue with just this case as described.

### Version
0.8.3

-->

### Platform

Mac OS 

### Crates
Tonic
-->

**Comment by LucioFranco** [comment]
I don't see any issues with the code you posted. You'd have to better describe your memory leak issue.

**Comment by mikemiles-dev** [comment]
@LucioFranco apologies.  I believe this can be closed.  The situation isn't related directly to the library.  Since the gRPC functions are called in an async fashion if I have many requests that all kick off n+ gRPC calls then I can get into a situation where the application now can't keep up as more async requests are coming in then can be processed.
