### ISSUE TITLE
document tonic-build configure method

### ISSUE THREAD

**Issue by blittable** [hyperium/tonic#118]
On: tonic-build v0.1.0-alpha.5 (/code/tonic/tonic-build)

We need api doc.

This method is also helpful for diagnosing protobuf build issues - (pb namespace, permissions, rustfmt, toolchain, config, etc.)  

https://docs.rs/tonic-build/0.1.0-alpha.5/tonic_build/fn.configure.html

https://github.com/hyperium/tonic/blob/23f648b5175b24c24f61bfd8cfb7235fcbae552a/tonic-build/src/lib.rs#L166

**Comment by blittable** [comment]
#102

**Comment by LucioFranco** [comment]
@blittable maybe im missing something, but is the api not documented? I assume you mean we should improve its documentation?

**Comment by blittable** [comment]
Maybe a sample on that link with the additional configuration options?  (Like out_dir)
