### ISSUE TITLE
Fetching Server TLS Certificate from Client Side

### ISSUE THREAD

**Issue by AnimeshAgrawal** [hyperium/tonic#1180]
hi! I'm trying to do some custom TLS certificate verification using tonic on the client side. This requires me to access the server TLS certificate when I make a connection, but I wasn't able to find a solution in the API docs. What's the best way to access the TLS certificate chain of the server?

what I've tried:
- I saw that there's a get_peer_certificates (https://docs.rs/tonic/latest/tonic/struct.Request.html#method.peer_certs) function in Request, but this seems to be giving client certs
- I found ways to access certs through rusTLS, but I can't figure out whether tonic exposes these. https://docs.rs/rustls/latest/rustls/struct.ClientConnection.html#method.peer_certificates
- I saw there's a peer_certs function in TlsConnectInfo (https://docs.rs/tonic/latest/tonic/transport/server/struct.TlsConnectInfo.html#method.peer_certs), but I'm not able to access TlsConnectInfo through extensions (is it supposed to be included by default? do I need to write an interceptor?)

**Comment by blakat360** [comment]
What did you end up doing? I used an interceptor but still never get any peer certificates even when using TLS. The same code does give me the client's certs when running server side
