### ISSUE TITLE
Consider making users not explicitly declare dependencies needed by generated code

### ISSUE THREAD

**Issue by rylev** [hyperium/tonic#123]
### Crates

This arguably effects both `tonic` and `tonic_build`

### Motivation

It is quite confusing when you write one line of code and it produces an absolute mountain of error messages. This is what happens when you generate code using `tonic_build` and you then include that generated code using `tonic::include_proto!`. 

This is because the generated code not only depends on `tonic` but all: `prost`, `bytes`, and `prost-types`.

### Proposal

One possible solution to this is to expose those dependencies through `tonic` so that as long as the user is depending on tonic, the generated code will work. This can be done by not documenting this explicitly and discouraging the user of these dependencies through `proto` except for in the generated code. 

### Alternatives

Alternatively, things can be left how they are and simply documented better.

**Comment by carllerche** [comment]
Thanks for bringing this up. I think your proposal is on point. Tonic can have doc hides re-exports of types it needs. @LucioFranco, what do you think?

**Comment by LucioFranco** [comment]
So this is actually a `prost` issue specifically with `prost_derive` I believe. It refernces `prost`, `bytes` and `prost-types` directly. Tonic's codegen runs through the codegen module to avoid this issue but this something that would need to be upstreamed into prost unfortunetly.

**Comment by LucioFranco** [comment]
Related upstream issue https://github.com/danburkert/prost/issues/127

**Comment by LucioFranco** [comment]
@rylev thanks for reporting! I've made sure to update the docs and this should come out with `tonic 0.1`.
