### ISSUE TITLE
Add zstd compression support

### ISSUE THREAD

**Issue by zamazan4ik** [hyperium/tonic#1236]
## Feature Request
Add a `zstd` compression support, in additionally to the already supported gzip.

### Motivation

`zstd` is a modern efficient compression algorithm. It usually works faster with almost the same compression ratio. Would be awesome to have an option to enable `zstd` support in tonic.

### Proposal

1. Add `zstd` dependency
2. Add `zstd` support to `CompressionEncoding` enum and the related methods.

**Comment by tottoto** [comment]
Resolved in #1532.
