### ISSUE TITLE
Remove manual `protobuf` installation requirement.

### ISSUE THREAD

**Issue by j-mendez** [hyperium/tonic#1238]
## Feature Request

It would make the package entry friendly if we handled the protobuf compiler automatically instead of needing manual steps.

### Motivation

Easier entry for users and projects.

### Proposal

On build check the OS if the depandacies are found. If not installed perform auto installs to build the package.

**Comment by j-mendez** [comment]
I started a pre-installation setup here https://github.com/a11ywatch/crawler/commit/00d58a6be340690894c507947bcdcc1327227139. It needs to switch to using the pre-compiled binaries for easier cross install.

**Comment by LucioFranco** [comment]
I do not believe a build script should be install external tools. Users can write that like you did if they want that but imho prost should not provide that and should remain lean. This is more so for a better security posture to put it onto the user to figure out what makes best sense for them and their users.

In the future, hopefully, we will have a native parser so you don't need protoc at all but for now this is currently the best way. If you want to understand more why on the decisions you can look up the relevant issues and PRs about removing the build script.

**Comment by j-mendez** [comment]
I agree and very valid points, thanks for the explanation. It would be hard to pin the version across each update and OS as well. I am looking forward to the changes on the native parser. One of the road blocks I am facing is having users perform manual actions on installation even with docs. Right now tonic is the only crate in my project that has the manual step, so I am very interested in the native parser. Is there a Rust crate for proto parsing now that could be used until then?

**Comment by LucioFranco** [comment]
@j-mendez if the proto code doesnt change you can just check the protobuf code into source and downstream users don't need to have protoc or run the build script at all.

**Comment by j-mendez** [comment]
> @j-mendez if the proto code doesnt change you can just check the protobuf code into source and downstream users don't need to have protoc or run the build script at all.

I like the sound of that, thanks for the direction.

**Comment by chenzhekl** [comment]
I am just a bit curious what stops tonic from dropping `protoc` altogether. It seems that `prost` is able to do everything `protoc` can do.
