### ISSUE TITLE
Unable to skip domain name verification when tls enabled

### ISSUE THREAD

**Issue by TommyLike** [hyperium/tonic#1258]
### Version

```
❯ cargo tree | grep tonic                
├── tonic v0.8.3
└── tonic-build v0.8.4

```

### Description
I am creating my grpc service by utilizing tonic crate, the question is I am unable to skip domain verification at the client side
```
let client_config = ClientTlsConfig::new()
            .identity(identity).domain_name("some.domain.com");;
```
the code above works well but if I remove the domain_name method it will raise error:
```
 Some(RemoteSignError("Status { code: Unavailable, message: \"error trying to connect: presented server name type wasn't supported\", source: Some(tonic::transport::Error(Transport, hyper::Error(Connect, Custom { kind: InvalidData, error: UnsupportedNameType }))) }"))
```

**Comment by LucioFranco** [comment]
Right I believe the TLS implementation requires a domain no matter what. If you want to work around it you may want to swap out the default tls implementation with openssl.

Here is an example of a custom tls impl using rustls https://github.com/hyperium/tonic/blob/master/examples/src/tls/client_rustls.rs you can just replace it with tokio-openssl and it all should work.

**Comment by super-secret-github-user** [comment]
the link is broken, how do i swap to openssl?

**Comment by moqix** [comment]
Here: https://github.com/hyperium/tonic/blob/master/examples/src/tls_rustls/client.rs
