### ISSUE TITLE
How to create Reflection server with manual build?

### ISSUE THREAD

**Issue by lykhouzov** [hyperium/tonic#1297]
I am following examples and built an example server and client.
I found an example of manually created server/client with codec.
also found example with reflection service.
But reflection can be create form `.proto` files only, there is no option/way how to make it in manual build

Do you have any suggestions how could I make it?

**Comment by LucioFranco** [comment]
The protos for reflection are generated into the source code already so there is no need to build it manually. You could always just copy the code if you wanted to modify it for your use case.
