### ISSUE TITLE
Endpoint::connect_lazy()  cause main thread panic

### ISSUE THREAD

**Issue by Ruoye-W** [hyperium/tonic#1298]
## Bug Report
I tried to use tonic 0.8.3 to create client channel,  but thread main paniced when I invoke:
endpoint
            .timeout(Duration::from_secs(5))
            .keep_alive_timeout(Duration::from_secs(600))
            .keep_alive_while_idle(true)
            **.connect_lazy();**
error message: "no reactor running, must be called from the context of a tokio 1.x runtime". It seems that tokio version in my program was different from which tonic depend on, but my tokio verison in program was 1.25.0.

### Version

cargo tree | grep tonic 

├── tonic v0.8.3
└── tonic-build v0.8.4

cargo tree | grep tokio

│   │   ├── tokio v1.25.0
│   │   │   └── tokio-macros v1.8.2 (proc-macro)
│   │   ├── tokio-util v0.7.7
│   │   │   ├── tokio v1.25.0 (*)
│   ├── tokio v1.25.0 (*)
│   │   └── tokio v1.25.0 (*)
│   │   └── tokio v1.25.0 (*)
│   │   └── tokio v1.25.0 (*)
│   │   │   ├── tokio v1.25.0 (*)
│   │   │   └── tokio-util v0.7.7 (*)
│   │   ├── tokio v1.25.0 (*)
│   │   ├── tokio-util v0.7.7 (*)
│   │   │   ├── tokio v1.25.0 (*)
│   │   │   └── tokio-rustls v0.23.4
│   │   │       ├── tokio v1.25.0 (*)
│   │   │   ├── tokio v1.25.0 (*)
│   │   │   └── tokio-native-tls v0.3.1
│   │   │       └── tokio v1.25.0 (*)
│   │   ├── tokio v1.25.0 (*)
│   │   ├── tokio-native-tls v0.3.1 (*)
│   │   ├── tokio-rustls v0.23.4 (*)
│   │   ├── tokio-util v0.7.7 (*)
│   ├── tokio v1.25.0 (*)
├── tokio v1.25.0 (*)
├── tokio-serde v0.8.0
├── tokio-util v0.7.7 (*)
│   │   │   ├── tokio v1.25.0 (*)
│   │   │   ├── tokio-util v0.7.7 (*)
│   │   ├── tokio v1.25.0 (*)
│   │   └── tokio-io-timeout v1.2.0
│   │       └── tokio v1.25.0 (*)
│   ├── tokio v1.25.0 (*)
│   ├── tokio-stream v0.1.12
│   │   └── tokio v1.25.0 (*)
│   ├── tokio-util v0.7.7 (*)
        ├── tokio v1.25.0 (*)

### Platform

Darwin MacBook-Pro-7.local 21.6.0 Darwin Kernel Version 21.6.0: Sat Jun 18 17:07:25 PDT 2022; root:xnu-8020.140.41~1/RELEASE_X86_64 x86_64

### Description

print stack backstrace:
thread 'main' panicked at 'there is no reactor running, must be called from the context of a Tokio 1.x runtime', /Users/bytedance/.cargo/registry/src/github.com-1ecc6299db9ec823/tonic-0.8    .3/src/transport/service/executor.rs:15:9
  7 stack backtrace:
  8    0: rust_begin_unwind
  9              at ./rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:575:5
 10    1: core::panicking::panic_fmt
 11              at ./rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/panicking.rs:64:14
 12    2: core::panicking::panic_display
 13              at ./rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/panicking.rs:135:5
 14    3: tokio::runtime::scheduler::Handle::current
 15              at ./Users/bytedance/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/scheduler/mod.rs:57:27
 16    4: tokio::runtime::handle::Handle::current
 17              at ./Users/bytedance/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/handle.rs:102:20
 18    5: tokio::task::spawn::spawn_inner
 19              at ./Users/bytedance/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/task/spawn.rs:184:22
 20    6: tokio::task::spawn::spawn
 21              at ./Users/bytedance/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/task/spawn.rs:171:13
 22    7: <tonic::transport::service::executor::TokioExec as hyper::rt::Executor<F>>::execute
 23              at ./Users/bytedance/.cargo/registry/src/github.com-1ecc6299db9ec823/tonic-0.8.3/src/transport/service/executor.rs:15:9
 24    8: <tonic::transport::service::executor::SharedExec as hyper::rt::Executor<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future+Output = ()+core::marker::Send>>>>::execute
 25              at ./Users/bytedance/.cargo/registry/src/github.com-1ecc6299db9ec823/tonic-0.8.3/src/transport/service/executor.rs:41:9
 26    9: tonic::transport::channel::Channel::new
 27              at ./Users/bytedance/.cargo/registry/src/github.com-1ecc6299db9ec823/tonic-0.8.3/src/transport/channel/mod.rs:162:9
 28   10: tonic::transport::channel::endpoint::Endpoint::connect_lazy
 29              at ./Users/bytedance/.cargo/registry/src/github.com-1ecc6299db9ec823/tonic-0.8.3/src/transport/channel/endpoint.rs:344:13

I've tried to use tonic 0.7.2 and other lower versions, and other lower tokio verisons(1.20.0, 1.24.1) as well, but doesn't work.

**Comment by LucioFranco** [comment]
> thread 'main' panicked at 'there is no reactor running, must be called from the context of a Tokio 1.x runtime',

This is a general tokio issue unrelated to tonic, it has to do with how you setup your code and it seems like maybe you're not running the code within any async context.

**Comment by Ruoye-W** [comment]
> > thread 'main' panicked at 'there is no reactor running, must be called from the context of a Tokio 1.x runtime',
> 
> This is a general tokio issue unrelated to tonic, it has to do with how you setup your code and it seems like maybe you're not running the code within any async context.

Yes, I'm trying to create a connect-lazy channel in a sync context, because there is only async connect function to use. According to the annotation, connect-lazy channel will actually invoke connect() when it is being used first time. Could you please tell me the reason that the connect_lazy() cannot be used in sync context?

**Comment by LucioFranco** [comment]
You still need to invoke it in an async context since it needs to spawn stuff even if it doesn't connect right away.
