### ISSUE TITLE
cosmos-rust: gRPC "transport error": GoAway(b"", FRAME_SIZE_ERROR, Library)

### ISSUE THREAD

**Issue by Philipp-Sc** [hyperium/tonic#1341]
## Bug Report
Hi,

I am using [cosmos-rust](https://github.com/cosmos/cosmos-rust) to query validator nodes via gRPC.

The following error is causing me trouble:

```bash
GetNodeInfoRequest failed for http://osmosis-grpc.lavenderfive.com:443: Status { code: Unknown, message: "transport error", source: Some(tonic::transport::Error(Transport, hyper::Error(Http2, Error { kind: GoAway(b"", FRAME_SIZE_ERROR, Library) }))) }
```

Note: the endpoint is taken from the [chain registry](https://github.com/cosmos/chain-registry).
I tested the same endpoint using grpcurl and that worked fine:
```bash
docker run fullstorydev/grpcurl osmosis-grpc.lavenderfive.com:443 cosmos.base.tendermint.v1beta1.Service/GetNodeInfo
```
 Also for most blockchains/endpoints I can successfully send gRPC requests without any issues. I am opening this issue just because for osmosis all endpoints fail, leaving me without fallback option.

Here the code used send gRPC requests to the nodes:
```rust
async fn get_channel(grpc_url: String) -> anyhow::Result<Channel> {
    let endpoint =
        tonic::transport::Endpoint::new(grpc_url.parse::<tonic::transport::Uri>().unwrap())
            .unwrap();
    match endpoint.connect().await {
        Ok(result) => Ok(result),
        Err(err) => Err(anyhow::anyhow!(err)),
    }
}

async fn check_grpc_url(grpc_url: String) -> anyhow::Result<String> {
    match get_channel(grpc_url.to_owned()).await {
        Ok(c) => {
            match cosmos_sdk_proto::cosmos::base::tendermint::v1beta1::service_client::ServiceClient::new(c).get_node_info(GetNodeInfoRequest{}).await {
                Ok(_node_info_response) => {
                    // TODO: potentially check versions, check node health.
                    Ok(grpc_url)
                },
                Err(e) => {
                    //println!("{:?}",e);
                    Err(anyhow::anyhow!(e))
                }
            }
        }
        Err(e) => Err(anyhow::anyhow!(e)),
    }
}
```
the full code can be found [here](https://github.com/Philipp-Sc/cosmos-rust-package/blob/829c3a8b1cc8cce92c54a69dcad2ad1ac3495b47/src/api/core/cosmos/channels/mod.rs) 

I opened this issue first here: https://github.com/cosmos/cosmos-rust/issues/361
There is also a similar setup with the same error from a while back, the issue is still unresolved: https://github.com/cosmos/cosmos-rust/issues/313

### Version

```rust
prost = "^0.11"
prost-types = "^0.11"
tonic = { version = "^0.8", features = ["transport","tls"] }
``` 

Please let me know if you have any ideas how to resolve this issue.
Thanks in advance.

**Comment by tony-iqlusion** [comment]
@Philipp-Sc from the URL:

```
http://osmosis-grpc.lavenderfive.com:443
```

It looks like you're sending a plaintext HTTP request to an HTTPS port?

**Comment by Philipp-Sc** [comment]
@tony-iqlusion when I change the schema to ```https://``` an leave everything else the same I get the following error:

```
Unable to establish a connection to https://osmosis-grpc.lavenderfive.com:443: transport error
    
    Caused by:
        0: error trying to connect: Connecting to HTTPS without TLS enabled
        1: Connecting to HTTPS without TLS enabled
```

Does this mean my client-side code is configured incorrectly? Can I tell tonic to enable TLS?

**Comment by Philipp-Sc** [comment]
@tony-iqlusion 

I have the suspicion that I am missing a feature flag. I added **"tls-roots"**, testing right now.

```tonic = { version = "^0.8", features = ["transport","tls","tls-roots"] }```

**Comment by Philipp-Sc** [comment]
Awesome it now works:
```
tonic = { version = "^0.8", features = ["transport","tls","tls-roots","tls-webpki-roots"] }
```

@tony-iqlusion thanks for the hint, it lead me into the right direction.

**Comment by snoww-leopard** [comment]
> Awesome it now works:
> 
> ```
> tonic = { version = "^0.8", features = ["transport","tls","tls-roots","tls-webpki-roots"] }
> ```
> 
> [@tony-iqlusion](https://github.com/tony-iqlusion) thanks for the hint, it lead me into the right direction.

Thanks mate it works for me as well
