### ISSUE TITLE
peer_certs() not available in middleware layer

### ISSUE THREAD

**Issue by brsnik** [hyperium/tonic#1342]
### Version

tonic v0.9.0
tonic-build v0.9.0

### Platform

22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023;
root:xnu-8796.101.5~3/RELEASE_ARM64_T6000 arm64

### Description

I need to be able to authenticate the certificate serial number in the case of mTLS.
For this I need a connection to a database. 

So I modified the middleware example to this:

```
#[derive(Debug, Clone, Default)]
struct MyMiddlewareLayer {
    conn: DatabaseConnection,
}

impl<S> Layer<S> for MyMiddlewareLayer {
    type Service = MyMiddleware<S>;

    fn layer(&self, service: S) -> Self::Service {
        MyMiddleware {
            inner: service,
            conn: self.conn.clone(),
        }
    }
}

#[derive(Debug, Clone)]
struct MyMiddleware<S> {
    inner: S,
    conn: DatabaseConnection,
}

impl<S> Service<hyper::Request<Body>> for MyMiddleware<S>
where
    S: Service<hyper::Request<Body>, Response = hyper::Response<BoxBody>> + Clone + Send + 'static,
    S::Future: Send + 'static,
{
    type Response = S::Response;
    type Error = S::Error;
    type Future = futures::future::BoxFuture<'static, Result<Self::Response, Self::Error>>;

    fn poll_ready(&mut self, cx: &mut Context<'_>) -> Poll<Result<(), Self::Error>> {
        self.inner.poll_ready(cx)
    }

    fn call(&mut self, mut req: hyper::Request<Body>) -> Self::Future {
        // This is necessary because tonic internally uses `tower::buffer::Buffer`.
        // See https://github.com/tower-rs/tower/issues/547#issuecomment-767629149
        // for details on why this is necessary
        let clone = self.inner.clone();
        let mut inner = std::mem::replace(&mut self.inner, clone);

        req.extensions_mut().insert(AppState {
            connection: self.conn.clone(),
        });

        Box::pin(async move {
            // Do extra async work here...
            let response = inner.call(req).await?;

            Ok(response)
        })
    }
}
```
And how I pass the connection: 
```
 Server::builder()
        .layer(MyMiddlewareLayer { conn: conn.clone() })
        .tls_config(tls)?
        .add_service(
            UsersServer::new(UserOperations {}),
        )
        .serve(addr)
        .await?;
 ```

So now I have a connection pool available in the middleware, however, the request does not have `.peer_certs()` so I can extract the client cert used and validate the serial number against a database.

I tried to access it in the call fn:
```
fn call(&mut self, mut req: Request<Body>) -> Self::Future {
...
```

What would be my solution here?

**Comment by LucioFranco** [comment]
This is a bit hacky but you could try to https://docs.rs/tonic/latest/tonic/struct.Request.html#method.from_http convert it into a tonic request which will then allow you to call that method. Then you convert back into a http::Request via into_parts. You then will have to convert each part into their http variant via https://docs.rs/tonic/latest/tonic/metadata/struct.MetadataMap.html#method.into_headers and https://docs.rs/tonic/latest/tonic/struct.Extensions.html#method.into_http and it should work. Its a bit hacky but should work for now.

**Comment by brsnik** [comment]
I ended up doing this:
```
req.extensions()
      .get::<TlsConnectInfo<TcpConnectInfo>>()
      .and_then(|i| i.peer_certs())
      .and_then(|certs| certs.first().cloned())
```
