### ISSUE TITLE
how to reuse gRpc client?

### ISSUE THREAD

**Issue by spursy** [hyperium/tonic#1388]
As the followed code displayed, I found tonic gRpc client is mut when i need to call server.

While I receive a request, I establish gRpc connection again, Do it have performance issue?

How can i reuse gRpc client connection, Could anyone give me some advise?

```rust
	let mut bert_svc_client =
		BertSvcClient::connect("127.0.0.1:8080").await.unwrap();
	let request = Request::new(GenerateVectorReq { sentences: input_params });
	let response = bert_svc_client.generate384_dim_vector(request).await.unwrap();
```

**Comment by SZenglein** [comment]
The way I do it is to use a [channel](https://docs.rs/tonic/latest/tonic/transport/struct.Channel.html) which can be used to construct a client.  
The doc I linked explicitly mentions the channel is meant to be *cloned* and explains the reasioning, which also applies to the client.
