### ISSUE TITLE
tls-roots doesn't work on android or ios devices

### ISSUE THREAD

**Issue by stan-irl** [hyperium/tonic#1403]
## Bug Report
Flagging this because I spent a few hours working out that this is a problem and other people will probably hit it. rustls-native-certs [doesnt support android or iOS](https://github.com/rustls/rustls-native-certs/issues/3) so you'll need to setup https://github.com/rustls/rustls-platform-verifier or enable feature `tls-webpki-roots`.

### Version

0.9.2

### Platform

- ios
- android

### Crates

tonic

### Description

Connecting to an AWS LB returns error: ` status: Unavailable, message: "error trying to connect: invalid peer certificate: UnknownIssuer"`

**Comment by vdhanan** [comment]
Thanks for flagging this!! Saved me some time
