### ISSUE TITLE
Add support for MAX_CONNECTION_AGE and MAX_CONNECTION_AGE_GRACE equivalents

### ISSUE THREAD

**Issue by jalaziz** [hyperium/tonic#1428]
### Motivation

In order to properly support DNS-based client side gRPC load balancing, the server must periodically terminate the client connection gracefully by sending a `GOWAY` frame and subsequently closing the connection.

`MAX_CONNECTION_AGE` and `MAX_CONNECTION_AGE_GRACE` are defined in the [gRPC Server-side connection management](https://github.com/grpc/proposal/blob/master/A9-server-side-conn-mgt.md).

Unfortunately, due the inconsistent support of client connection timeout settings in gRPC client libraries, the current recommendation appears to be to use service side.

These issues provide more context:
* https://github.com/grpc/grpc-go/issues/1663#issuecomment-343566633
* https://github.com/grpc/grpc/issues/12295

### Proposal

Introduce `max_connection_age` and `max_connection_age_grace` server timeouts. On first look, it appears support would need to be added to `hyper` first.

### Alternatives

The alternative is client side timeouts. Unfortunately, client side timeouts are not implemented consistently. See https://github.com/grpc/grpc-go/issues/1663.

I am not aware of any alternatives other than service meshes, proxies, xDS, or a custom gRPC resolver or load balancing mechanism (all of which can be quite complex).

**Comment by ionut-slaveanu** [comment]
I created a pull request here:
https://github.com/hyperium/tonic/pull/1865

**Comment by jalaziz** [comment]
Closing this now that #1865 has been merged.
