### ISSUE TITLE
Rustdoc fails weirdly on tonic related snippets

### ISSUE THREAD

**Issue by zmrocze** [hyperium/tonic#1435]
## Version

 - tonic v0.9.2
 - tonic-build v0.9.2
 - prost
 - async_trait

## Description

I'm running doctests with `cargo test --all`. My tests fail without any clear reason, as there is no codeblocks in my code (no triple ticks anywhere). 

There's two types of errors, these may involve macro expansions. All the errors involve some snippets related to `tonic`, this  is why I file this bug here, in hope that the errors are generated by the macro expansions + code generation. I cross-link the issue to `rustdoc` as well [HERE](https://github.com/rust-lang/rust/issues/114025).

### first type: 

```rust
#[tonic::async_trait]
impl Platform for PlatformServerState {
  #[instrument(
    name = "ServerHandler",
    skip_all
  )]
  async fn ping(&self, _: Request<PingMsg>) -> Result<Response<PongAnswer>, Status> {
    info!("Got a ping request");
    Ok(Response::new(PongAnswer {}))
  }
}
```

contains no codeblocks but shows in the error message as: 

```
error[E0433]: failed to resolve: could not find `pin` in `core`
  --> /home/zmrocze/mlabs/walkways/walkways/core/src/platform/communication.rs:84:3
   |
84 |   async fn ping(&self, _: Request<PingMsg>) -> Result<Response<PongAnswer>, Status> {
   |   ^^^^^ could not find `pin` in `core`
```

### Second type originates in some generated code (by prost I suppose):

First error message:
```
error[E0433]: failed to resolve: could not find `result` in `core`
 --> /home/zmrocze/mlabs/walkways/walkways/target/debug/build/core-70621e4fd67026d0/out/platform.rs:2:28
  |
2 | #[derive(Clone, PartialEq, ::prost::Message)]
  |                            ^^^^^^^^^^^^^^^^ could not find `result` in `core`
  |
  = note: this error originates in the derive macro `::prost::Message` (in Nightly builds, run with -Z macro-backtrace for more info)
```

and the code snippet, but note that it's not part of my codebase strictly:

```rust
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StartMsg {}
```

## Meta
`rustc --version --verbose`:
```
rustc 1.72.0-nightly (f0411ffce 2023-05-30)
binary: rustc
commit-hash: f0411ffcebcd7f75ac02ed45feb53ffd07b75398
commit-date: 2023-05-30
host: x86_64-unknown-linux-gnu
release: 1.72.0-nightly
LLVM version: 16.0.4

```

**Comment by LucioFranco** [comment]
Seems like it may just be a nightly bug? It doesn't seem related to tonic so going to close this issue.
