### ISSUE TITLE
Graceful shutdown docs/example/default-impl

### ISSUE THREAD

**Issue by xd009642** [hyperium/tonic#144]
Graceful shutdown is recommended for GRPC servers. Upon receiving a SIGTERM stop serving new requests and wait a maximum predetermined amount of time to finish existing requests before closing the program. This would be helpful to document if it's done already or add an example showing how to add it. Even better would be adding a recommended implementation of this that users can enable either in this crate or via another crate.

It does also change the response from a health checking service so should be considered when doing #135

**Comment by LucioFranco** [comment]
This is now supported via #169

**Comment by clarkmcc** [comment]
> and wait a maximum predetermined amount of time to finish existing requests before closing the program

Is it just me, or is tonic killing all requests immediately upon shutdown? If I put a sleep on a unary request and then send a signal that I am capturing and forwarding on to Tonic, the server just dies immediately.
