### ISSUE TITLE
Remove deprecated API

### ISSUE THREAD

**Issue by tottoto** [hyperium/tonic#1455]
### Crates

- `tonic`
- `tonic-build`

### Motivation

Simplifies implementations.

### Proposal

> **Warning**
> This proposal contains API breaking changes.

There are some deprecated APIs in tonic projects. In this proposal, the assumed version is `0.9.2`.

| deprecated api | deprecated at | alternative api |
| --- | --- | --- |
| [`tonic::service::interceptor_fn`](https://docs.rs/tonic/0.9.2/tonic/service/fn.interceptor_fn.html) | `0.5.1` | [`tonic::service::interceptor`](https://docs.rs/tonic/0.9.2/tonic/service/fn.interceptor.html) |
| [`tonic::service::interceptor::InterceptorFn`](https://docs.rs/tonic/0.9.2/tonic/service/interceptor/type.InterceptorFn.html) | `0.5.1` | [`tonic::service::interceptor::InterceptorLayer`](https://docs.rs/tonic/0.9.2/tonic/service/interceptor/struct.InterceptorLayer.html) |
| [`tonic::metadata::MetadataValue::try_from_bytes`](https://docs.rs/tonic/0.9.2/tonic/metadata/struct.MetadataValue.html#method.try_from_bytes)| `0.7.2` | [`TryFrom`](https://docs.rs/tonic/0.9.2/tonic/metadata/struct.MetadataValue.html#impl-TryFrom%3C%26'a+%5Bu8%5D%3E-for-MetadataValue%3CVE%3E) |
| [`tonic::metadata::MetadataValue::from_shared`](https://docs.rs/tonic/0.9.2/tonic/metadata/struct.MetadataValue.html#method.from_shared)| `0.7.2` | [`TryFrom`](https://docs.rs/tonic/0.9.2/tonic/metadata/struct.MetadataValue.html#impl-TryFrom%3C%26'a+%5Bu8%5D%3E-for-MetadataValue%3CVE%3E) |
| [`tonic::metadata::MetadataValue::<Ascii>::from_str`](https://docs.rs/tonic/0.9.2/tonic/metadata/struct.MetadataValue.html#method.from_str)| `0.7.2` | [`TryFrom`](https://docs.rs/tonic/0.9.2/tonic/metadata/struct.MetadataValue.html#method.from_str), [`FromStr`](https://docs.rs/tonic/0.9.2/tonic/metadata/struct.MetadataValue.html#impl-FromStr-for-MetadataValue%3CAscii%3E) |
| [`tonic_build::client::generate`](https://docs.rs/tonic-build/0.9.2/tonic_build/client/fn.generate.html) | `0.8.3` | [`tonic_build::CodeGenBuilder::generate_client`](https://docs.rs/tonic-build/0.9.2/tonic_build/struct.CodeGenBuilder.html#method.generate_client) |
| [`tonic_build::server::generate`](https://docs.rs/tonic-build/0.9.2/tonic_build/server/fn.generate.html) | `0.8.3` | [`tonic_build::CodeGenBuilder::generate_server`](https://docs.rs/tonic-build/0.9.2/tonic_build/struct.CodeGenBuilder.html#method.generate_server) |

The latest deprecation among these APIs is `tonic-build 0.8.3` released on November 29, 2022. Also, since there has been corresponding alternative APIs, I think that there has been sufficient period to migrate them.

### Alternatives

Maintains these APIs until it becomes necessary to remove them for designs or other reasons.

**Comment by LucioFranco** [comment]
Yeah, I think it would be good to remove these API's for the next breaking release.

**Comment by tottoto** [comment]
Thanks for your review. I'll work on this.

**Comment by LucioFranco** [comment]
I think release wise I may go ahead soon and make a point release since I believe what we have on master now is non-breaking (I checked via cargo-semver-checks but I also need to review the code). Once that is done, we can then do a breaking release with these api changes and some other changes include.
