### ISSUE TITLE
Re-export `axum::Router`

### ISSUE THREAD

**Issue by tottoto** [hyperium/tonic#1479]
### Crates

- tonic

### Motivation

Improves usability.

### Proposal

Re-exports `axum::Router`. As `axum::Router` has been exported by `Router::into_router` directly, it might be useful to re-export `axum::Router` for users who want to use the type of the returned value.

### Alternatives

**Comment by LucioFranco** [comment]
I think this is a decent idea though we need to export it in such a way that its not confused with the regular router.

**Comment by tottoto** [comment]
How about as `AxumRouter`?

**Comment by LucioFranco** [comment]
Yeah I think that would be ok
