### ISSUE TITLE
Streaming Methods on Windows - No Response Received

### ISSUE THREAD

**Issue by martin-css** [hyperium/tonic#150]
### Version

Rust (stable) v1.39. The relevant `tonic` crates are:

```
tonic v0.1.0-alpha.6
tonic-build v0.1.0-alpha.6
```

### Platform

Windows 7 (64 bit)

### Description

Are there known issues with the streaming response type when using Tonic in Windows? I appreciate it might be a lower level library like `tokio` that has the issue but it's using tonic that brought it to my attention.

Take a simple proto API example:

```proto
syntax = "proto3";
package api;

message Item {
    string value = 2;
}

message ItemParameters {}

message ItemResponse {
    repeated Item item = 1;
}

service API {
    rpc GetItemsStream(ItemParameters) returns (stream Item);
    rpc GetItemsCall(ItemParameters) returns (ItemResponse);
}
```

Generate a server (as in the [hello world tutorial](https://github.com/hyperium/tonic/blob/master/tonic-examples/helloworld-tutorial.md)). Create a trivial server implementation that returns 5 fixed string values for each method.

On Linux, both these methods work as you would expect when accessed from a client.

However, on Windows, the streaming method (`GetItemsStream`) never returns any data. Logging shows the request being received and the responses being submitted into the channel (up to the buffer total which is 4 in tutorial). However, these are never received by the client.

The unary method (`GetItemsCall`) on Windows works as expected.

**Comment by martin-css** [comment]
Also just tried this on a Windows 10 (64bit) machine just to check it wasn't a Windows 7 only issue - same problem.

**Comment by LucioFranco** [comment]
@martin-css hi! Could you provide the code you are using to generate the stream and consume it? We run the interop tests on windows which ensures that streaming works between tonic client/server pairs and tonic/grpc-go. So this leads me the believe that maybe there is something wrong with how the stream is being yielded?

**Comment by martin-css** [comment]
Sorry @LucioFranco , this is a non-issue. Was looking at making a small reproducible sample and realised I hadn't spawned a new async task to send the responses (i.e. not wrapped in `tokio::spawn`) - was attempting to send & await in the main implementation.

Once I fixed my dodgy code it is all working as expected :+1: 

Just started learning Rust the last couple of days so sure there will be some more silly mistakes in the near future!

**Comment by LucioFranco** [comment]
@martin-css no worries! Glad you figured it out, feel free to pop onto discord if you need anymore help :)
