### ISSUE TITLE
Impossible to do anything about cors.

### ISSUE THREAD

**Issue by ta3pks** [hyperium/tonic#1524]
I came across a couple of discussions and a PR concerning cors however none of the explanations in the docs about cors make any sense and there isnt a single example showing how to use a cors layer. 
Docs state one can customize cors config but for some reason the author has no explanation for how to do that and the example following that statement has nothing to do with cors. Unfortunately, contrary to the belief of the author most of us dont have physic powers. 
![image](https://github.com/hyperium/tonic/assets/9097437/cd1b6aaa-9aa6-4acd-87e6-dce2182e7506)

There's a CorsGrpcWeb struct in the project however that as well has no explanation or a constructor.

Seems adding a third party library -tower- should fix this issue but adding tower cors layer also didnt seem to fix the cors issue. It is obvious i did something wrong there but since the documentation just expects us to know how to do this out of the womb.

Overall I just thought using grpc can improve development speed since the client and server stubs are just auto generated so no need to do double job by writing a rest endpoint for everything and then writing a request for that endpoint on client-side I was sooo wrong. Just wasted hours trying to get cors running for a project that claims to be a grpc framework with web support which seems to be lacking most basic things to get started.

**Comment by seddonm1** [comment]
Hi,
Maybe this would help. This is effectively what [.enable](https://github.com/hyperium/tonic/blob/master/tonic-web/src/lib.rs#L128) does. Get the constants from the top of that file.

```rust
  Server::builder()
       .accept_http1(true)
        .layer(
            CorsLayer::new()
                .allow_origin(AllowOrigin::mirror_request())
                .allow_credentials(true)
                .max_age(DEFAULT_MAX_AGE)
                .expose_headers(
                    DEFAULT_EXPOSED_HEADERS
                        .iter()
                        .cloned()
                        .map(HeaderName::from_static)
                        .collect::<Vec<HeaderName>>(),
                )
                .allow_headers(
                    DEFAULT_ALLOW_HEADERS
                        .iter()
                        .cloned()
                        .map(HeaderName::from_static)
                        .collect::<Vec<HeaderName>>(),
                ),
        )
       .layer(GrpcWebLayer::new())
       .add_service(greeter)
       .serve(addr)
       .await?;
```

**Comment by ta3pks** [comment]
> Hi, Maybe this would help. This is effectively what [.enable](https://github.com/hyperium/tonic/blob/master/tonic-web/src/lib.rs#L128) does. Get the constants from the top of that file.
> 
> ```rust
>   Server::builder()
>        .accept_http1(true)
>         .layer(
>             CorsLayer::new()
>                 .allow_origin(AllowOrigin::mirror_request())
>                 .allow_credentials(true)
>                 .max_age(DEFAULT_MAX_AGE)
>                 .expose_headers(
>                     DEFAULT_EXPOSED_HEADERS
>                         .iter()
>                         .cloned()
>                         .map(HeaderName::from_static)
>                         .collect::<Vec<HeaderName>>(),
>                 )
>                 .allow_headers(
>                     DEFAULT_ALLOW_HEADERS
>                         .iter()
>                         .cloned()
>                         .map(HeaderName::from_static)
>                         .collect::<Vec<HeaderName>>(),
>                 ),
>         )
>        .layer(GrpcWebLayer::new())
>        .add_service(greeter)
>        .serve(addr)
>        .await?;
> ```

Thank you I really appreciate the help. Until grpc echosystem little bit matures tho i think i will stick with rest for now

**Comment by Larkooo** [comment]
> Hi, Maybe this would help. This is effectively what [.enable](https://github.com/hyperium/tonic/blob/master/tonic-web/src/lib.rs#L128) does. Get the constants from the top of that file.
> 
> ```rust
>   Server::builder()
>        .accept_http1(true)
>         .layer(
>             CorsLayer::new()
>                 .allow_origin(AllowOrigin::mirror_request())
>                 .allow_credentials(true)
>                 .max_age(DEFAULT_MAX_AGE)
>                 .expose_headers(
>                     DEFAULT_EXPOSED_HEADERS
>                         .iter()
>                         .cloned()
>                         .map(HeaderName::from_static)
>                         .collect::<Vec<HeaderName>>(),
>                 )
>                 .allow_headers(
>                     DEFAULT_ALLOW_HEADERS
>                         .iter()
>                         .cloned()
>                         .map(HeaderName::from_static)
>                         .collect::<Vec<HeaderName>>(),
>                 ),
>         )
>        .layer(GrpcWebLayer::new())
>        .add_service(greeter)
>        .serve(addr)
>        .await?;
> ```

Setting the cors layer doesn't seem to work. Gives a trait bound error the on .serve()...

**Comment by boan-anbo** [comment]
> > Hi, Maybe this would help. This is effectively what [.enable](https://github.com/hyperium/tonic/blob/master/tonic-web/src/lib.rs#L128) does. Get the constants from the top of that file.
> > ```rust
> >   Server::builder()
> >        .accept_http1(true)
> >         .layer(
> >             CorsLayer::new()
> >                 .allow_origin(AllowOrigin::mirror_request())
> >                 .allow_credentials(true)
> >                 .max_age(DEFAULT_MAX_AGE)
> >                 .expose_headers(
> >                     DEFAULT_EXPOSED_HEADERS
> >                         .iter()
> >                         .cloned()
> >                         .map(HeaderName::from_static)
> >                         .collect::<Vec<HeaderName>>(),
> >                 )
> >                 .allow_headers(
> >                     DEFAULT_ALLOW_HEADERS
> >                         .iter()
> >                         .cloned()
> >                         .map(HeaderName::from_static)
> >                         .collect::<Vec<HeaderName>>(),
> >                 ),
> >         )
> >        .layer(GrpcWebLayer::new())
> >        .add_service(greeter)
> >        .serve(addr)
> >        .await?;
> > ```
> 
> Setting the cors layer doesn't seem to work. Gives a trait bound error the on .serve()...

I have the same issue: see also #1636
