### ISSUE TITLE
Is there a way to handle unhandled requests?

### ISSUE THREAD

**Issue by nicholasbishop** [hyperium/tonic#154]
I have a server that implements a number of services, but I'm not totally confident I've implemented all the services that the clients require. I would like to log an error if an unhandled request is made, something like this:

```rust
Server::builder()
    .add_service(foo)
    .add_service(bar)
    .else(|req| error!("unhandled request: {}", req))
    .serve(addr)
    .await?;
```

I'm guessing that I could do this by implementing my own [Service](https://docs.rs/tower-service/0.3.0-alpha.2/tower_service/trait.Service.html). If that is the right approach, maybe some documentation and/or example code could be added.

By the way, thanks for creating Tonic. I've found it pretty easy to get up and running quickly with it, and the documentation and examples have been very helpful.

**Comment by LucioFranco** [comment]
You should be able to use the https://docs.rs/tonic/0.1.0-alpha.6/tonic/transport/struct.Server.html#method.interceptor_fn to check the type of the outbound response.

**Comment by nicholasbishop** [comment]
Thanks for the pointer. Here's how I have it implemented now:

```rust
Server::builder()
    .interceptor_fn(|svc, req| {
        let uri = req.uri().clone();
        let call = svc.call(req);
        async move {
            let resp = call.await?;
            if let Some(status) = resp.headers().get("grpc-status") {
                let unimplemented = "12";
                if status == unimplemented {
                    error!("unhandled request: {:?}", uri);
                }
            }
            Ok(resp)
        }
    })
```

Thanks for the help :)

**Comment by LucioFranco** [comment]
great! Feel free to reopen this if you have anymore questions :)
