### ISSUE TITLE
GrpcMethod's service and method should have "static" lifetime?

### ISSUE THREAD

**Issue by sneakstarberry** [hyperium/tonic#1547]
### Crates

extensions::GrpcMethod

### Motivation
I'm currently create dynamic client but if create GrpcMethod struct with `&'static str` then there is a memory leak occur. so I want to avoid this happen.

### Proposal
Actually, this is not proposal. it's a question.
In client side generated code, GrpcMethod created with `&'static str`, but is it necessary?
if it's necessary one then, can you explain it for me? and there is a way to avoid this? 
thank you in advance.
```
req.extensions_mut()
    .insert(GrpcMethod::new("helloworld.Greeter", "SayHelloBidiStream"));

----

#[derive(Debug, Clone)]
pub struct GrpcMethod {
    service: &'static str,
    method: &'static str,
}
```

**Comment by tottoto** [comment]
As `GrpcMethod` technically seems not to needed to be static, it might be allowed to have an arbitrary lifetime.
