### ISSUE TITLE
Client streaming will lose message when sending using ReceiverStream

### ISSUE THREAD

**Issue by gaius-qi** [hyperium/tonic#1582]
## Bug Report
```rust
async fn download() {
        let (in_stream_tx, in_stream_rx) = mpsc::channel(128);

        let in_stream = ReceiverStream::new(in_stream_rx);
        let response = client.bidirectional_stream(Request::new(in_stream))
            .await?;

        let mut out_stream = response.into_inner();
        while let Some(message) = out_stream.message().await? {
            match response {
                announce_peer_response::Response::EmptyTaskResponse(response) => {
                    in_stream_tx
                            .send_timeout(1)
                            .await?;
                        return;
                }
                announce_peer_response::Response::NormalTaskResponse(response) => {
                    in_stream_tx
                            .send_timeout(1)
                            .await?;
                        return;
                }
            }
        }
}
```

### Version
`0.9.2`

### Platform
`Darwin Kernel Version 20.2.0`

### Description
Run download function, the information sent by `in_stream_tx.send_timeout()` will be lost because `mpsc::channel` will be dropped in advance.

I can only sleep and wait for the message to be sent successfully, refer to https://github.com/dragonflyoss/client/blob/main/src/task/mod.rs#L417.

**Comment by gaius-qi** [comment]
🤔🤔🤔

**Comment by gaius-qi** [comment]
Refer to https://github.com/hyperium/tonic/issues/601.

**Comment by LucioFranco** [comment]
This is not a tonic bug but a misuse it seems with dropping the channel before it can fully send. This seems normal maybe you want to see if the other end can send an ack that it got the message. There is no way to guarantee that the other end got the message or not in a networked environment without an ack.
