### ISSUE TITLE
Upgrade to `tokio` 0.2

### ISSUE THREAD

**Issue by LucioFranco** [hyperium/tonic#159]
Blockers: 

- [x] `tower-service 0.3`
- [x] `hyper 0.13`
- [x] Update all the smaller tower services

**Comment by joelgallant** [comment]
https://github.com/tower-rs/tower/issues/367
https://github.com/hyperium/hyper/issues/2025

just for anyone who ran into `all possible versions conflict with previously selected packages.` when using tokio '0.2'

**Comment by LucioFranco** [comment]
Hey! Yup, were working on getting hyper out this week, there still needs to be an update to all the tower services we use so I am focusing on that. Once, all those are done tonic can be released as a 0.1.

**Comment by LucioFranco** [comment]
This has been done in #163 and is on master!

**Comment by reyk** [comment]
Hi, are there any plans to release the tokio-0.2-compatible crate soon?

**Comment by LucioFranco** [comment]
Yeah, I have been waiting on some of our dependencies, I am gonna try to get a beta out today/tomorrow.

**Comment by reyk** [comment]
That would be great!
