### ISSUE TITLE
How to strip url path prefix?

### ISSUE THREAD

**Issue by stepan-romankov** [hyperium/tonic#1614]
Imaging that there is a case that we forward api requests from frontend to grpc-web service. Some environments doesn't provide path prefix stripping e.g. Firebase Hosting. Is it possible to configure tonic server to automatically strip url path prefix e.g. "/api" or "/grpc-web" from incoming request, so that service is accessible both on "/api/my.Service/MyMethod" and "/my.Service/MyMethod" endpoints?

**Comment by LucioFranco** [comment]
The way to do this would be to place a tower layer in front of the grpc code that does this, nothing for this is built into tonic.
