### ISSUE TITLE
examples: grpc-web is not working

### ISSUE THREAD

**Issue by enddeadroyal** [hyperium/tonic#1625]
### Version
0.10.2

### Platform
Rocky 8 ,all platform

### Description
the example of grpc-web's client is not working.
there is error after compiled.

code is under
```rust
pub async fn start() -> Result<(), Box<dyn Error>> {
    let client = hyper_util::client::legacy::Builder::new(hyper_util::rt::TokioExecutor::new())
        .http2_only(true)
        .build_http();
    let t = tower::ServiceBuilder::new()
        .layer(tonic_web::GrpcWebClientLayer::default())
        .service(client);
    let mut client =
        InstructServiceClient::with_origin(t, "http://10.167.219.157:10998".try_into()?);
    Ok(())
}
```
![image](https://github.com/hyperium/tonic/assets/11900056/6fbdd926-5de3-4b2e-ae5e-3cf86f436d54)

**Comment by LucioFranco** [comment]
Tonic does not currently support hyper/http 1.0, that is likely why you are seeing those errors.

**Comment by enddeadroyal** [comment]
I use interceptor API to refactor the code to implement my need.
