### ISSUE TITLE
Implement From<> on protobuf:oneof

### ISSUE THREAD

**Issue by gwbres** [hyperium/tonic#1634]
Hello,

It would be great if the code generator would auto implement `From<>` anytime it encounters a `protobuf::oneof`.

I find myself implementing `From<>` all the time to simplify how to use the auto generated code.  

If I understand correctly, anytime we encounter `protobuf::oneof` we get an object of this form:

```rust
pub struct Object {
    #[prost(oneof = "inner::Value", tags = xxx)]
    pub value: ::core:option:Option<inner::Value>,
}
```

So I wind up writing casts like this all the time

```rust 
impl From<inner::Value::X> for Object {
   fn from(value: inner::Value::X) -> Object {
      Object {
           value: Some(v),
      }
   }
} 
```

**Comment by LucioFranco** [comment]
This is an issue better opened in the `prost` repo
