### ISSUE TITLE
Tonic build to generate service traits without server wrappers?

### ISSUE THREAD

**Issue by boan-anbo** [hyperium/tonic#1641]
### Crates

`tonic build`

### Motivation

I want to be able to use a generated Trait from protobuf service

### Proposal

Currently: 

```protobuf
service ReadingService {
    rpc CreateReadingList(CreateReadingListCommand) returns (CreateReadingListResult);
}
```

is generated by tonic build as (with server enabled):

```rust 
#[async_trait]
    pub trait ReadingService: Send + Sync + 'static {
        async fn create_reading_list(
            &self,
            request: tonic::Request<super::CreateReadingListCommand>,
        ) -> std::result::Result<
            tonic::Response<super::CreateReadingListResult>,
            tonic::Status,
        >;
}
```

I wonder if Tonic build could generate an additional plain trait without server requests, response and status such as 

```rust
pub trait ReadingServiceRPCs {
        async fn create_reading_list(
            &self,
            super::CreateReadingListCommand,
        ) -> std::result::Result<
            super::CreateReadingListResult,
            UserDefinedError
        >;
```

This is needed because for a architecture where Tonic server does not handle business logic, the actual library that handles the business logic can implement the same Service trait without server related wrappers such as request, status, and response.

Then, Tonic server can simply pass the inner content of the request to the backend with guaranteed uniformity in parameters and returns.

If needed, I can contribute a PR for such as feature as an option in `tonic_build::configure()`

**Comment by LucioFranco** [comment]
I personally, don't think this is something worth including within tonic because I believe that having access to the request/response types is quite important and converting out of them is pretty easy with the into fns.

**Comment by boan-anbo** [comment]
Understood!

> I personally, don't think this is something worth including within tonic because I believe that having access to the request/response types is quite important and converting out of them is pretty easy with the into fns.
