### ISSUE TITLE
Does not build on nightly due to transitive dependence on ahash

### ISSUE THREAD

**Issue by ysimonson** [hyperium/tonic#1645]
### Version

tonic v0.11.0

### Platform

ubuntu

### Description

Tonic v0.11.0 [will not build on nightly](https://github.com/indradb/indradb/actions/runs/8039345323/job/21956260585?pr=313), due to a transitive dependency on ahash v0.7.8 which relies on `feature(stdsimd)`. This feature was removed in [early Feb nightly builds](https://users.rust-lang.org/t/error-e0635-unknown-feature-stdsimd/106445).

Dependency graph of a project that uses tonic v0.11:

```
$ cargo tree -i ahash          
ahash v0.7.8
└── hashbrown v0.12.3
    ├── indexmap v1.9.3
    │   └── tower v0.4.13
    │       ├── axum v0.6.20
    │       │   └── tonic v0.11.0
    │       │       ├── ...
    │       └── tonic v0.11.0 (*)
    └── internment v0.7.4
        └── ...
```

**Comment by ysimonson** [comment]
It looks like newer versions of ahash fix this issue: https://github.com/tkaitchuck/aHash/issues/200#issuecomment-1928956777

**Comment by tottoto** [comment]
It seems to be caused by `internment` which enables `hashbrown`'s `ahash` feature.

**Comment by ysimonson** [comment]
AIUI those are independent; ie in order to fix my project it would not suffice to remove internment, because tonic also pulls in the bad version of ahash.

**Comment by tottoto** [comment]
As `tonic` does not depend on `ahash` crate, tonic itself does not pull `ahash`.

**Comment by ysimonson** [comment]
Tonic depends on axum, which depends on tower, which depends on indexmap, which depends on hashbrown.

**Comment by tottoto** [comment]
So, do you mean the `hashbrown` pulls `ahash` as `tonic`'s transitive dependency?

**Comment by tottoto** [comment]
> Tonic depends on axum, which depends on tower, which depends on indexmap, which depends on hashbrown.

Yes, up to this point, it is as described in the dependency tree.

**Comment by LucioFranco** [comment]
I would recommend pinning your nightly version if you run into build issues, tonic does not guarantee building on nightly.
