### ISSUE TITLE
Construct a Client that will lazily establish a connection

### ISSUE THREAD

**Issue by bmwill** [hyperium/tonic#167]
## Feature Request

Construct a Client that will lazily establish a connection

### Motivation

Sometimes it would be useful to be able to construct a client and defer establishing a connection with a server until you make a request.

### Proposal

Today when creating a client the connection with the server must be established before a client struct is returned from the `::connect()` function. Perhaps another constructor could be added which lazily connects and defers actually establishing the connection until a request is made.

Its expected (at least to me) that a client already needs to know and understand how to reconnect to a server in the event of a broken connection so this shouldn't be much more difficult than handling that case.

cc: @LucioFranco

**Comment by LucioFranco** [comment]
Sorry, this was closed wrong, the issue for reestablishing connections is fixed but to support lazy connections, the idea I have is to provide a method on `Channel` that is similar to `connect` but `connect_lazy` that will lazily connect.

**Comment by LucioFranco** [comment]
Removing this from `0.1` release, we should support this but I want to think about it some more, but it doesn't seem to be blocking @bmwill anymore.

**Comment by bmwill** [comment]
Yeah this isn't blocking me currently as I'm handling this by having a light wrapper around a tonic client atm.

**Comment by LucioFranco** [comment]
@bmwill got a link to that wrapper by chance?

**Comment by bmwill** [comment]
Yeah sure! Here's one [example](https://github.com/libra/libra/blob/master/mempool/src/proto/mod.rs#L56-L129).

**Comment by joelgallant** [comment]
We did a naive but simple implementation of this, found [here](https://gist.github.com/joelgallant/f0fe9f593728b106daddbf7fa00e10af).
