### ISSUE TITLE
Release 0.12.0

### ISSUE THREAD

**Issue by LecrisUT** [hyperium/tonic#1734]
I hope you don't mind opening this issue, it's just that it would be useful for downstream to have something to track regarding this update since it seems to have rather big refactoring that would not be easy to patch for distro packagers. Feel free to edit this to add any relevant breaking changes:
- [x] https://github.com/hyperium/tonic/pull/1670

**Comment by dynst** [comment]
#1740

**Comment by ne0h** [comment]
I am also waiting for https://github.com/hyperium/tonic/issues/1734. Is there any timeline for `0.12`?

**Comment by LecrisUT** [comment]
Almost perfect timing with the comment: https://github.com/hyperium/tonic/pull/1740#issuecomment-2214198774

**Comment by ne0h** [comment]
> Almost perfect timing with the comment: [#1740 (comment)](https://github.com/hyperium/tonic/pull/1740#issuecomment-2214198774)

Great, thanks for the quick reply!

**Comment by flokli** [comment]
With https://github.com/hyperium/tonic/pull/1740 merged, this can be closed. Thanks!

**Comment by LecrisUT** [comment]
Oh, dunno why it did not get closed automatically, yesterday it was marked as `Closes`, but the top-level comment was edited. I'll close manually
