### ISSUE TITLE
use of undeclared crate or module `tonic_reflection`

### ISSUE THREAD

**Issue by shenghui0779** [hyperium/tonic#1792]
## Bug Report

![image](https://github.com/user-attachments/assets/432e903c-c215-4291-87e4-4184f22f47cc)

### Version

0.12.0

### Platform

MacOS

### Description

use of undeclared crate or module `tonic_reflection`

![image](https://github.com/user-attachments/assets/4466e76d-4d95-4c8a-a9c3-9e7f451734c9)

**Comment by nxy7** [comment]
Probably it's obvious, but how are you sure that you're compiling your app with feature that enables 'tonic_reflection'? After all you've marked it as optional.

**Comment by shenghui0779** [comment]
My problem, just remove the `optional`.
