### ISSUE TITLE
version 0.12.1 causes ClientTlsConfig to explode with invalid CryptoProvider

### ISSUE THREAD

**Issue by tzilist** [hyperium/tonic#1818]
## Bug Report

ClientTls causes a panic in latest tonic client

### Version

```
cargo tree | grep tonic
├── tonic v0.12.1 (*)
├── tonic-health v0.12.1
│   └── tonic v0.12.1 (*)
├── tonic-reflection v0.12.1 (*)
├── tonic-types v0.12.1 (*)
├── tonic-web v0.12.1
│   ├── tonic v0.12.1 (*)
│   ├── tonic v0.12.1 (*)
│   ├── tonic-health v0.12.1 (*)
│   ├── tonic-reflection v0.12.1 (*)

```

### Platform

Darwin arm64

### Description

We recently updated to v0.12 (tried both v0.12.0 and v0.12.1). When I try to run the code like 

```
    let tls_config = ClientTlsConfig::new().domain_name("secretmanager.googleapis.com");

    Channel::from_static("https://secretmanager.googleapis.com")
        .tls_config(tls_config)?
        .connect()
        .await
```

It panics with the following:

```
no process-level CryptoProvider available -- call CryptoProvider::install_default() before this point
```

**Comment by tzilist** [comment]
It turns out this was an issue with `metrics-exporter-prometheus` requiring `aws_lc_rs`

**Comment by PaulOlteanu** [comment]
@tzilist I'm running into this same issue but not using `metrics-exporter-prometheus`. How did you narrow the issue down to that particular dependency?

**Comment by karelispanagiotis** [comment]
I came across the same issue. Do we know how `metrics-exporter-prometheus` interferes ?
