### ISSUE TITLE
Share tonic server port with other http routes

### ISSUE THREAD

**Issue by alexheretic** [hyperium/tonic#1878]
I'd like to serve non-grpc routes alongside tonic grpc same server tcp port. Is there an existing way to do this?

**Comment by alexrudy** [comment]
You can use a `Router` instead of a server, and then convert it to an Axum router - allowing you to server whatever else you'd like with Axum. See [Router::into_router](https://docs.rs/tonic/latest/tonic/transport/server/struct.Router.html#method.into_router)

**Comment by alexheretic** [comment]
Thanks that works, perhaps this could be included in the examples.

**Comment by alexheretic** [comment]
I raised a pr with an example that should be helpful for the next person.

Does anyone know of a good `axum::serve` replacement out there that supports configuration of tcp_nodelay, http2_keepalive etc similar to the tonic server impl?
