### ISSUE TITLE
How to detect stream disconnection on server side

### ISSUE THREAD

**Issue by junky89** [hyperium/tonic#196]
Hi,

I'm not sure that it is the place to ask. So if it is not, excuse my mistake. 

In my application I need to react when a client disconnects from an stream (directional, server to client) and I can't figure out how. I check all the examples and information I could, but without luck. At the moment, what I could achieve is to check if an error was produced when I send a message to this client (throw the mpsc producer). If there is an error then assume the client has been disconnected. This behavior is not ideal at all because I'm detecting a disconnection an undefined time after (when for X reason I need to send a message to this client and this didn't succeed). I'm quite sure that must exist a proper way tot achieve this result and react when the user really disconnects. 

Any help, link, example, point to the right direction... would be awesome.

Thanks

**Comment by LucioFranco** [comment]
Hi! So when a client gets dropped aka disconnects, it will send a GOAWAY. You can check for this on the server side by using the `drop` impl of the stream you return. So when the client disconnects the server side stream's drop will be called. Hopefully this helps!

**Comment by junky89** [comment]
Hi. Thank you very much for the answer. It helped because now I know in wich direction I have to go, but still I don't get the full picture (I just been some month with Rust). What I understood is that I can implement drop for "mpsc::Receiver<Result<XXX, Status>>", is that right? Any change that there is any example somewhere on how to do it?

Sorry for my ignorance, and thank you very much again.

**Comment by LucioFranco** [comment]
So you probably want to write your own `Stream` implementation, for reference you can do,

```rust
pub struct MyStream(mpsc::Receiver<Result<Msg, Status>>);

// In here you just need to forward the `poll_accept` call
// to the inner `Reciever`.
impl Stream for MyStream { ... }

impl Drop for MyStream {
	fn drop(&mut self) {
		println!("Stream dropped! Client disconnected!");
	}
}
```

You can then use something like a `oneshot` channel that triggers on the drop to notify you somewhere else that the client disconnected.

> Sorry for my ignorance, and thank you very much again.

No worries, happy to help :)

**Comment by junky89** [comment]
I understand perfectly now. Tomorrow I will get on to it. That was very helpful, thank you very much.

**Comment by LucioFranco** [comment]
Great! I am gonna close this issue, feel free to reopen it and/or come onto our discord if you have anymore questions!
