### ISSUE TITLE
Release new alpha with tokio 0.2 and hyper 0.13

### ISSUE THREAD

**Issue by oblique** [hyperium/tonic#197]
Can you release new alpha with tokio 0.2 and hyper 0.13?

**Comment by LucioFranco** [comment]
Yup! Working on it, there are a couple of dependency issues that I am resolving. Hopping to have it out soon.

**Comment by oblique** [comment]
Cool thanks!

**Comment by LucioFranco** [comment]
Released! https://crates.io/crates/tonic/0.1.0-beta.1
