### ISSUE TITLE
Update tonic to tower 0.5

### ISSUE THREAD

**Issue by kanpov** [hyperium/tonic#2003]
### Crates

tonic

### Motivation

Currently, an empty tokio + tonic project pulls in both tower 0.5 and tower 0.4, which is undesirable.

### Proposal

Bump to tower 0.5

### Alternatives

**Comment by kanpov** [comment]
Fixed in #2004

**Comment by hatomist** [comment]
+1 on this, bumping tower fixes builds on riscv-musl architecture (or anything that is built with -Zbuild-std) as per this ticket https://github.com/tower-rs/tower/issues/771

**Comment by kanpov** [comment]
> +1 on this, bumping tower fixes builds on riscv-musl architecture (or anything that is built with -Zbuild-std) as per this ticket https://github.com/tower-rs/tower/issues/771

Well as far as understand it, #1892 fixing the issue has been open for a while but doesn't seem to be getting merged any time soon.
