### ISSUE TITLE
UDS example does not build on Windows

### ISSUE THREAD

**Issue by repi** [hyperium/tonic#205]
Find a Windows equivalent of the below or try and disable the example on Windows?

```
error[E0432]: unresolved import `tokio::net::UnixStream`
  --> examples\src/uds/client.rs:10:5
   |
10 | use tokio::net::UnixStream;
   |     ^^^^^^^^^^^^^^^^^^^^^^ no `UnixStream` in `net`

error[E0432]: unresolved import `tokio::net::UnixListener`
 --> examples\src/uds/server.rs:9:5
  |
9 |     net::UnixListener,
  |     ^^^^^------------
  |     |    |
  |     |    help: a similar name exists in the module: `TcpListener`
  |     no `UnixListener` in `net`
```

**Comment by LucioFranco** [comment]
We should just feature gate it, since I do not know of a similar thing for mio and windows. https://docs.rs/mio-uds/0.6.7/src/mio_uds/lib.rs.html#3

**Comment by messense** [comment]
@LucioFranco https://github.com/Azure/mio-uds-windows

**Comment by alce** [comment]
@messense crate looks good, unfortunately it has some outdated deps that overlap with Tonic's and I don't think it'll be worth the hassle, what do you think?

If you all agree I can try to figure out how to hide it from Windows

**Comment by messense** [comment]
I think hiding it from Windows is fine.

**Comment by alce** [comment]
I guess this was resolved on https://github.com/hyperium/tonic/pull/206. 

@LucioFranco  can we close this?

**Comment by LucioFranco** [comment]
Yes! thank you.
