### ISSUE TITLE
Error Display implementation contains source display impl as well

### ISSUE THREAD

**Issue by faern** [hyperium/tonic#213]
## Feature Request

When printing a connection refused error and all its source errors you currently end up with:
```
Error: Client: error trying to connect: tcp connect error: Connection refused (os error 111)
Caused by: error trying to connect: tcp connect error: Connection refused (os error 111)
Caused by: tcp connect error: Connection refused (os error 111)
Caused by: Connection refused (os error 111)
```
That is very redundant and not very nice to read. A good rule is to not include the `Display` implementation of your source error in your error. Or if you do, don't return it from `source()`. Never do both.

I created a forum post on this topic a while back: https://users.rust-lang.org/t/do-people-not-care-about-printable-error-chains-a-k-a-how-to-nicely-implement-display-for-an-error/35362

I see the stack of errors here is not only `tonic` specific, but the problem exists in `hyper` as well.

### Proposal

Change some error type implementations. Especially if there are errors which are basically just combinations of sub-errors, then make them "transparent". Meaning their `Display` impl just proxies to the `Display` of the sub-error and `source()` become something like:
```rust
fn source() -> Option<dyn Error> {
    match self {
        Io(error) => error.source(),
        Something(error) => error.source(),
        ...
    }
}
```

**Comment by LucioFranco** [comment]
@faern hi! I agree the current error situation with the transport errors is a bit funky. I plan on improving them but am lacking some time right now to get there. I think what you're suggesting seems good! If you're open to PRing it I would love that and I'm happy to help out :)

**Comment by faern** [comment]
With the submitted PR, #217, The output of printing the error chain is now reduced to:
```
Error: error trying to connect: tcp connect error: Connection refused (os error 111)
Caused by: tcp connect error: Connection refused (os error 111)
Caused by: Connection refused (os error 111)
```
The remaining problems exist in layers outside of `tonic`. I will have to do something similar to `hyper` later.
