### ISSUE TITLE
Server streaming doesn't work over TLS

### ISSUE THREAD

**Issue by adityapk00** [hyperium/tonic#214]
Version: 0.1.0-beta.1
`tonic = { version = "0.1.0-beta.1", features = ["tls", "tls-roots"] }`

### Platform
Ubuntu 18.04 64-bit

### Description
The server streaming example doesn't work over TLS(https), but the exact same code works over http. 

I create a client like this:
```
async fn get_client(uri: &http::Uri) -> Result<CompactTxStreamerClient<Channel>, Box<dyn std::error::Error>> {
    let channel = if uri.scheme_str() == Some("http") {
        Channel::builder(uri.clone()).connect().await?
    } else {
        let mut config = ClientConfig::new();

        config.alpn_protocols.push(b"h2".to_vec());
        config.root_store.add_server_trust_anchors(&webpki_roots::TLS_SERVER_ROOTS);
        
        let tls = ClientTlsConfig::new().rustls_client_config(config)
            .domain_name(uri.host().unwrap());
        
        Channel::builder(uri.clone())
            .tls_config(tls).connect()
            .await?
    };

    Ok(CompactTxStreamerClient::new(channel))
}
```

Now, when I try a streaming gRPC call with the domain `https://domain.co`, it fails with the following error message:
`Status { code: Internal, message: "failed to decode Protobuf message: invalid tag value: 0" }`

If I remove the TLS from the server and call it with just `http://domain.co`, the streaming call works as expected.

Note that non-streaming gRPC calls work fine on both TLS and non-TLS versions

For reference, here's the code that makes the call:
```
async fn get_streaming_response(uri: &http::Uri) 
    -> Result<(), Box<dyn std::error::Error>>  {
    let mut client = get_client(uri).await?;

    let request = Request::new(EmptyRequest{});

    let mut response = client.get_block_range(request).await?.into_inner();
    while let Some(block) = response.message().await? { // This "?" throws the error
        println!("{:?}", block);
    }

    Ok(())
}
```

**Comment by LucioFranco** [comment]
Hi! Can you provide more information on what the downstream service is, from what I can tell this looks like the response from the downstream is wrong. We also have tests that check for all the gRPC capabilities include TLS + server side streaming so I'm not sure exactly what is triggering this but more information would be helpful :)

**Comment by adityapk00** [comment]
Thanks for your reply! I'll make a small, re-producible example and update this thread.

**Comment by adityapk00** [comment]
So it looks like I was wrong. The problem is not in tonic, but with the NGINX reverse proxy. For some reason, I get the error when NGINX is reverse proxy-ing the gRPC service. If I connect directly to the gRPC server, everything works fine. 

I'm not 100% sure what the underlying problem is, but I've just decided to get rid of NGINX, so ... problem solved, I guess :)
