### ISSUE TITLE
RPC with streaming input and unary output: unexpected internal error encountered

### ISSUE THREAD

**Issue by ChristopherRabotin** [hyperium/tonic#216]
### Version
```
cargo tree | grep tonic
└── tonic v0.1.0-beta.1
└── tonic-build v0.1.0-beta.1
```

### Platform
OpenSuSE Leap 15

```
Linux linux-fgdx 4.12.14-lp151.28.36-default #1 SMP Fri Dec 6 13:50:27 UTC 2019 (8f4a495) x86_64 x86_64 x86_64 GNU/Linux
```

### Description
Endpoint works when using a Rust client. Fails with a Python 3 client using the official grpc libraries: that specific payload cannot be decoded it seems, and I don't know why. What kind of tips can you provide to either fix this, or further debug the encoding/decoding?

I'm currently running the server as:
```
RUST_LOG=debug RUST_BACKTRACE=1 cargo run --bin server
```

#### Server error
```
[2019-12-31T23:57:57Z INFO  server] [traj push states]
[2019-12-31T23:57:57Z DEBUG tonic::codec::decode] decoder inner stream error: Status { code: Unknown, message: "error reading a body from connection: protocol error: unexpected internal error encountered" } 
[2019-12-31T23:57:57Z DEBUG server] got state
[src/traj_srv/srv.rs:567] &traj_state = Err(
    Status {
        code: Unknown,
        message: "error reading a body from connection: protocol error: unexpected internal error encountered",
    },
)
[2019-12-31T23:57:57Z DEBUG hyper::proto::h2::server] send response error: user error: unexpected frame type
[2019-12-31T23:57:57Z DEBUG hyper::proto::h2::server] stream error: http2 error: user error: unexpected frame type

```

#### Relevant Rust server code
```
async fn traj_push_states(
        &self,
        request: Request<tonic::Streaming<TrajState>>,
    ) -> Result<Response<Empty>, Status> {
        info!("[traj push states]");

        let stream = request.into_inner();

        // Pin the inbound stream to the stack so that we can call next on it
        futures::pin_mut!(stream);

        while let Some(traj_state) = stream.next().await {
            debug!("got state");
            dbg!(&traj_state);
            let traj_state = traj_state?;
            debug!("unwrapped");
            let req_traj_id = traj_state.id as i32;
            // Fails _before_ the unwrapped debug message
```

#### Python code
The RPC stubs are generated as per https://grpc.io/docs/quickstart/python/ . All of the endpoints work apart from this one. Every endpoint is either a unary -> unary or a unary -> stream.

The Python implementation follows the same code as the RecordRoute from the `routes` gRPC tutorial.

#### RPC description
```
rpc TrajPushStates(stream TrajState) returns (Empty);
```

Where
```
message TrajState {
    uint32 id = 1; // Trajectory ID
    xb.EphemRegistry.State state = 2;
}
// ...
message State {
    // Absolute epoch
    Epoch epoch = 1;
    // The position may be unset, check the is_zero flag of the Vector.
    Vector position = 2;
    // The velocity may be unset, check the is_zero flag of the Vector.
    Vector velocity = 3;
    /* If the covariance is composed entirely of zeros, it is not informative, and therefore
     * can be assumed to be unset.*/
    Covariance covariance = 4;
    /* The covariance exponent specifies an optional exponent for all of the components of the
    * covariance. This enables storing high precision covariance while not losing precision of
    * floating point values.
    */
    double covariance_exponent = 5;
    // An optional map of parameters associated to this state
    map<string, Parameter> parameters = 6;
  }
```

**Comment by LucioFranco** [comment]
This sounds like the python client is trying to perform a http1 -> http2 upgrade possibly. The error you are getting is that the frame the rust http2 library is getting doesn't correspond with the one its expecting. Can you check how the python library is trying to establish the connection?

**Comment by ChristopherRabotin** [comment]
I'm setting up the connection in a similar fashion as in the example, with "insecure connection." https://github.com/grpc/grpc/blob/master/examples/python/route_guide/route_guide_client.py#L107

**Comment by LucioFranco** [comment]
Interesting, @ChristopherRabotin would you be able to check wireshark on what type of frames its getting. From what I can tell there is a mismatch in the http2 protocol that the python client is sending. so it would be good to see what the rust server is actually getting.

**Comment by ChristopherRabotin** [comment]
Sure thing. I'll give that info in a few hours, I'm on the move right now

Christopher Rabotin.

**Comment by LucioFranco** [comment]
Thanks! I am happy to take a look too but am a bit busy this week, so any more info is super helpful!

**Comment by ChristopherRabotin** [comment]
Sorry for the delay in sending this. Here is the PCAP file: https://send.firefox.com/download/6dea8f666f33b826/#e7h8E5SfT0qLPix8k69cZw . I couldn't upload it directly to Github because it isn't among the accepted file formats. Note that Firefox will delete this file in 7 days.

In this capture, you'll see communication between a client and a server, and a server and a postegres database running locally. The last few packets are the ones which show the bug. Wireshark shows that the packet in dark red, so I assume something is going wrong with the protocol then.

**Comment by LucioFranco** [comment]
@ChristopherRabotin nothing specifically sticks out to me here, is there any way you can create a minimal reproduction so I can inspect it locally, this seems pretty odd.

**Comment by ChristopherRabotin** [comment]
@LucioFranco here is the code for both projects, the server and the client: https://send.firefox.com/download/812099346257d97e/#F73gjgZLstmHBRlaSM-weQ . I've added a short readme in there as a quick start. Let me know if I can help you get started on that.

And thanks very much for the help!

**Comment by alce** [comment]
@ChristopherRabotin `TrajState` id is probably overloading Rust's `std::u32::MAX`

**Comment by ChristopherRabotin** [comment]
The database is started fresh every time, and other tables also use psql's `serial` type. Do you still think that could be an issue?

How would I go about avoid that problem then? I'm happy to try that out.

**Comment by alce** [comment]
try this:

```python
import grpc
import logging
import route_guide_pb2 as pb
import route_guide_pb2_grpc as pb2

RUST_U32_MAX = 4294967295


def push_states():
    with grpc.insecure_channel('localhost:50055') as channel:
        stub = pb2.RouteGuideStub(channel)
        stub.TrajPushStates((pb.TrajState(id=RUST_U32_MAX + x, state=pb.State()) for x in [0, 1]))


if __name__ == '__main__':
    logging.basicConfig()
    push_states()
```

The first TrajState yielded will succeed, the second will raise in the client and panic in the server

**Comment by alce** [comment]
What happens is that proto's `uint32` is a python `int`, which in Python 3 is unbounded and an `u32` in Rust.

 Also, even if the state id does not overload u32, this cast `let req_traj_id = traj_state.id as i32` can still fail.

It is usually not a good idea to use unsigned integer types. JavaScript and maybe others cannot handle them very  well and as you can see, they can overflow.

**Comment by alce** [comment]
Sorry, the second yielded `TrajState` I reference above will not panic, it will return the error you are seeing:

```
[src/server.rs:1] &traj_state = Err(
    Status {
        code: Unknown,
        message: "error reading a body from connection: protocol error: unexpected internal error encountered",
    },
)
```

**Comment by ChristopherRabotin** [comment]
I changed all `uint32` field definitions to be `int32`. Updated the Rust code, and the regenerated the Python code using the grpc tools. I get the same error.

In the Rust server:
```
[2020-01-08T04:47:34Z INFO  server] [traj push states]
[2020-01-08T04:47:34Z DEBUG tonic::codec::decode] decoder inner stream error: Status { code: Unknown, message: "error reading a body from connection: protocol error: unexpected internal error encountered" } 
[2020-01-08T04:47:34Z DEBUG server] got state
[src/traj_srv/srv.rs:567] &traj_state = Err(
    Status {
        code: Unknown,
        message: "error reading a body from connection: protocol error: unexpected internal error encountered",
    },
)
[2020-01-08T04:47:34Z DEBUG hyper::proto::h2::server] send response error: user error: unexpected frame type
[2020-01-08T04:47:34Z DEBUG hyper::proto::h2::server] stream error: http2 error: user error: unexpected frame type
```

In Python (demo.py)
```
_InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNKNOWN
        details = "Exception iterating requests!"
        debug_error_string = "None"
>
```

Here is the diff in the Python generated code:
```
@@ -297,7 +297,7 @@ _TRAJSTATE = _descriptor.Descriptor(
   fields=[
     _descriptor.FieldDescriptor(
       name='id', full_name='thalassa.TrajState.id', index=0,
-      number=1, type=13, cpp_type=3, label=1,
+      number=1, type=5, cpp_type=1, label=1,
       has_default_value=False, default_value=0,
       message_type=None, enum_type=None, containing_type=None,
       is_extension=False, extension_scope=None,
```

And that matches the pb file:
```
 message TrajState {
-    uint32 id = 1; // Trajectory ID
+    int32 id = 1; // Trajectory ID
     xb.EphemRegistry.State state = 2;
 }
```

Any other tip as to what could be the problem?

**Comment by alce** [comment]
_If_ I'm right on on what the issue may be, this change won't help. Could you please re-upload the last sources you posted? They were not available when I tried to download them and I used this incomplete proto definition:

```proto
syntax = "proto3";

package routeguide;

service RouteGuide {
    rpc TrajPushStates(stream TrajState) returns (Empty) {}
}

message TrajState {
    uint32 id = 1;
    State state = 2;
}

message State {
    Epoch epoch = 1;
    Vector position = 2;
    Vector velocity = 3;
    Covariance covariance = 4;
    double covariance_exponent = 5;
    map<string, Parameter> parameters = 6;
}

message Epoch {}
message Vector {}
message Covariance {}
message Parameter {}
message Empty {}
```

I'm still positive this is something in your Python code, not in Tonic though, probably around numeric data types.

I've never used Python's grpc implementation so there is not a lot more I can think of without looking at your code.

Found the source of the integer data type recommendations, please take a look to see if you can make heads or tails  (scroll down to 'Integer Types') https://cloud.google.com/apis/design/design_patterns.

**Comment by alce** [comment]
I think I know what's going on. I thought Tonic (or Prost, rather) was failing to make sense of a somehow malformed or invalid protocol buffer but that's not the case. 

As Lucio points out, the error is being returned  while attempting to read the request's body, not while attempting to decode it. This happens because the python generator crashes when trying to _encode_ a new value while the request is already in flight.

So, this:

```python
stub.TrajPushStates((pb.TrajState(id=RUST_U32_MAX + x, state=pb.State()) for x in [0, 1]))
```
crashes the client because while Python does not care about the size of an `int` protobuf does care about the size of an `uint32` and the upper bound is of course the same.

So, while I can't tell exactly where your code is failing, I'm confident something very similar is going on.

**Comment by ChristopherRabotin** [comment]
Here is the new code: https://send.firefox.com/download/a7b184b62d30ac57/#3jhnMe-rI0Dw26EsSwNbHw . 

So you're saying that the problem might be when the Python client tried to encode and send the next `TrajState` in the stream, is that correct? And if so, any idea how I would go about solving that?

Thanks again for your precious help

**Comment by alce** [comment]
> So you're saying that the problem might be when the Python client tried to encode and send the next `TrajState` in the stream, is that correct? 

Yes, that's what I suspect. At least that's what my code above is doing. If, like you said before, your Python client is closely modeled after the gRPC example (which mine is) and since we are seeing the exact the same error, there is a good chance your code has a similar issue.

> And if so, any idea how I would go about solving that?
I would first try to confirm if this is actually an encoding issue on the Python side by encoding/decoding messages without making any calls to the server.

* You said all other requests succeed, except this one, so try to identify which messages are not being used in the other calls. Maybe the error is in one of those messages.
* Add some error handling to the client calls.
*  Implement a simple server with just the problematic method in another language, is the error still there?
* If all else fails, maybe implement a simple unary method that uses the exact same messages and data as the client streaming method and call it in a loop. Does it fail?

I'll take a look at your code tonight or tomorrow morning to see if something jumps out.

**Comment by alce** [comment]
I ran this script inside aether without changing anything else and it successfully pushes 10 trajectory states all the way to the db:

```python
def make_state(traj_id, force_crash):
    val = lambda: random.uniform(1500, 5000)
    vector = lambda: Vector(x=val(), y=val(), z=val())

    if force_crash:
        val = lambda: '1500.0'

    dt = Epoch(
        ts=TimeSystem.keys().index('TAI'),
        repr=TimeRepr.keys().index('DaysJ1900'),
        value=val())

    xb_state = EphemRegistry.State(epoch=dt, position=vector(), velocity=vector())

    return TrajState(id=traj_id, state=xb_state)


def push_states(traj_id, force_crash=False):
    with grpc.insecure_channel("[::1]:50051") as channel:
        stub = trajectory_service_pb2_grpc.TrajectoryStub(channel)
        try:
            stub.TrajPushStates((make_state(traj_id, force_crash) for _ in range(0, 10)))
        except grpc.RpcError as e:
            print('failed to push states: {}'.format(e))


if __name__ == '__main__':
    logging.basicConfig()
    trajectory_id = 3
    push_states(trajectory_id)
```



If you pass `True` as the second argument to `push_states`, a string is inserted where a number is expected. The client will crash, and you can see the exact same error as before on the client and the server. 

So, it seems that a bad value is sneaking in when you build your values, possibly when loading the csv. Not sure if it's a string instead of a number or a float instead of an int or an overflow or what but that's what's going on.

**Comment by ChristopherRabotin** [comment]
Oooh wow, how interesting. Let me check this out right now, I didn't even
consider this possibility!

Christopher Rabotin.

**Comment by ChristopherRabotin** [comment]
Excellent, many thanks for your help.

The problem I had was indeed in Python, and it was even more stupid than a variable type. Everything was already in floats.

The problem is that the two following sections of code are actually considered different (I don't know why):

Working version:
```
session.traj.TrajPushStates((state for state in states))
```

Buggy version:
```
def my_iterator():
    for state in states:
        yield state

session.traj.TrajPushStates(my_iterator)
```

I expected both to be a generator, but it turns out `my_iterator()` is considered a function despite it have a `yield` statement:
```
<class 'generator'>
<class 'function'>
```
