### ISSUE TITLE
Enable reuse_port(true) in easy way

### ISSUE THREAD

**Issue by michael-a-cliqz** [hyperium/tonic#219]
### Crates

```tonic```

### Motivation

We are trying to build multithreaded server, where each thread is supposed to run following code snippet:
```
    tokio::runtime::Runtime::new().unwrap().block_on(async {
        tonic::transport::Server::builder().add_service(...).serve(address).await;
    });
```
But as long as all our threads share same address, it doesn't work.
Now this could be done by using ```net2::TcpBuilder::reuse_port(true)``` and then passing produced listener to ```Server::builder()::serve_with_incoming()```, just like [uds](https://github.com/hyperium/tonic/blob/82facb628377db15e3e57df0466cf499788480c3/examples/src/uds/server.rs) example does.
Unfortunately, this approach is too tedious for controlling single socket option. It would be nice to have some friendly interface instead.

**Comment by LucioFranco** [comment]
I don't think this is a supported feature in hyper currently, so I think if we want this to be added to `tonic::transport` then I think that would be the right path to go down. Aka we should probably open an issue in hyper about this.

May I ask what is tedious about using the method that is in the `uds` example?

**Comment by michael-a-cliqz** [comment]
> we should probably open an issue in hyper about this.

Fair enough, will do it

> May I ask what is tedious about using the method that is in the '''uds''' example?

If I got it correctly, we need to implement ```AsyncRead```, ```AsyncWrite``` ourselves. Although, what we really want is to customize listener, and not the stream.

**Comment by LucioFranco** [comment]
So you can use tokio's tcp stream type which implements those traits. I would suggest using the tokio tcplistener, and set the options you want. https://docs.rs/tokio/0.2.8/tokio/net/struct.TcpListener.html#method.incoming this should then create a stream of tcpstreams that should align with the incoming types for tonic.

**Comment by michael-a-cliqz** [comment]
> 
> 
> So you can use tokio's tcp stream type which implements those traits. I would suggest using the tokio tcplistener, and set the options you want. https://docs.rs/tokio/0.2.8/tokio/net/struct.TcpListener.html#method.incoming this should then create a stream of tcpstreams that should align with the incoming types for tonic.

Right, thats what I am basically doing. But also what I need to do is to add a new datatype:
```
struct MyStream(tokio::net::TcpStream);

impl Connected for MyStream {}

impl AsyncRead for MyStream {
    fn poll_read(
        mut self: Pin<&mut Self>,
        cx: &mut Context<'_>,
        buf: &mut [u8],
    ) -> Poll<std::io::Result<usize>> {
        Pin::new(&mut self.0).poll_read(cx, buf)
    }
}

impl AsyncWrite for MyStream {
    fn poll_write(
        mut self: Pin<&mut Self>,
        cx: &mut Context<'_>,
        buf: &[u8],
    ) -> Poll<std::io::Result<usize>> {
        Pin::new(&mut self.0).poll_write(cx, buf)
    }

    fn poll_flush(mut self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<std::io::Result<()>> {
        Pin::new(&mut self.0).poll_flush(cx)
    }

    fn poll_shutdown(mut self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<std::io::Result<()>> {
        Pin::new(&mut self.0).poll_shutdown(cx)
    }
}
```
So I am just duplicating code from uds example.
Is there any easier solution?

**Comment by LucioFranco** [comment]
@michael-a-cliqz there is, I forgot to add a impl for `Connected` for `tokoo::net::TcpStream`. I only have it for `hyper::server::conn::AddrStream` :)

I'd accept a PR that does this for `TcpStream` https://github.com/hyperium/tonic/blob/master/tonic/src/transport/server/conn.rs#L24

**Comment by alidehghan** [comment]
could you please provide a gist to use Socket2 and reuse_port?
