### ISSUE TITLE
Compiling protos creates illigal r#Self raw identifier

### ISSUE THREAD

**Issue by jpittis** [hyperium/tonic#225]
### Version

```
0.1.0-beta.1
```

### Platform

```
Linux archlinux 5.4.2-arch1-1 #1 SMP PREEMPT Thu, 05 Dec 2019 12:29:40 +0000 x86_64 GNU/Linux
```

### Description

When compiling with tonic_build, I'm running into the following error:

```
error: `Self` cannot be a raw identifier
```

Which seems to be complaining about the following line in the generated protobufs:

```rust
  #[prost(message, tag="5")]
  r#Self(super::SelfConfigSource),
}
```

I'm gonna do some digging into what this means. I'm also happy to post a reproducible repo if that's preferred, I just wasn't sure if this was a proper bug or if I'm doing something wrong.

**Comment by LucioFranco** [comment]
@jpittis this looks related to the `prost` crate. Looks like you are generating some proto that has the use of the word `Self`?

**Comment by jpittis** [comment]
Yup! Here's the proto file I'm generating from:

https://github.com/envoyproxy/data-plane-api/blob/master/envoy/api/v2/core/config_source.proto#L164

Looks like the field is called self:

```proto
SelfConfigSource self = 5;
```

Any suggestions on how to proceed? Should I cross post this with the `prost` crate?
Gonna look there to see if anyone has had similar issues.

**Comment by jpittis** [comment]
Here's a relevant `prost` issue: https://github.com/danburkert/prost/issues/179

**Comment by jpittis** [comment]
Sees like the fix was added with https://github.com/danburkert/prost/commit/f51cbb2d23fe1c044309f8ab14473b0db61c3ffe which is on master.

**Comment by jpittis** [comment]
Ah I think this is the issue. `prost-build` forces 0.5.0 which does not include the latest `prost` master that includes the fix.

**Comment by jpittis** [comment]
Given `tonic-build` does not have a dependency on the 0.5.0 prost with the bug ([Cargo.toml](https://github.com/hyperium/tonic/blob/master/tonic-build/Cargo.toml#L19)), I don't see much point in keeping this issue open.
