### ISSUE TITLE
Update to `prost` 0.6

### ISSUE THREAD

**Issue by marcelbuesing** [hyperium/tonic#230]
## Feature Request
Replace all dependencies of prost, prost-derive and prost-build to the just released version `0.6`.

### Crates
- interop
- tonic-build
- tonic
- (examples/tests)

### Motivation
- As far as I remember I think this was one of the last issues that tonic 0.1.0 is not yet released ?

### Proposal

Replace all git/master of  dependencies with 

### Alternatives
- None

**Comment by LucioFranco** [comment]
Done in #231, thanks!
