### ISSUE TITLE
Endpoint.connect() with TLS fails with InvalidDNSNameError

### ISSUE THREAD

**Issue by corhere** [hyperium/tonic#239]
### Version

tonic v0.1.0
tonic-build v0.1.0

### Platform

Darwin x86_64

### Crates

webpki v0.21.0

### Description

Creating a channel by calling `connect()` on an `Endpoint` configured with a TLS config fails with the error

        Error(hyper::Error(Connect, InvalidDNSNameError))

unless the `domain_name` option on the `ClientTlsConfig` is set. Contrary to the docs, the `domain_name` option is used (and required) even when the `rustls_client_config` option is set on the config.

The inner `InvalidDNSNameError` comes from the webpki crate, returned at this line: https://github.com/hyperium/tonic/blob/5fc6762435494d8df023bea8e35a5d20d81f2f3b/tonic/src/transport/service/tls.rs#L88

When the `ClientTlsConfig` builds a `TlsConnector`, the entire connection URI string is used as the domain name if the domain name has not been set on the config. https://github.com/hyperium/tonic/blob/5fc6762435494d8df023bea8e35a5d20d81f2f3b/tonic/src/transport/channel/tls.rs#L83-L86

I would expect the `domain_name` option to actually be optional, and for connections to succeed in the common case when the host component of the connection URI matches the domain name for TLS SNI.

**Comment by LucioFranco** [comment]
@corhere thanks for writing this up! If I understand correctly you are suggesting that we use `uri.host()` instead of `uri.to_string()`?

**Comment by corhere** [comment]
@LucioFranco that is correct

**Comment by LucioFranco** [comment]
@corhere I think I got a fix up https://github.com/hyperium/tonic/pull/244 here, would you be able to confirm this works for you? If it does, I can put a release out this week.

**Comment by corhere** [comment]
@LucioFranco that fix works for me. Thank you very much for the quick response!

**Comment by LucioFranco** [comment]
`v0.1.1` is out with this fix.
