### ISSUE TITLE
How to establish serveral calls on one client

### ISSUE THREAD

**Issue by hicqu** [hyperium/tonic#240]
### Motivation
I'm trying to establish more than 1 RPC calls on 1 client:
```rust
fn main() {
    let mut runtime = tokio::runtime::Builder::new()
        .max_threads(1)
        .core_threads(1)
        .thread_name("client-runtime")
        .threaded_scheduler()
        .enable_io()
        .build()
        .unwrap();

    let mut client = runtime
        .block_on(GreeterClient::connect("http://127.0.0.1:44444"))
        .map_err(|e| eprintln!("connect to server fail: {:?}", e))
        .unwrap();

    let request = HelloRequest {
        msg: "test message".into(),
    };

    for _ in 0..10000 {
        let f = client
            .say_hello(Request::new(request.clone()))
            .map_ok(|resp| println!("resp: {:?}", resp.into_inner().msg))
            .map_err(|e| eprintln!("RPC fail: {:?}", e));
        // Can't compile because `client` is already borrowed for `'static`.
        // But, `runtime.block_on(f)` is ok.
        let _ = runtime.spawn(f);
    }

    std::thread::park();
}
```

In my code rust compiler reports that the client is already borrowed. However calling `block_on` instead is ok, but it's not what I want.

### Alternatives
Previously I had a similar question about `tower-grpc`. Thank for @LucioFranco 's help, I can write such code with `tower-grpc`:
```rust
    let executor = runtime.executor();
    client
        .ready()
        .map_err(|e| println!("poll the client fail: {:?}", e))
        .map(move |mut client| {
            let name = "Client".to_owned();
            executor.spawn(
                client
                    .say_hello(Request::new(new_request(name)))
                    .map(|resp| println!("RESPONSE = {:?}", resp))
                    .map_err(|e| panic!("gRPC failed; err={:?}", e)),
            );
            client
        })
```
After the `client` becomes ready again, I can do more RPCs with it.

**Comment by hicqu** [comment]
I found this in `tonic/examples`:
```rust
#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let endpoints = ["http://[::1]:50051", "http://[::1]:50052"]
        .iter()
        .map(|a| Channel::from_static(a));

    let channel = Channel::balance_list(endpoints);

    let mut client = EchoClient::new(channel);

    for _ in 0..12usize {
        let request = tonic::Request::new(EchoRequest {
            message: "hello".into(),
        });

        let response = client.unary_echo(request).await?;

        println!("RESPONSE={:?}", response);
    }

    Ok(())
}
```
But seems in this style a request can only be sent out after the last one is responsed. So all of them are handled one by one, which is still not what I want.

**Comment by nytopop** [comment]
From what I can see, multiplexing is done by [cloning the `Channel`](https://docs.rs/tonic/0.1.0/tonic/transport/struct.Channel.html#multiplexing-requests).  There should also be a `Clone` implementation for generated clients as well. Something like [`futures::stream::Unordered`](https://docs.rs/futures/0.3.1/futures/stream/struct.FuturesUnordered.html) can be used to poll all the request futures simultaneously.

**Comment by LucioFranco** [comment]
So basically to get multiple in flight requests, you can do this:

```rust
#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let endpoints = ["http://[::1]:50051", "http://[::1]:50052"]
        .iter()
        .map(|a| Channel::from_static(a));

    let channel = Channel::balance_list(endpoints);

    let client = EchoClient::new(channel);

    let mut handles = Vec::new();
    for _ in 0..1000 {
        let client = client.clone();
		let j = tokio::spawn(async move {
			let request = tonic::Request::new(EchoRequest {
           		message: "hello".into(),
        	});
        

        	let response = client.unary_echo(request).await?;

        	println!("RESPONSE={:?}", response);
		});
       
        handles.push(j);
    }

    for handle in handles {
        handle.await?
    }

    Ok(())
}
```

This will spawn a new task for each request, cloning the client will basically be the same as cloning a channel. The generated client will always implement clone if the inner transport does https://github.com/hyperium/tonic/blob/master/tonic-build/src/client.rs#L45.

The difference between `tower-grpc` and `tonic` here is that on each request call we need a `&mut self` borrow for the lifetime of the request future. While, tower-grpc just returned a 'static future. There are pros and cons here but this works out the best and having a cheap clone is the solution.

**Comment by LucioFranco** [comment]
It probably makes sense to update this client example with the code above https://github.com/hyperium/tonic/blob/master/examples/src/multiplex/client.rs

**Comment by hicqu** [comment]
Thanks a lot! it resolves my question totally! And, let me update the example above!

**Comment by arssher** [comment]
@LucioFranco Does such cloned client employ HTTP/2 multiplexing, boiling down to single TCP connection (I suppose so), or is it totally separate?
