### ISSUE TITLE
Tonic 0.1.1 produces code which does not compile.

### ISSUE THREAD

**Issue by tkaitchuck** [hyperium/tonic#249]
## Bug Report
When building with tonic 0.1.1 many compile errors of the following from appear:
```
error[E0277]: the trait bound `controller::ServerRequest: prost::message::Message` is not satisfied
##[error]   --> /home/runner/work/pravega-client-rust/pravega-client-rust/target/debug/build/pravega-controller-client-3df4ddb1cd436cfb/out/io.pravega.controller.stream.api.grpc.v1.rs:529:24
    |
529 |             self.inner.unary(request.into_request(), path, codec).await
    |                        ^^^^^ the trait `prost::message::Message` is not implemented for `controller::ServerRequest`
    |
    = note: required because of the requirements on the impl of `tonic::codec::Codec` for `tonic::codec::prost::ProstCodec<controller::ServerRequest, _>`
```
### Version
0.1.1
Noticeably this does not happen with tonic 0.1.0-beta.1

### Platform
Linux workdesktop 4.15.0-72-generic #81-Ubuntu SMP Tue Nov 26 12:20:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

### Crates
An unreleased crate. However the proto that is causing the problem is here:
https://github.com/pravega/pravega/blob/master/shared/controller-api/src/main/proto/Controller.proto

### Description
The code to pull in the proto is:
```
#[allow(non_camel_case_types)]
mod controller {
    tonic::include_proto!("io.pravega.controller.stream.api.grpc.v1");
    // this is the rs file name generated after compiling the proto file, located inside the target folder.
}
```
Running this with tonic 0.1.0-beta.1 there were no issues, with 0.1.1 it does not compile.

**Comment by alce** [comment]
Hi @tkaitchuck, make sure you have the correct version of prost. For tonic 0.1.1 it should be 0.6. Also, if you just upgraded tonic, also upgrade tonic-build and generate your protos again.

**Comment by tkaitchuck** [comment]
This fixed the problem. Feel free to close. 
Should prost be a public dependency?

**Comment by alce** [comment]
Yes. This is because generated structs derive prost::Message, and it needs to be available directly on your project. 

```rust
/// EchoRequest is the request for echo.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EchoRequest {
    #[prost(string, tag = "1")]
    pub message: std::string::String,
} 
```

**Comment by LucioFranco** [comment]
Yup, this is due to prost's macros requiring it at the root level nothing we can really do about this unfortunately.
