### ISSUE TITLE
Server post-startup hook

### ISSUE THREAD

**Issue by znewman01** [hyperium/tonic#252]
### Crates

`tonic`

### Motivation

I want the server to register itself (with e.g. etcd) once the service is serving and healthy.

### Proposal

My gut says: add a method to `Server`.

```rust
tonic::transport::server::Server::builder()
    .startup(async || { /* do some stuff */ })  // here! could take a Future instead of a Fn
    .add_service(...)
    .serve(...)
    .await?;
```

I think we'd need to add something similar to the Hyper server too---the logical place to hook it in on the Tonic side is [here](https://github.com/hyperium/tonic/blob/master/tonic/src/transport/server/mod.rs#L256).

### Alternatives

Please let me know if there's a better way to do this. I've thought about adding a [health check](https://github.com/grpc/grpc/blob/master/doc/health-checking.md) service, `tokio::spawn` the server, and query the service using its corresponding client, which I'm willing to do but is a little overkill for my use case.

**Comment by LucioFranco** [comment]
Hi! My gut feeling is to adapt this https://github.com/hyperium/tonic/blob/master/examples/src/uds/server.rs#L43 example to use TCP and this then would allow you to spawn a task to tell etcd once the tcp socket as been bound.

**Comment by znewman01** [comment]
Thanks for the quick response (and all your work on Tonic; it's been very fun to work with and well-designed)!

That seems like it'll do the it for me; feel free to close unless you think you should document that trick explicitly somewhere.

**Comment by LucioFranco** [comment]
Thanks! Let me know if you have any issues!

I think i'll close this and if any one has any questions they can post in here.
