### ISSUE TITLE
Add a blocking hello_world server example.

### ISSUE THREAD

**Issue by amrx101** [hyperium/tonic#253]
A blocking server example to go along with the client will be helpful.

**Comment by govardhangdg** [comment]
Hello! I'd like to take a shot at this issue. 
I believe the new example can be placed in the file https://github.com/hyperium/tonic/blob/master/examples/helloworld-tutorial.md. I intend to use `futures::executor::block_on`  as executor, so as to make it blocking in nature.
Thanks.

**Comment by LucioFranco** [comment]
@govardhangdg sounds good, you will still need to use the tokio runtime. So for that I would use https://docs.rs/tokio/0.2.13/tokio/runtime/struct.Runtime.html#method.block_on
