### ISSUE TITLE
Support creating multiple modules for services rather than just one

### ISSUE THREAD

**Issue by cthulhua** [hyperium/tonic#259]
## Feature Request
Prost will create a module structure from the package specifier in the .protos, from the prost docs:

> For example, given the package specifier:
>
>`package foo.bar;`
>All Rust types generated from the file will be in the foo::bar module.

Tonic could do the same, or consume an option on the top-level proto to figure out the module.

### Crates

tonic-build

### Motivation

Currently, unless you wrap the `include_proto!` invocation with the appropriate nested modules, the modules don't line up with the prost generated ones:
```
error[E0433]: failed to resolve: there are too many leading `super` keywords
   --> /Users/danny/googleapis/google/cloud/secrets/tsm/target/debug/build/tsm-c643fd8a748aa3b1/out/google.cloud.secrets.v1beta1.rs:561:60
    |
561 |             request: impl tonic::IntoRequest<super::super::super::super::iam::v1::SetIamPolicyRequest>,
    |                                                            ^^^^^ there are too many leading `super` keywords
```

### Proposal

* generate modules from service package specifier

### Alternatives

* consume a `rust_module` option on the grpc .proto and generate code in that module
* have this be configurable in `tonic_build::configure`

**Comment by cthulhua** [comment]
Did some reading; this is a prost-build thing, more than anything. It seems the right way to handle this is to either

a) if it's all within the same crate, provide the module structure around the generated services to match the grpc package structure, or

b) use prost_build::Config::extern_path to instead refer to types in other crates and separate services out that way

Closing this, as it's not a tonic issue.

**Comment by cetanu** [comment]
I notice you made a repo where you tested this and you included code along the lines of:

`tonic_build::configure().extern_path(".uuid", "::uuid")` 

Are you able to explain what this does exactly? I'm new to Rust and I did something similar and it solved this issue for me as well, but I actually have no idea how/why.

For example, what's the significance of the preceding `.` in the proto path, and then the `::` in the rust path?

Please forgive me if this is an extremely noob question! :(

**Comment by cthulhua** [comment]
Both those do similar things; for the proto, the leading dot indicates that it's a fully qualified path. For the rust module, it indicates that the path is an absolute path i.e. not relative to the current module.
The original PR might shed some light on it for you.
GitHub <notifications@github.com> wrote:
“I notice you made a repo where you tested this and you included code along the lines of:

tonic_build::configure().extern_path(".uuid", "::uuid")

Are you able to explain what this does exactly? I'm new to Rust and I did something similar and it solved this issue for me as well, but I actually have no idea how/why.

For example, what's the significance of the preceding . in the proto path, and then the :: in the rust path?

Please forgive me if this is an extremely noob question! :(”

**Comment by LucioFranco** [comment]
Honestly, I don't remember but `::uuid` was the old way of picking up root paths where now you can do `crate` or just call the crate name directly.

**Comment by EdmundsEcho** [comment]
Does this remain the proposed manner by which to avoid generating empty build files?  I ran into this recently; I can't be 100% sure it's not something I'm doing wrong as I new to tonic, but this issue does not seemed to have been resolved by anything other than a work-around.

**Comment by talksik** [comment]
I ran into this as well with the following build script

```
fn build_files_in_directory(directory: &str) -> Result<(), Box<dyn std::error::Error>> {
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());

    for entry in read_dir(directory)? {
        let entry = entry?;
        let path = entry.path();
        if path.is_dir() {
            build_files_in_directory(path.to_str().unwrap())?;
            continue;
        }

        println!("building {}", path.to_str().unwrap());

        // get last part of path
        let file_name = path.file_name().unwrap().to_str().unwrap();
        // take out the .proto extension
        let file_name = &file_name[..file_name.len() - 6];
        let file_descriptor_name = format!("{}_descriptor.bin", file_name);

        configure()
            .build_server(true)
            .build_client(false)
            .file_descriptor_set_path(out_dir.join(file_descriptor_name))
            .compile(&[path.to_str().unwrap()], &[PROTOBUF_DIRECTORY])?;

        println!("successfully built {}", path.to_str().unwrap());
    }

    Ok(())
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let protobuf_directory = "../../protobuf";

    build_files_in_directory(protobuf_directory)?;

    // temporary to debug build
    //panic!("done");

    Ok(())
}

```
It causes same issue. When you have two proto files with same defined package, the second one overthrows the first.
