### ISSUE TITLE
Unclear how to combine Tonic-generated code with an existing Hyper server.

### ISSUE THREAD

**Issue by shepmaster** [hyperium/tonic#266]
Extreme TL;DR: How can I combine Tonic's [hello world](https://github.com/hyperium/tonic/tree/4f343eb980e3c743f4210939e04e0fb73f728d6b/examples/src/helloworld) with Hyper's [hello world](https://github.com/hyperium/hyper/blob/dd02254ae8c6c59432254a546bee6c9e95e16400/examples/hello.rs)?

Slightly longer:

I have an existing Hyper server with some basic endpoints. I'd like to extend this with support for some gRPC endpoints. I've gotten both pieces working independently, but it's unclear how I can combine the Tower `Service` produced by Tonic with what Hyper expects:

```rust
let make_svc = make_service_fn(move |_conn| {
    let state = state.clone();
    async move {
        Ok::<_, http::Error>(service_fn(move |req| {
            let state = state.clone();
            service(req, state)
        }))
    }
});

let server = Server::bind(&bind_addr).serve(make_svc);
```

Let me know what more information or reproducible examples you'd like to see!

**Comment by LucioFranco** [comment]
https://github.com/hyperium/tonic/pull/267 I just added this example, let me know if that helps :)

**Comment by shepmaster** [comment]
That is helpful, but I'm still missing a crucial piece on how to **combine** existing Hyper routes with Tonic. For example, I have this dummy route that always responds with "Hello World" (pretend that it only returns for a specific URL). I'd like to use those routes, and if not found, check the Tonic routes (or vice-versa, I suppose).

```rust
    let make_svc = make_service_fn(move |_conn| {
        // REST API
        // async move {
        //     Ok::<_, http::Error>(service_fn(move |_req| async {
        //         Ok::<_, http::Error>(Response::new(Body::from("Hello World!")))
        //     }))
        // }

        // Tonic
        // async move  {
        //     Ok::<_, http::Error>(DeloreanServer::new(Zabba::default())
        // }
    });

   let server = Server::bind(&bind_addr).serve(make_svc);
```

**Comment by LucioFranco** [comment]
Ok so what you want to do is write a wrapper service that contains both a copy of the hello world service and the tonic one. Then you basically implement an `Either` type of `tower::Service` that on each request will dispatch to either inner service depending on lets say the http version.

https://docs.rs/tower/0.3.1/tower/util/enum.Either.html

Tower currently doesn't provide a router due to it being somewhat complicated with the current type system. Tonic provides a specialized one but may one day get upstreamed.

**Comment by LucioFranco** [comment]
I've updated the example to show this type of usage with warp, let me know if that helps! :)

**Comment by LucioFranco** [comment]
I hope the example helps, going to close this issue, feel free to reopen if you have more questions!
