### ISSUE TITLE
Expose `Router::into_service` 

### ISSUE THREAD

**Issue by LucioFranco** [hyperium/tonic#269]
We should expose something akin to `warp::service` that allows the `Router` type to turn into a `Service` implementation so that it can be combined with more custom implementations.

**Comment by cthulhua** [comment]
Took a look at this; do we kind of want the opposite tack here of `tonic::transport::Server`? ie rather than a 'batteries included' approach, literally just turn a `Router` into a `Service` and let users compose that service however they want?

**Comment by LucioFranco** [comment]
@cthulhua well I think one goal of the transport was to remove the need to worry about services unless you really need to. So I think providing this into_service would allow users that want to do more advanced things with tower use the router infrastructure.

**Comment by cthulhua** [comment]
Ok; I took a crack at this...literally just a RouterService with
```
    #[inline]
    fn call(&mut self, req: Request<Body>) -> Self::Future {
        self.router.routes.call(req)
    }
```

I'll add some tests and open a PR; is there anything more we want here?

**Comment by cthulhua** [comment]
started draft pr:
#272

**Comment by alce** [comment]
Resolved via https://github.com/hyperium/tonic/pull/419
