### ISSUE TITLE
can i Custom load balancing type? just like ，random，hash，Round... and more?

### ISSUE THREAD

**Issue by zhuxiujia** [hyperium/tonic#273]
## Feature Request
can i Custom load balancing type? just like ，random，hash，Round... and more?

**Comment by LucioFranco** [comment]
@zhuxiujia in this case, I would probably suggest looking at `tower-balance` and seeing if that fits your use case. This may be something you want to write manually and I don't think is in the current scope of tonic.

**Comment by LucioFranco** [comment]
Closing this issue as it does not directly relate to tonic.
