### ISSUE TITLE
how to get packet size statistics

### ISSUE THREAD

**Issue by crides** [hyperium/tonic#274]
Hi, I'm using tonic for the programming assignments for one of my classes for message passing between nodes, and the professor wants us to provide statistics (specifically the delay and bandwidth usage) for whatever underlying protocol we're using. I can get the packet delay simply by logging from the nodes, but so far I can't find any method to get the packet sizes. I know tonic probably doesn't handle the packets directly, so I probably can't do this directly inside tonic. Can someone point me to sections of code (inside and outside tonic) that the packets are handled so that I can get the statistics I need? Any other suggestions are also welcome! Thanks!

**Comment by LucioFranco** [comment]
@crides tonic is built ontop of hyper which internally uses tcp to handle the connections. TCP isn't a packet/datagram based protocol. So I am not entirely sure you could capture that information. As for request latency this should be possible by implementing a custom service layer in-between hyper and tonic via tower-service that can measure from beginning to end.

**Comment by crides** [comment]
Sorry, I should've clarified a little bit. Since we're expected to use TCP based protocols, can I get the amount of data sent on TCP?

**Comment by LucioFranco** [comment]
I would say this is not super trivial but one way would be to wrap the TcpStream's AsyncRead/Write impls to see how many bytes were written

**Comment by davidpdrsn** [comment]
I think I'm going to close this. The best solution would probably be to use `Endpoint::connect_with_connector` and build a connector that returns something that wraps a `TcpStream` or some other `AsyncRead + AsyncWrite` and sends statistics to some other system. Could perhaps also be done with a Tower middleware.

Feel free to reopen if you have further questions. You're also welcome to hit us up in [Discord channel](https://discord.gg/tokio).
