### ISSUE TITLE
Generation of server code independent of tonic transport

### ISSUE THREAD

**Issue by mzabaluev** [hyperium/tonic#281]
### Crates

tonic-build

### Motivation

In version 0.1.1, disabling feature `transport` in both tonic and tonic-build results in generated server code that does not compile due to an unconditional dependency on `tonic::codegen::HyperBody`.
Such coupling is not present in the client code, where it is possible to use the generic client with other `Service` impls, not necessarily dependent on `hyper`.

### Proposal

The generated `Service` impl should be generic over the body type, with suitable bounds that are implemented for `hyper::Body`.

**Comment by LucioFranco** [comment]
@mzabaluev yup you are right, master just got some breaking changes, so this will be fixed in `0.2` which should be coming out _soonish_.

**Comment by bnjjj** [comment]
I'm interested for working on this issue for this weekend :) I'll send you a PR to open a discussion

**Comment by LucioFranco** [comment]
Great! I have not fully scoped this issue out, but feel free to chat with us on discord about it :)
