### ISSUE TITLE
tonic_build::compile_protos fail in complex proto folder structure

### ISSUE THREAD

**Issue by wu-sheng** [hyperium/tonic#286]
### Version
0.1.0

### Platform
MacOS 10.15.3 (19D76)

### Description
I am using tonic to build [Apache SkyWalking](http://skywalking.apache.org) rust client, https://github.com/apache/skywalking-rust
Due to that, I need to follow the official proto definition at here https://github.com/apache/skywalking-data-collect-protocol.

And I write `build.rs` like this, but seems the Register.proto can't find the `import common/common.proto`
```
tonic_build::configure()
        .compile(&[
            "proto/common/common.proto",
            "proto/register/Register.proto",
            ...
        ], &["proto"]).unwrap();
```

All these protos and the structure are being used in Java, .net, PHP, Nodejs repos, I am a little confused what is wrong. 

Thank you.

**Comment by LucioFranco** [comment]
This is a prost bug more than it is a tonic bug, I would suggest opening an issue in the prost repo :)
