### ISSUE TITLE
warp example could be better

### ISSUE THREAD

**Issue by xd009642** [hyperium/tonic#289]
The dispatching between warp and tonic could be improved by using the `content-type` header and looking for `application/grpc` for the requests to tonic. I'm not sure if it should replace the check or be combined with it in some way but it seems more correct to use the headers available instead of the http version. 

```Rust
    Server::bind(&addr)
        .serve(make_service_fn(move |_| {
            let mut tonic = tonic.clone();
            let mut warp = warp.clone();
            future::ok::<_, Infallible>(tower::service_fn(
                move |req: hyper::Request<hyper::Body>| match req.version() {
                    Version::HTTP_11 | Version::HTTP_10 => Either::Left(
                        warp.call(req)
                            .map_ok(|res| res.map(EitherBody::Left))
                            .map_err(Error::from),
                    ),
                    Version::HTTP_2 => Either::Right(
                        tonic
                            .call(req)
                            .map_ok(|res| res.map(EitherBody::Right))
                            .map_err(Error::from),
                    ),
                    _ => unimplemented!(),
                },
            ))
        }))
        .await?;
```

**Comment by LucioFranco** [comment]
@xd009642 sure, happy to take PRs for how you might want to see this improved. I do though like showing off how hyper can detect the versions and route things.

**Comment by LucioFranco** [comment]
@xd009642 sure, happy to take PRs for how you might want to see this improved. I do though like showing off how hyper can detect the versions and route things.

**Comment by xd009642** [comment]
So I'm working out this myself for some of my code, if I come up with a way that seems elegant I'll submit a PR :+1:
