### ISSUE TITLE
TLS Indentity in PKCS #12 format

### ISSUE THREAD

**Issue by selmeci** [hyperium/tonic#290]
### Crates

tonic

### Motivation

A PKCS 12 file may be encrypted and signed, which add extra security.

### Proposal

It could be similar to implementation in the reqwest [crate](https://docs.rs/reqwest/0.10.4/reqwest/) which provides a convenient, higher-level HTTP Client with [Identity](
https://docs.rs/reqwest/0.10.4/reqwest/struct.Identity.html) which support pkcs12 format.

**Comment by LucioFranco** [comment]
Unfortunately, it looks like that is only supported under `native-tls` and tonic only uses `rustls`. I would suggest possibly using something like the openssl crate to convert cert types as I don't think rustls supports this and I do not want to bring openssl in tree.
