### ISSUE TITLE
Add ability to set `Status` details

### ISSUE THREAD

**Issue by LucioFranco** [hyperium/tonic#292]
Reference issue https://github.com/tower-rs/tower-grpc/issues/136

**Comment by fluxxu** [comment]
Looks like there is a PR for this in the old repo by @GeorgeHahn:
https://github.com/tower-rs/tower-grpc/pull/191
I can help to transfer it to this repository if needed

**Comment by GeorgeHahn** [comment]
That PR was the bare minimum to get messages into the `Status` details; it could use some API love. This would be great to have though!
