### ISSUE TITLE
Question: Retrieving method name/URL in interceptor

### ISSUE THREAD

**Issue by ddibiase** [hyperium/tonic#300]
I'm wondering if it's possible (or what would be the most appropriate way) to retrieve the method name or URL from the interceptor. The Request struct doesn't seem to contain anything easy. If this isn't currently possible, then perhaps it's appropriate as a feature request.

**Comment by ddibiase** [comment]
Building on the above question, as I'm digging deeper into Interceptors I'm either noticing some missing information or not understanding it correctly. The Interceptor docs state:

`
If you would like to apply middleware like features to the body of the request, going through the tower abstraction is recommended.
`

I'm assuming this is in reference to the Service abstraction: https://docs.rs/tower-service/0.3.0/tower_service/trait.Service.html#middleware--layer although it's not clear where/how/why this needs to be implemented in such a way. This could use further explanation and possibly an example.

Apologies if this is a novice question.

**Comment by LucioFranco** [comment]
I think it may be a valid use case to provide the name of the RPC call on inbound requests for interceptors. Though I am curious how other libraries handle this.

As for the tower abstraction, we use Service as the abstraction between the codec of gRPC/tonic and hyper the http server. So this allows you to place a service middleware in between. If you have a bit more of a clear use case for the service abstraction I can whip up an example (its def not simple).

**Comment by ddibiase** [comment]
Thanks for the quick reply @LucioFranco.

Here's an example of my current implementation that works for validating requests. I'd however like to mutate the metadata with additional user credentials ie. user ID and other info retrieved from the db call. Dgraph is basically my database (imagine this would be Postgres or something similar). Also kindly ignore the hackiness of the example. I'm experimenting.

```rust
// Authentication helper for service
fn generate_auth(graph: Dgraph) -> Interceptor {
    let auth = Interceptor::new(
        move |req: Request<()>| -> Result<Request<()>, Status> {
            let token = req.metadata().get("authorization");
            if token.is_some() == true {
                // Prepare incoming token by cleansing it first
                let tkn = token.unwrap().to_str().unwrap();
                let tkn_str = tkn.replace("Bearer ", "");
                // Prepare query and var hash
                let query = r#"query all($t: string) {
                    q(func: eq(token, $t)) {
                        count(uid)
                    }
                }"#.to_string();
                let mut vars: HashMap<String, String> = HashMap::new();
                vars.insert("$t".to_string(), tkn_str);
                // Query database for record
                let resp = graph
                    .new_readonly_txn()
                    .query_with_vars(query, vars)
                    .expect("query");
                let check: AuthCheck = serde_json::from_slice(&resp.json).expect("parsing");
                // Validate to ensure record exists
                if check.q[0].count == 0 {
                    Err(Status::unauthenticated("Invalid token"))
                } else {
                    Ok(req)
                }
            } else {
                Err(Status::unauthenticated("Missing token"))
            }
        }
    );
    return auth
}
```
Then when setting up the server:
```rust
    let opts: Opts = Opts::parse();
    let addr = format!("{}:{}", opts.host, opts.port).parse()?;
    let server = MyService::new(opts);
    let graph = new_graph(opts);
    let svc = MyServiceServer::with_interceptor(server, generate_auth(graph));
    println!("\n-> Server is online...");
    Server::builder()
        .add_service(svc)
        .serve(addr)
        .await?;
```

**Comment by LucioFranco** [comment]
I would suggest following this example https://github.com/hyperium/tonic/blob/master/examples/src/hyper_warp/server.rs#L58 where you modify the returned service future with a wrapped version with what you have above. You don't need any of the warp stuff but this should enable you to do what you want.

**Comment by ddibiase** [comment]
Ok, I'll give it a shot. Thank you very much!

**Comment by ddibiase** [comment]
I didn't get through the whole implementation but you're certainly right, it's not easy or straightforward. If you do end up working up a complete example, please post it on this issue so I can come back to you later. I'm sure others would be interested in this potentially.

**Comment by LucioFranco** [comment]
```rust
    Server::bind(&addr)
        .serve(make_service_fn(move |_| {
            let mut tonic = tonic.clone();
            let mut warp = warp.clone();
            future::ok::<_, Infallible>(tower::service_fn(
                move |req: hyper::Request<hyper::Body>| match req.version() {
					  let uri = req.uri();
					  // Do something with URI here
                    tonic.call(req)
                },
            ))
        }))
        .await?;
```

If you look at the example above, you can modify it like so. You can then insert something into the regular `http` header and it should come through in each request as metadata. Since, basically our request/metadata are just wrappers for http headermap and request.

**Comment by ddibiase** [comment]
Thanks!

**Comment by odisseylm** [comment]
Answer of [LucioFranco](https://github.com/LucioFranco) is a bit outdated (make_service_fn is removed)

Now the same can be written as
```
fn grpc_req_enrich<Body>(mut req: http::request::Request<Body>)
    -> Result<http::request::Request<Body>, BoxError> {
    let ext_uri = req.extensions().get::<axum::extract::OriginalUri>();
    if ext_uri.is_none() {
        let uri = req.uri().clone();
        req.extensions_mut().insert(axum::extract::OriginalUri(uri));
    }
    // OR another your code with setting headers or extension values which will be copied later by tonic to tonic request
    Ok(req)
}


    Server::builder()
        .layer(FilterLayer::new(grpc_req_enrich))
        //
        // Another code like
        // As example only
        .layer(tonic::service::interceptor(DependenciesSetInterceptor { dependencies: dependencies.clone() }))
        //
        .layer(async_interceptor(grpc_auth_interceptor))
        .add_service(reflection_service) // needed for grpcurl
        .add_service(client_search_serv)
        .add_service(health_check_serv)
        .serve(addr)
        .await ?;

```
