### ISSUE TITLE
Server Reflection

### ISSUE THREAD

**Issue by rokadias** [hyperium/tonic#305]
### Crates

tonic

### Motivation

Desire to use [grpcurl](https://github.com/fullstorydev/grpcurl) or other dynamic client that wants to read the protodefinition from the server instead of having the proto definition locally. This can also help avoid issues of not being sure which version of the protobuf file is associated with a server.

### Proposal

Implement [Server Reflection](https://github.com/grpc/grpc/blob/master/doc/server-reflection.md). I'm aware that prost currently generates the rust types. I wonder if there is a derive macros that can be used to create the appropriate types to server up the reflection entities. See the loose coupling as potentially being an issue: https://github.com/grpc/grpc/blob/master/doc/server-reflection.md#language-specific-implementation-thoughts 
Based on the decoupling work here: https://github.com/hyperium/tonic/issues/98

It would make reading the health check proto easier that is being defined in:
https://github.com/hyperium/tonic/pull/304

### Alternatives

An alternative would be to make it easy/automatic to statically host the proto files from an endpoint on the tonic server.

A side note it would be cool to see the rust/tonic in known implementations:
https://github.com/grpc/grpc/blob/master/doc/server-reflection.md#known-implementations

**Comment by steffengy** [comment]
Duplicate of #165 ?

**Comment by rokadias** [comment]
Yep, it's a duplicate. Closing.
