### ISSUE TITLE
How to use several services using the Tower service approach

### ISSUE THREAD

**Issue by robertohuertasm** [hyperium/tonic#309]
I was using `add_service` to do multiplexing of several services but I needed to implement some sort of middleware in order to validate a token. I went first with the `interceptor` approach but didn't work for me as they don't seem to support `async` and I need to occasionally make a request to a third party server to make a validation.

Then I went for the `warp/tonic/tower` example in order to get access to the `request` and do some async stuff before calling the `service`. But then, a couple of questions arose:

```rust
Server::bind(&addr)
    .serve(make_service_fn(move |_| {
        let mut server = server.clone();
        async {
            let tw_svc = tower::service_fn(move |req: hyper::Request<hyper::Body>| {
                server.call(req)
            });
            Ok::<_, Infallible>(tw_svc)
        }
    }))
    .await?;
```

1. How could I use several services as when I was using `add_service` in such scenario? i.e. if I needed to add `server2` how would I proceed?
2. I'm having issues using `async` inside the closure passed as argument to `tower::service_fn`. If I use it I get compiler errors when I await the result of the call (`async { server.call(req).await }` => captured variable cannot escape `FnMut` closure body). I can overcome this issue by not using async/await and using just futures chain methods (e.g. `and_then`), so it's not a blocker for the moment. Just curious about whether there are other ways to solve this.
3. Is there a recommended way to deal with async middlewares other than this approach?

I suspect this question is not really related to Tonic but to how it relates to Hyper and Tower. I'm starting to get dirty with all these libs so apologies if the question is naive. 😉

**Comment by LucioFranco** [comment]
@robertohuertasm do you need to make a request for the token on each request or can you have some sort of background task that say updates a mutex? If you can go with the later version (which I have seen is more) common you can use the interceptors.

Otherwise, we have an issue https://github.com/hyperium/tonic/issues/269 for exposing a way to instead of serving directly from the router to expose its generated service that you can then call directly in your own hyper implementation.

**Comment by robertohuertasm** [comment]
@LucioFranco this token is the one authorizing the caller to access to the grpc api so it has to be validated prior to accessing the resource. The authorization server is third party server, so I have to make a request there. I guess I could add this logic to each endpoint in the services but I was wondering if there was a simple way to add a middleware wrapping all these calls.

So, according to your answer, should I assume that by using the Tower service approach, for the moment, I should manage the routing to the different services myself? Is that right? At least until #269 story gets merged.

**Comment by LucioFranco** [comment]
I think here then adding it to each handler in the async fn actually might be easier to understand and reason about than writing some complex service stack?

In theory you could just add a `validate_token(&req).await?` to each call. I think that would be prefered here.

If you want to go with the tower method then you will have to do the routing by yourself for now. You can peek in the `transport` module to see how I handle some of that but it is quite complex.

**Comment by robertohuertasm** [comment]
Yes, I took a look at it yesterday to understand how the Router was working. Thanks @LucioFranco for your help and your awesome work! 👍  I think I have enough options for the moment to cover my use case.

**Comment by LucioFranco** [comment]
@robertohuertasm great, feel free to hop on the discord and ping me if you have any further questions!

**Comment by robertohuertasm** [comment]
btw, which discord channel are you in? I was looking for it but couldn't find it. Is it the Rustlang discord or a specific one?

**Comment by LucioFranco** [comment]
@robertohuertasm we have a tokio based one here https://discord.gg/tokio

**Comment by robertohuertasm** [comment]
That's awesome! Thanks again @LucioFranco!
