### ISSUE TITLE
Empty 'google.protobuf.rs' file creation when using well-known types

### ISSUE THREAD

**Issue by evdokimovs** [hyperium/tonic#314]
### Version

`tonic-build v0.1.1`

### Platform

`Linux DellArch 5.5.8-arch1-1 #1 SMP PREEMPT Fri, 06 Mar 2020 00:57:33 +0000 x86_64 GNU/Linux`

### Crates

`tonic-build`

### Description

When Protobuf well-known types used in spec, `tonic-build` generates empty `google.protobuf.rs` file in the output directory.

Fields with well-known types can be normally used. The problem is only in empty file creation.

Repository with reproduction of this bug: [evdokimovs/tonic-build-empty-file].

[evdokimovs/tonic-build-empty-file]: https://github.com/evdokimovs/tonic-build-empty-file

**Comment by LucioFranco** [comment]
This sounds like it may be a `prost` bug, rather than a tonic one?

**Comment by evdokimovs** [comment]
@LucioFranco ,

> This sounds like it may be a prost bug, rather than a tonic one?

Yep, you're right, this is `prost`'s bug. [Here][1] is the issue with this bug. But, as mentioned in the #317 and [danburkert/prost#228][1] issues, [`compile_well_known_types`] usage can fix this.

[1]: https://github.com/danburkert/prost/issues/228
[`compile_well_known_types`]: https://docs.rs/prost-build/0.4.0/prost_build/struct.Config.html#method.compile_well_known_types

**Comment by LucioFranco** [comment]
@evdokimovs https://github.com/hyperium/tonic/pull/318 just merged so this is now supported!

**Comment by evdokimovs** [comment]
@LucioFranco ,

Thank you!
