### ISSUE TITLE
Feature: Genereate protos using a user defined prost_build::Config

### ISSUE THREAD

**Issue by SkamDart** [hyperium/tonic#317]
## Feature Request
Add the ability to compile protos using a user defined prost_build::Config.

### Crates
tonic-build

### Motivation
#314 beat me to opening a similar issue. I have a repro [here](https://github.com/SkamDart/tonic-prost-build-error-example) for failing to compile google protobuf types.

prost provides the ability to [compile_well_known_types](https://docs.rs/prost-build/0.4.0/prost_build/struct.Config.html#method.compile_well_known_types) to generate their [well known types](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf) from the corresponding `.proto` files. However, the tonic-build crate uses the [default constructor](https://github.com/hyperium/tonic/blob/master/tonic-build/src/prost.rs#L92)

### Proposal

Add an additional function, `compile_with_builder` similar to [tonic_build::compile](https://github.com/hyperium/tonic/blob/master/tonic-build/src/prost.rs#L86-L92) that includes a parameter for a user defined `prost_build::Config`.

### Alternatives

If we want to solve a subset of the problem, we could call the `compile_well_known_types` for all builds.

FWIW - I'm probably missing or some reason why you didn't do this originally.

**Comment by rlabrecque** [comment]
Hmm it used to?

https://github.com/hyperium/tonic/pull/49

**Comment by LucioFranco** [comment]
@SkamDart everything seems to compile fine if I include prost-types as a dependency? Is there a specific reason that doesn't work for you?

I do think we can include a way for users to manually use the prost config, I'll open a PR for that.

**Comment by LucioFranco** [comment]
Ok Pr has been merged to support custom prost configs https://github.com/hyperium/tonic/pull/318

**Comment by SkamDart** [comment]
@LucioFranco Incredible. Thank you very much! I was going to happily do the dev work myself but you beat me to it.

**Comment by SkamDart** [comment]
As for why it doesn't compile without that? It's likely that, I'm not including prost-types.

**Comment by LucioFranco** [comment]
@SkamDart yup, if you look at the error it shoudl say its looking for prost-types but its not included in the cargo.toml.
