### ISSUE TITLE
cargo build failed

### ISSUE THREAD

**Issue by Andy320** [hyperium/tonic#322]
### Version
latest code in github master

### Platform

Darwin xxx-mac.local 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64

### Description
On my mac:

1. git clone https://github.com/hyperium/tonic.git
2. cd tonic
3. cargo build

output:
error[E0034]: multiple applicable items in scope
help: disambiguate the method call for candidate #1
    |
418 |                 return tower_service::Service::poll_ready(&mut self.balance, cx);
    |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
help: disambiguate the method call for candidate #2
    |
418 |                 return tower_make::make_service::MakeService::poll_ready(&mut self.balance, cx);
    |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: could not compile `tower-balance`.

**Comment by LucioFranco** [comment]
This is a rustc bug, I would recommend using stable or updating to a newer nightly. If its still an issue on a newer nightly I would open an issue in rustc. Since, this is unrelated to tonic going to close this, feel free to reopen if you have any more questions.
