### ISSUE TITLE
Opinion: how to organize endpoints in a project

### ISSUE THREAD

**Issue by davedbase** [hyperium/tonic#324]
I just completed writing my first API with Tonic and it's pretty great so far! I've reached a point where all my endpoints are in a single main.rs, which can be unruly. I'm now looking for good patterns to organize my endpoints into separate Rust source files. I've separated all my non-endpoint logic but having some trouble deciding and executing a pattern that works well.

I'm having trouble deciding how to compose the Api service from multiple sources. If anyone has an active example or quick suggestive explanation, would be really helpful. Other langs like Go have prescriptive ways and patterns to do this. Just curious if there's an unspoken standard.

My default solution would be simply create modules with endpoint functions and call them from the impl Api block. Wondering mostly if there's a nicer/cleaner way. My endpoints depend on a database connection and access to a config/opts struct currently declared at within my service struct. Individual endpoints access them from `self.db` and `self.config`.

Thanks!

**Comment by LucioFranco** [comment]
I don't think people have fully figured this one out! I like to keep a lot of impl details within my handlers.

Even though this project uses an older version of tonic, its still a good example of how I would write an app with tonic https://github.com/LucioFranco/kv
