### ISSUE TITLE
Fetching peer certs fails

### ISSUE THREAD

**Issue by LucioFranco** [hyperium/tonic#325]

**Comment by gmambro** [comment]
My 2c: while this bug is waiting do be fixed, docs and examples should be updated to reflect this.

**Comment by LucioFranco** [comment]
@gmambro I think that makes sesne but I won't have time right now to get that update out and when I am back from vacation to just implement the fix.

**Comment by gmambro** [comment]
Is there any update or workaround for this issue?

**Comment by max-heller** [comment]
> Is there any update or workaround for this issue?

@gmambro Using version 1.1 works, but is very much not ideal

**Comment by LucioFranco** [comment]
Right, using tonic `0.1` will work. The issue is a deeper problem upstream that we have not gotten to fixing yet. I believe our current priority is to get `tokio 0.3` out then we will focus on hyper/tonic.

**Comment by ian-p-cooke** [comment]
@LucioFranco I saw that `tokio 0.3` is out now... do you know where this issue sits priority-wise?  I'm eagerly awaiting it...

**Comment by LucioFranco** [comment]
High priority, will require changes to hyper so that is what we are working on as we speak.
