### ISSUE TITLE
Difference between dropping server manually and serve_with_shutdown

### ISSUE THREAD

**Issue by faern** [hyperium/tonic#330]
### Motivation

The method `tonic::transport::server::Router::serve_with_shutdown` (and `serve_with_incoming_shutdown`) allows aborting a tonic server with the help of anything implementing `Future<Output = ()>`. However, there is a primitive in the `futures` crate that allows you to wrap and abort any future at will: `futures::future::Abortable`. Another way of making a future abortable is something like:
```rust
tokio::select! {
    _ = tonic_router.serve() => { eprintln!("Server error"); }
    _ = some_channel_receiver => { println!("Server aborted by signal"); }
}
```

Is one way preferred over the others for a good reason? Would tonic not be able to clean up properly if a `tonic_router.serve()` future is just dropped?

### Proposal

If there is a technical reason one way of aborting a server is better than any other, then it would be nice if the docs for `serve_with_shutdown` and `serve_with_incoming_shutdown` mentioned that, so users don't shut down servers in bad ways.

If all ways of aborting a server future are equivalent, it might still be nice if the documentation said that just dropping the normal `serve()` future is also a correct way of stopping the tonic server. The existence of dedicated serve futures allowing clean shutdown makes me wonder if the normal one won't cut it or be problematic.

**Comment by LucioFranco** [comment]
So basically, dropping the server will forcefully cancel all connections and not perform a proper drain/shutdown. This is because it basically just deallocates the future. Abortable does this when you cancel since it can only drop the future, it can't tell it to start shutting down. While using the special shutdown methods on the server will allow hyper to gracefully drain all connections and gracefully close the H2 connection. So in general its preferred to go with the shutdown method rather than abortable.

**Comment by faern** [comment]
Thanks for the reply!

I thought most async sockets do properly close themselves when dropped thanks to their `Drop` implementation. But I guess proper/gracefully in this case maybe involves sending some good bye message to the peer? Or what's the reason it can't clean up during drop? I know `Drop` does not support async dropping yet, but this has been discussed. Would it be possible to make `tonic` clean up properly by dropping after async dropping is implemented in the language?

**Comment by LucioFranco** [comment]
Possibly! But async drop just like regular drop is still optional so there is a chance it doesn't get called. What we generally prefer for async tasks that can gracefully shutdown is to pass in a handle and let them exit gracefully instead of forcing it to end on drop.

**Comment by faern** [comment]
Good to know. I just now released [`triggered`](https://crates.io/crates/triggered) to get some primitives that were easy to use with `serve_with_shutdown`.

**Comment by LucioFranco** [comment]
Cool! Looks like we can close this issue then, feel free to reopen if you have questions :)
