### ISSUE TITLE
Panic when returning Status with arbitrary Bytes in details

### ISSUE THREAD

**Issue by dvshur** [hyperium/tonic#342]
### Version
0.2.0

### Platform
Mac OS Catalina

### Description
I was trying to return a Status with details from an unary RPC call looking like this
```
Err(Status::with_details(
  Code::ResourceExhausted,
  "Too many requests",
  Bytes::from_static(b"hello"),
))
```
It panicked with an error:
```
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Status { code: Internal, message: "Couldn\'t serialize non-text grpc status header" }', /Users/<usr>/.cargo/registry/src/github.com-1ecc6299db9ec823/tonic-0.2.0/src/server/grpc.rs:225:9
```

Upon discussing with @LucioFranco in Discord:
- This is probably due to [this validation](https://docs.rs/http/0.2.1/src/http/header/value.rs.html#559)
- Since the bytes are going to a `*-bin` header, they should probably be base64-serialized according to [spec](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md).

**Comment by LucioFranco** [comment]
The test in https://github.com/hyperium/tonic/pull/345 should reproduce but it seems to pass

**Comment by dvshur** [comment]
`Bytes::from_static(&[1])` reproduce the bug.
