### ISSUE TITLE
Why doc(hidden) on impl Service?

### ISSUE THREAD

**Issue by l4l** [hyperium/tonic#344]
It seems that service is generated with `doc(hidden)` attribute (introduced in https://github.com/hyperium/tonic/commit/cd9133a41cc6bedf23f64eb44b2b2f9bf93925e4):

https://github.com/hyperium/tonic/blob/68d2ab3339f1cc8bf4cf90c6c9fb37dbae251425/tonic-build/src/server.rs#L34-L37

This type is intended for direct using, e.g. in helloworld:

https://github.com/hyperium/tonic/blob/68d2ab3339f1cc8bf4cf90c6c9fb37dbae251425/examples/src/helloworld/server.rs#L36

It seems that @carllerche also had this question: https://github.com/hyperium/tonic/issues/1#issuecomment-533300029, but it left without answer.

**Comment by LucioFranco** [comment]
Uh good question, we should probably remove that :) I'd totally accept a PR for this I have limited time atm.
