### ISSUE TITLE
lttp typo?

### ISSUE THREAD

**Issue by rambattu** [hyperium/tonic#350]
Is this supposed to be http here instead of lttp? Or was it intention so the resolution of this URI fails and then it switches to UDS path?

https://github.com/hyperium/tonic/blob/372da52e96114ca76cc221f3c598be82bfae970c/examples/src/uds/client.rs#L20

Either way the example works fine as it ignores the string that is used for URI here.

**Comment by LucioFranco** [comment]
Yeah, that is a typo haha

**Comment by dfreese** [comment]
To be honest, I thought that was intentional to make it clear that it was invalid.
