### ISSUE TITLE
Get the server's port/local_addr

### ISSUE THREAD

**Issue by mariogemoll** [hyperium/tonic#351]
### Crates

`tonic`

### Motivation

For testing purposes it would be good if there was a way to retrieve the port a server is listening on when it was started without a specified port (ie. with port 0).

### Proposal

Add functionality to obtain the port/local_addr a server is listening on (similar to https://docs.rs/hyper/0.13.5/hyper/server/struct.Server.html#method.local_addr).

**Comment by gabrielrussoc** [comment]
This is also very useful when there are multiple servers on the same host, where it is usual to let the OS find a free port by specifying `:0`.

**Comment by mariogemoll** [comment]
Great, that worked, thanks!

**Comment by gabrielrussoc** [comment]
Can we reopen this? Although there is a workaround, it would be great to support this out of the box.

**Comment by davidpdrsn** [comment]
I don't quite see how to add a more convenient way could be added. Once the server (`Router`) has been bound to an address or an "incoming" it is no longer accessible. All the methods that do this consume `self`.

Hyper's server gets around that by making the server itself a `Future` whereas tonic users `async fn`s.

I'm personally fine with requiring users to create the `TcpListener` to get the address and passing it in with `server_with_incoming`.

**Comment by LucioFranco** [comment]
Yeah, I don't think its worth making things more complicated to support this feature. Going to close for now.

**Comment by Raphiiko** [comment]
Would it be possible to reopen this issue? I have a situation where I find a free port by setting `:0` as the port, and I'm looking to find the port it picked.

The workaround in https://github.com/hyperium/tonic/issues/351#issuecomment-638346513 no longer seems to be an option, as `incoming` is no longer available on `tokio::net::TcpListener` in recent versions of tokio.
