### ISSUE TITLE
helloworld-tutorial is brocken

### ISSUE THREAD

**Issue by TeFiLeDo** [hyperium/tonic#360]
### Version
v0.2.1

### Platform
`uname -a`:
```
Linux hostname 5.6.14-arch1-1 #1 SMP PREEMPT Wed, 20 May 2020 20:43:19 +0000 x86_64 GNU/Linux
```

### Description

I tried to follow the [helloworld-tutorial](https://github.com/hyperium/tonic/blob/master/examples/helloworld-tutorial.md) in order to get a grasp of tonic. But when it was time to compile for the first time (after adding the code for the server), I got these errors:
```
   Compiling helloworld-tonic v0.1.0 (/tmp/helloworld-tonic)
error: environment variable `OUT_DIR` not defined
 --> src/bin/server.rs:7:5
  |
7 |     tonic::include_proto!("helloworld");
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0432]: unresolved import `hello_world::greeter_server`
 --> src/bin/server.rs:3:18
  |
3 | use hello_world::greeter_server::{Greeter, GreeterServer};
  |                  ^^^^^^^^^^^^^^ could not find `greeter_server` in `hello_world`

error[E0432]: unresolved imports `hello_world::HelloReply`, `hello_world::HelloRequest`
 --> src/bin/server.rs:4:19
  |
4 | use hello_world::{HelloReply, HelloRequest};
  |                   ^^^^^^^^^^  ^^^^^^^^^^^^ no `HelloRequest` in `hello_world`
  |                   |
  |                   no `HelloReply` in `hello_world`

error[E0422]: cannot find struct, variant or union type `HelloReply` in module `hello_world`
  --> src/bin/server.rs:21:34
   |
21 |         let reply = hello_world::HelloReply {
   |                                  ^^^^^^^^^^ not found in `hello_world`

error: aborting due to 4 previous errors

Some errors have detailed explanations: E0422, E0432.
For more information about an error, try `rustc --explain E0422`.
error: could not compile `helloworld-tonic`.

To learn more, run the command again with --verbose.
```

I know that the code is exactly the same as in the tutorial because I tried again copying the code and got the same results.

The only difference is that instead of defining binaries in the `Cargo.toml` file, I used the `/src/bin`. Since all files inside that directory get compiled to binaries, this should not be the cause of this behaviour.

Since this is the helloworld-tutorial, you can probably guess that I have absolutely no idea what causes these errors or how to fix it.

**Comment by LucioFranco** [comment]
If you follow the tutorial without moving the binaries to `/src/bin` does it work? Also what does your `build.rs` look like?

**Comment by LucioFranco** [comment]
No update, so closing this issue, if you have anymore questions feel free to re-open!

**Comment by maudieey** [comment]
I encountered the same issue. In my case, the problem was that the `build.rs` file in the project's root directory didn't download successfully. After adding the missing `build.rs` file, the compilation process worked fine.
