### ISSUE TITLE
include_proto! doesn't work with out_dir

### ISSUE THREAD

**Issue by rlabrecque** [hyperium/tonic#37]
### Version

master: afa9d9d236b7ca96d70d696ab38aadac7cdf41ff

### Platform

Linux RILEY-LT 4.19.43-microsoft-standard #1 SMP Mon May 20 19:35:22 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

### Crates

cargo-build

### Description

Because include_proto uses OUT_DIR it doesn't know where to find the files when using `tonic_build::configure().out_dir("src/proto")`

https://github.com/hyperium/tonic/blob/c1db64244ea3af06df6305638b88d9a87e11e68e/tonic/src/macros.rs#L11

**Comment by LucioFranco** [comment]
@rlabrecque should be possible to include it normally via 

`include!("src/proto/{pacakge}.rs")`

We probably want to document this better.

**Comment by LucioFranco** [comment]
I think now that #40 has been merged we can close this!
