### ISSUE TITLE
allow get uri from transport::Endpoint

### ISSUE THREAD

**Issue by Sherlock-Holo** [hyperium/tonic#370]
### Crates

tonic

### Motivation

I am using `tonic` and stored the `Endpoint`, ensure I can reconnect GRPC server directly, however sometimes I need to get the uri in `Endpoint` to print some log.

### Proposal

add a new method `get_uri(&self) -> &Uri` for `Endpoint`, choose `&Uri` not `Uri` because it can reduce clone if the user doesn't want the ownership.

an implement is 
```rust
fn get_uri(&self) -> &Uri {
    &self.uri
}
```

### Alternatives

I have tried to create wrapper type `Endpoint(Uri, Endpoint)` to store the uri, but it needs a clone of the uri, adding the new method can reduce uselessly memory allocate

**Comment by LucioFranco** [comment]
I believe the debug/display implementation should show the uri but it should be possible to expose that. I'd accept a PR for this :)

**Comment by Sherlock-Holo** [comment]
`Endpoint` only implementd `Debug` but it doesn't show the uri, I will try to create a PR to add this feature :)
