### ISSUE TITLE
Remove `Code::__NonExhaustive` variant

### ISSUE THREAD

**Issue by LucioFranco** [hyperium/tonic#384]
cc @seanmonstar, looks like there are no more status codes being added, I think we can do this?

**Comment by LucioFranco** [comment]
One issue with this will be when decoding a status code that doesn't exist. In this case we most likely want to error out. We want to consider this case and probably don't want to funnel it into the same error case as getting a correct status back from another remote peer.

**Comment by seanmonstar** [comment]
There's a guarantee that no new codes would be added? I'm suspicious of that, unless adding a new code would blow up too many implementations. An alternative is to change to `non_exhaustive`.

**Comment by LucioFranco** [comment]
I don't think they will change, there is basically zero movement right now with the spec. Though if it does change I also don't think there is any problem in creating a breaking change for tonic.

I think the idea is that if we don't use `non_exhaustive`  we will be forcing the user to statically handle the case when a new code is added. I don't think that is that bad of a consequence. Not sure though.

**Comment by davidpdrsn** [comment]
I agree with @LucioFranco. I've made a PR that removes it https://github.com/hyperium/tonic/pull/625.
