### ISSUE TITLE
Enable mapping `h2` errors to correct `Status` codes.

### ISSUE THREAD

**Issue by LucioFranco** [hyperium/tonic#394]
We currently have this code https://github.com/hyperium/tonic/blob/master/tonic/src/status.rs#L344 which maps `h2::Error` into proper `Code`'s. We should test and ensure that if the user enables the `transport` feature we can downcast the errors into `h2` variants and mapping them to correct status codes.

**Comment by SkamDart** [comment]
Happy to take this over but after reading through the code, it looks as if maybe this has already been done with this [feature](https://github.com/hyperium/tonic/blob/master/tonic/src/status.rs#L329-L334) and [test](https://github.com/hyperium/tonic/blob/master/tonic/src/status.rs#L775-L791)?

Unless I'm misunderstanding this and you were looking to feature gate something like, `pub enum Http2Error` based on [this spec](https://github.com/grpc/grpc/blob/3977c30/doc/PROTOCOL-HTTP2.md#errors) under transport?

**Comment by LucioFranco** [comment]
Last I remembered I don't think its hooked up would be good to test. We don't need to add a http2error we just need to ensure when we get an h2 error its translated into the correct status code.

**Comment by davidpdrsn** [comment]
Is this related to https://github.com/hyperium/tonic/pull/612?

**Comment by davidpdrsn** [comment]
It isn't. But it was fixed in https://github.com/hyperium/tonic/pull/509
