### ISSUE TITLE
Please add the example with CPU-intensive or blocking operations

### ISSUE THREAD

**Issue by igor-petruk** [hyperium/tonic#404]
### Crates

`tonic`

### Motivation

It would be nice to know if there is anything special needs to be done to run CPU instensive/blocking tasks in Tonic service.

### Proposal

Please add a simple hello_world or echo example where server is correctly performing plain blocking operation, for example blocking sleep or blocking file read. For example it would also nice to see how to control the size of the underlying thread pool and how to combine purely async and CPU-intensive tasks in one service if possible.

There are examples like `helloworld/server_blocking.rs`, but it is not quite clear what are they demonstrating, they use different runtime. Is it the runtime for CPU intensive tasks?

Would simple code like this do the job:

```
let reply = tokio::task::spawn_blocking(move || {
    ...
}).await;
```

Any details that are worth noting?

### Alternatives

If existing examples do already demonstrate that, we can make comments/readme more explicits explaining it.

*P.S. Great job with the project, thanks!*

**Comment by LucioFranco** [comment]
Thanks for the kind words! And, tokio will soon have more docs for this (and I would totally accept a PR with an example) type of workload. In general, I would suggest using `tokio::task::spawn_blocking` since that will provide better consistent latency.

**Comment by LucioFranco** [comment]
Here are some docs on how to use blocking https://docs.rs/tokio/0.2.22/tokio/task/index.html#blocking-and-yielding nothing here is specific to tonic, so I don't know if it makes sense to include an example for it. Going to close this issue, feel free to re-open if you have more questions.
