### ISSUE TITLE
proto3 fields should be optional (Option<T>)

### ISSUE THREAD

**Issue by Rulliam** [hyperium/tonic#407]
### Version

tonic 0.3.0

### Platform

Linux Ubuntu 18

### Description

I have a .proto with

```proto
syntax = "proto3";

message Packet {
    bytes data = 1;
}

message PacketWrapper {
    Packet packet = 1;
    int64 packet_id = 2;
}
```

After the build process, tonic_build will generate
```rust
pub struct PacketWrapper {
    pub packet: Option<Packet>,
    pub packet_id: i64,
}
```

But according to proto3 specs, all fields should be "optional" by default, so why don't we have an `Option<i64>` here ?

**Comment by Rulliam** [comment]
Well, I just saw that you were using Prost https://github.com/danburkert/prost#field-modifiers , I will look at that

**Comment by LucioFranco** [comment]
These fields can use the `Default` trait I believe.
