### ISSUE TITLE
Update logo

### ISSUE THREAD

**Issue by LucioFranco** [hyperium/tonic#408]
We have a fancy logo from the new tokio website, we should go through the code base and update it in every spot we use the old one.

https://github.com/tokio-rs/website/blob/master/public/img/icons/tonic.svg

**Comment by freiguy1** [comment]
Out of curiosity, if I were to work on this issue and create a PR, could the PR get tagged with `hacktoberfest-accepted` so it can count toward my four? :)

**Comment by alce** [comment]
If the PR gets actually accepted I don't see why not.
