### ISSUE TITLE
HealthService isn't public

### ISSUE THREAD

**Issue by xd009642** [hyperium/tonic#409]
## Feature Request

As discussed on discord I'm attempting to route between two grpc services (one being the health service) and a http service. However, I've found I can't use the `HealthService` directly because it's not public https://github.com/hyperium/tonic/blob/master/tonic-health/src/server.rs#L108 

### Crates

tonic-health

**Comment by xd009642** [comment]
Just making the struct pub isn't enough you'd also have to rework a bit of the API. I've done this locally and if it ends up being desired as a feature I can start a PR - I've not pushed anything yet because it's not currently working

**Comment by xd009642** [comment]
This may be unnecessary, if #410 is solved this will be solved via that or this is unnecessary

**Comment by alce** [comment]
Resolved via https://github.com/hyperium/tonic/pull/419.
