### ISSUE TITLE
Allow for easier routing between http server and multiple grpc servers 

### ISSUE THREAD

**Issue by xd009642** [hyperium/tonic#410]
I have two gRPC services in my server, my main server and the health check. I'm also adding a HTTP endpoint via warp. So I tried to do this and found things didn't quite work. Assuming I'm not doing anything egregiously wrong, there might be some changes to tonic-health and #272 or an equivalent may be required.

I've created an example repository here: https://github.com/xd009642/tonic-route-warp-example 

In the mean time I'll start hosting two servers listening at different ports but it would be nice if this would work :smile:

**Comment by LucioFranco** [comment]
Yeah, that PR is related we just need to find a way to return an easy to use service from the router.

**Comment by xd009642** [comment]
is there anything stopping #272 being merged? I saw there was one comment adding something but otherwise (at least to my untrained) eyes it looked pretty solid

**Comment by LucioFranco** [comment]
@xd009642 we just need to address https://github.com/hyperium/tonic/pull/272#issuecomment-612143535

**Comment by alce** [comment]
I believe this was resolved on https://github.com/hyperium/tonic/pull/419. Please re-open if there are further questions.
