### ISSUE TITLE
tonic-build cannot generate code for service with `connect` rpc method

### ISSUE THREAD

**Issue by Horusiath** [hyperium/tonic#412]
## Bug Report

When generating code from proto files, a generated client code will contain a `connect` function. This may result in name clash i.e. when the proto file itself has defined such rpc method name, like:

```proto
service NodeService {
    rpc Connect(Request) returns (stream Response) {}
}
```

Example error message:

```
error[E0592]: duplicate definitions with name `connect`
  --> <path-to-generated-proto-file>.rs:31:9
   |
31 | /         pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
32 | |         where
33 | |             D: std::convert::TryInto<tonic::transport::Endpoint>,
34 | |             D::Error: Into<StdError>,
...  |
37 | |             Ok(Self::new(conn))
38 | |         }
   | |_________^ duplicate definitions for `connect`
...
```

Technically, there are no limitations in terms of name restrictions for gRPC method names. While this is not a serious issue for someone who's in control of proto file definitions, it may become one once we're about to generate a client to an existing gRPC service, that's outside our control.

### Version

```
[build-dependencies]
└── tonic-build v0.3.0
    ├── proc-macro2 v1.0.19 (*)
    ├── prost-build v0.6.1
    │   ├── bytes v0.5.6
    │   ├── heck v0.3.1
    │   │   └── unicode-segmentation v1.6.0
    │   ├── itertools v0.8.2 (*)
    │   ├── log v0.4.11 (*)
    │   ├── multimap v0.8.1
    │   ├── petgraph v0.5.1
    │   │   ├── fixedbitset v0.2.0
    │   │   └── indexmap v1.5.0 (*)
    │   ├── prost v0.6.1 (*)
    │   ├── prost-types v0.6.1
    │   │   ├── bytes v0.5.6
    │   │   └── prost v0.6.1 (*)
    │   └── tempfile v3.1.0
    │       ├── cfg-if v0.1.10
    │       ├── rand v0.7.3 (*)
    │       ├── remove_dir_all v0.5.3
    │       │   └── winapi v0.3.9
    │       └── winapi v0.3.9
    │   [build-dependencies]
    │   └── which v3.1.1
    │       └── libc v0.2.73
    ├── quote v1.0.7 (*)
    └── syn v1.0.35 (*)
```

### Platform

Windows (64 bit).

**Comment by LucioFranco** [comment]
@Horusiath `tonic-build` has some features flags you can disable to have it not generate the connect method. https://github.com/hyperium/tonic/blob/master/tonic-build/Cargo.toml#L25

You likely want to keep all of them except the `transport` one which enables the `Client::connect` method to be generated. Hopefully this helps!

**Comment by zhongTao99** [comment]
> Could you please come back to this issue?
> 
> For me if I specify the dependency like this:
> 
> ```
> tonic-build = { version = "0.11.0", features = [] }
> ```
> 
> the error still persists.
> 
> Moreover, is the flag useful? How would I create a GRPC client if I don't have the `connect` method?..

I also encountered this problem, how did you solve it?

**Comment by zhongTao99** [comment]
> > > Could you please come back to this issue?
> > > For me if I specify the dependency like this:
> > > ```
> > > tonic-build = { version = "0.11.0", features = [] }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > the error still persists.
> > > Moreover, is the flag useful? How would I create a GRPC client if I don't have the `connect` method?..
> > 
> > 
> > I also encountered this problem, how did you solve it?
> 
> Hey! An empty features list actually activates ALL features. You have to populate it with the features you want and not include the feature “transport”, and then it’ll work.
> 
> You’ll basically have to write your own transport code, however.

ok，thank you for your reply. I still have a question. When I write my own transport code, can I refer to the generated connect code and modify it?

**Comment by LucioFranco** [comment]
> ok，thank you for your reply. I still have a question. When I write my own transport code, can I refer to the generated connect code and modify it?

No you will need to use `new` and pass in your own transport.
