### ISSUE TITLE
Investigate `grpc-go` interop client failures with `tonic` server

### ISSUE THREAD

**Issue by LucioFranco** [hyperium/tonic#414]
> FATAL: 2020/07/27 14:36:49 &{0xc000150380}.UnaryCall(_, response_status:<code:2 message:"test status message" > ) = _, rpc error: code = Internal desc = server closed the stream without sending trailers, want _, rpc error: code = Unknown desc = test status message

When running the `status_code_and_message` test case via the grpc-go interop client.

**Comment by alce** [comment]
This was failing because the `EchoHeaderSvc` that wraps `TestService` adds an empty data stream to the response when there are no trailers to echo back. This seems to confuse the client, which expects trailers that never come.

**Comment by LucioFranco** [comment]
Thank you @alce for digging in!
