### ISSUE TITLE
actix-web example (re-using the same port)

### ISSUE THREAD

**Issue by GopherJ** [hyperium/tonic#420]
Hi, I've posted a question in chat. I also would like to create an issue here, I've never used warp/hyper, if tonic can work perfectly with actix-web, that'll be really great news for me because then I don't need to rewrite all my existing code.

**Comment by LucioFranco** [comment]
I am not directly familiar with actix, but if you can construct their own internal http types from the hyper version than it should work. Basically, can you run actix with hyper?

**Comment by kivo360** [comment]
Is this a thing? I'm curious to know the extent in which I can use actix actor model.

**Comment by LucioFranco** [comment]
Actix the actor model != the actix-web project, I think they diverged a while back. That said, if you can run a hyper server on that port then you can run a tonic one.
