### ISSUE TITLE
tonic::Interceptor is not unwind safe

### ISSUE THREAD

**Issue by tobz** [hyperium/tonic#429]
### Version
0.3.0

### Platform
Linux consigliere 5.4.0-40-generic #44-Ubuntu SMP Tue Jun 23 00:01:04 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### Description
As `tonic::Interceptor` is not unwind safe, it is not suitable for use within objects/codepath that themselves must be unwind safe, such as `gotham`.  This is particularly thorny with crates like `gotham` where storing objects in middleware -- for access during request handling -- is the norm for holding shared state.

/cc @LucioFranco

**Comment by tobz** [comment]
This playground is an MVCE of the issue, where `SharedFn` can be thought of as `Interceptor`: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=769c3f025aa3b7cf07a9556152819c53

**Comment by LucioFranco** [comment]
This doesn't seem to hard? We can for sure include this in 0.5
