### ISSUE TITLE
Server/interceptor should be able to see request path, source IP, etc.

### ISSUE THREAD

**Issue by AndiDog** [hyperium/tonic#430]
### Motivation

Server-side functions currently look like

```
async fn my_rpc_func(&self, request: tonic::Request<GetUserDevicesRequest>) { ... }
```

and `request.metadata()` gives information like `MetadataMap { headers: {"content-type": "application/grpc", "user-agent": "grpc-go/1.30.0", "te": "trailers"} }`. This doesn't allow logging the type of request (= request path), source IP or other information generically.

### Proposal

Such information (whichever is available) should be added to `tonic::Request`.

### Alternatives

Only interceptors get this functionality. Worse than the above suggestion because the information is relevant to the server implementation as well, not only for interceptors.

**Comment by LucioFranco** [comment]
Do you not get the rpc path from the actual rpc fn it calls? I am not directly following where you need this data in the code example above.

**Comment by AndiDog** [comment]
It's useful for many purposes, for example for logging. You _could_ repeat logging code in every called RPC function, since there you know which path/function was called, but it's better to have this generally available to not repeat boilerplate code. The source IP is interesting in logs, too.

**Comment by AndiDog** [comment]
That allows me to read `hyper::Request::path_and_query`, for example 👍 But the remote address can't be read from hyper requests (as of 0.13, previous versions had it), but only later in `tonic::Request`. I'd like to log both at once central place, e.g. the interceptor, so is there a way to get the remote address there?

**Comment by LucioFranco** [comment]
@AndiDog if you write a custom connector/acceptor where you handle the tls/tcp connection yourself you can then use the example above and set it there. I know its a bit painful but we need to ship tokio first, then we will tackle these issues in hyper/tonic. Work has made a bit more busy than I would like so things are moving a bit slow. Sorry about that. Feel free to ping me on discord and we can get the context example to work for you.

**Comment by davidpdrsn** [comment]
With https://github.com/hyperium/tonic/pull/634 interceptors will get passed a `&http::Request<()>`. That at least lets you access the path but not the client IP.

I don't feel interceptors is the appropriate place to add logging since they're only called when a request is received and not when a response is sent. Tower is better suited for this with something like [`Trace` in tower-http](https://github.com/tower-rs/tower-http/blob/master/tower-http/src/trace/mod.rs). That is designed with gRPC in mind. tower-http isn't on crates.io yet but we're working on finalizing things.

Something I would like to explore is make it easier to add tower middlewares and improve the docs around it, and then deprecate interceptors. But nothing is decided yet.

**Comment by LucioFranco** [comment]
This should be supported by tower support @davidpdrsn since you've done a lot of that work, if there is a better issue to track that tower work we can close this one.

**Comment by davidpdrsn** [comment]
Yes! This tower-http milestone tracks whats missing for a 0.1 release https://github.com/tower-rs/tower-http/milestone/1. Once that is released logging can be added using `TraceLayer::new_for_grpc()` as shown in this example https://github.com/tower-rs/tower-http/blob/master/examples/tonic-key-value-store/src/main.rs#L170-L172

**Comment by davidpdrsn** [comment]
I think I'm going to close this. We've decided not to make more changes to interceptors for the next release. In the future we're going to explore making tower easier to integrate with tonic as tower is the right place for these kinds of middleware things to live.

For now the `Trace` middleware provided by tower-http is probably the best option for easily adding logging.

Feel free to re-open if you have more questions.
