### ISSUE TITLE
Rewrite keywords?

### ISSUE THREAD

**Issue by entropitor** [hyperium/tonic#433]
### Version
```
├── tonic v0.3.0
├── tonic-health v0.2.0
│   └── tonic v0.3.0 (*)
│   └── tonic-build v0.3.0
└── tonic v0.3.0 (*)
└── tonic-build v0.3.0 (*)
└── tonic v0.3.0 (*)
└── tonic-build v0.3.0 (*)
```

### Platform

Darwin 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64

### Crates
tonic-build

### Description

Create a proto file that contains a rust keyword (e.g. `type`) as a field name

Try constructing the message, you will fail because you cannot set the field. 

Maybe we can add a trailing underscore to the field name so it's possible to create and behind the scenes tonic translates this correctly?

**Comment by LucioFranco** [comment]
This is likely an issue with `prost-build` rather than tonic if I am understanding correctly?

**Comment by entropitor** [comment]
Yes you are correct, I wrongly thought that `tonic-build` was responsible. 

As you can see here https://github.com/danburkert/prost/issues/166 and https://github.com/danburkert/prost/blob/master/prost-build/src/ident.rs#L7-L30 it needs to be `r#type`
