### ISSUE TITLE
Prepare 0.4 release with tokio 1.0

### ISSUE THREAD

**Issue by LucioFranco** [hyperium/tonic#443]

**Comment by saschagrunert** [comment]
I was looking around to find an indicator when tokio 0.3 will be released (roughly). Do you have any reference to for that?

**Comment by LucioFranco** [comment]
@saschagrunert soon, we are currently working on it, there should be a milestone in the tokio repo for it.

**Comment by faern** [comment]
Tokio 0.3 has been released!

**Comment by LucioFranco** [comment]
Work will be going into hyper to get that upgrade so it will be a few days at a min before a new version of tonic, but we are working hard to get there!

**Comment by cfvescovo** [comment]
See https://github.com/hyperium/hyper/issues/2302 for further information

**Comment by anton-dutov** [comment]
@LucioFranco 
prost v0.7 also released with bytes v1.0

**Comment by joseph-wakeling-frequenz** [comment]
Is the intention still to support tokio 0.3, or to jump straight to the 1.0 release?

**Comment by cfvescovo** [comment]
Imho it would be better if we switched directly to tokio 1.0

**Comment by cfvescovo** [comment]
Imho it would be better if we switched directly to tokio 1.0

**Comment by LucioFranco** [comment]
Hey all sorry for the delay, the plan is this:

1) Update to the newer version of hyper
2) Update to utilities in tower when that is released (should be soon)
3) Refactor the server to fix a couple open bugs (I don't want to release a new version that still has those issues).
4) Update to prost 0.7

This is what is planned, but its not trivial atm. That said, my focus the last few months (even longer tbh) has been on tokio since we have needed a solid foundation there. Now that my work there is mostly complete (it was to help get it to 1.0), I can now focus on other areas of the stack.

Writing this as of the 28th of Dec and I am on vacation till the new year, so won't get started on this until then. Hopefully, this gives some context on why things have been a bit slow here but now that tokio 1.0 is out there is a lot of planned work that I will finally get too in 2021.

**Comment by cfvescovo** [comment]
@LucioFranco thank you!
Your contribution to the Rust community is crucial and impressive.
Keep up the good work!

**Comment by LucioFranco** [comment]
Okay so a little update here, most deps have been updated. I have a PR open to fix the blocking bug. I don't currently have much time to fix all the transport issues so I will release `0.4` that is basically a few important bug fixes + tokio 1.0 upgrade. Then in the following months the transport will be extracted into its own crate and redone. The goal for that rewrite is to really fix a lot of the bug/issues/usability problems with the current transport.

**Comment by LucioFranco** [comment]
tonic 0.4 has been released! enjoy!
