### ISSUE TITLE
Can I add multiple Interceptor to a server?

### ISSUE THREAD

**Issue by yes7rose** [hyperium/tonic#448]
I want to add a list of Iterceptor to the service, is tonic support a list of Iterceptor now?
Or there is a way to do this, please help!

Thanks!

**Comment by alce** [comment]
It is not currently possible to add more than one interceptor but you can use `tower::Service` to compose your services. It is a little more involved but a lot more powerful. 

There is an example here https://github.com/hyperium/tonic/blob/master/examples/src/tower/server.rs#L36
