### ISSUE TITLE
Endpoint should be able to accept String instead of &'static str

### ISSUE THREAD

**Issue by GopherJ** [hyperium/tonic#450]
`&'static` str isn't programatically useful, we always generate Url from some places like Config file then pass it to tonic. It's not convinient to use &'static str

**Comment by MikailBag** [comment]
As a workaround, one can use String::into_boxed_str and then Box::leak

**Comment by GopherJ** [comment]
@MikailBag Seems I need to leak a string everytime when I reconnect

**Comment by GopherJ** [comment]
just realized that it implemented `TryFrom<String>` but got another issue
![image](https://user-images.githubusercontent.com/33961674/92327716-f321f300-f05b-11ea-8c42-4e2fb6234fcf.png)

**Comment by alce** [comment]
@GopherJ:

```rust
let url = "http://[::1]:50051".to_string();
let ep = Endpoint::from_shared(url).unwrap();
let fut = ep.connect();
```

This is because `Endpoint::connect` takes `&self`. Not sure why though. It should probably consume `self`.

**Comment by GopherJ** [comment]
@alce Hi, thanks for your help, I tried it but still the same error

**Comment by alce** [comment]
Resolved by https://github.com/hyperium/tonic/pull/451#issuecomment-694435204
