### ISSUE TITLE
A connection opened with `connect_lazy` does not attempt to reconnect if the server is unavailable on first request

### ISSUE THREAD

**Issue by K900** [hyperium/tonic#452]
### Version

```
tonic = 0.3.1
tonic-build = 0.3.1
```

### Platform

Linux 4.9.104-microsoft-standard (WSL2), Linux 5.8.6-NixOS (NixOS)

### Crates

Likely `tonic` itself.

### Description

If a connection is created with `connect_lazy`, a first gRPC call is made, and the server is not available (e.g. not running or rejecting incoming connections), subsequent gRPC calls will not attempt to reconnect to the server, and will instead return an error.

Code and reproducible setup (Docker) here: https://github.com/K900/tonic-issue-repro

Following up from a Discord conversation with @LucioFranco.

**Comment by LucioFranco** [comment]
@alce if you have time to investigate this, that would be great, otherwise, I will try to get to it next week. 

@K900 sorry for the delay!

**Comment by K900** [comment]
No worries!

**Comment by alce** [comment]
@LucioFranco there is a possible solution in https://github.com/hyperium/tonic/pull/458
