### ISSUE TITLE
Support gRPC channel options

### ISSUE THREAD

**Issue by alertedsnake** [hyperium/tonic#453]
I also work with gRPC in Go and Python, and both have a way to use the channel options to do a number of things, in my specific case I'd like to set the `user-agent` header, which cannot be done via metadata.

In Python it looks like this:

```
connect = 'localhost:50041'
user_agent = "monkey 1.0.0"
options = (
    ('grpc.primary_user_agent', user_agent),
)
channel = grpc.insecure_channel(connect, options=options)
```

In Go, it looks like this:
```
endpoint = 'localhost:50041'
user_agent := "monkey 1.0.0"
var options []grpc.DialOption
options = append(options, grpc.WithInsecure())
options = append(options, grpc.WithUserAgent(user_agent)
grpc.Dial(endpoint, options)
```

I cannot find a way to do this with Tonic - am I missing this?  Also, I unfortunately don't know anything about Hyper or Tower, so I don't know where to start implementing it.

**Comment by alertedsnake** [comment]
You can't set the metadata key `user-agent` as that's specifically marked as reserved, and setting a totally different key doesn't allow compatibility with other languages which use that key internally via the methods I described.

**Comment by alce** [comment]
You are right, this is a bug. `user-agent` header should be whitelisted. I'm not sure at this point if we can just remove it from the reserved headers list but will look into it. Thanks.
