### ISSUE TITLE
When using a self-signed certificate to build channel,an error occurred.

### ISSUE THREAD

**Issue by ZhangLei-cn** [hyperium/tonic#459]
### Version
v0.3.1

### Platform
Linux  4.14.81-amd64 #1 SMP Debian 4.14.81 Sun Sep 8 05:02:31 UTC 2019 x86_64 GNU/Linux

### Description
```
let server_root_ca_cert = Certificate::from_pem(server_root_ca_cert);
let client_identity = Identity::from_pem(client_cert, client_key);
    let tls = ClientTlsConfig::new()
        .ca_certificate(server_root_ca_cert)
        .identity(client_identity)
        .domain_name("mongoose-server.bytedance.net");
    let channel = Channel::from_static("https://it_is_a_host:443")
        .tls_config(tls)?
        .connect()
        .await?;
    let mut client = Mongoosev3HealthClient::new(channel);
    let request = tonic::Request::new(HealthCheckRequest {
        service: "Ping".into(),
    });
    let response = client.check(request).await?;

    println!("RESPONSE={:?}", response);
    Ok(())
```
And then:
```
cargo run
- Error: tonic::transport::Error(Transport, hyper::Error(Connect, Custom { kind: InvalidData, error: WebPKIError(BadDER) }))
```
Both CA certificate and client certificate are self-signed,did I do something wrong?
I have reviewed the following issues:
https://github.com/hyperium/tonic/pull/397
https://github.com/ctz/rustls/issues/127
https://github.com/ctz/rustls/issues/373
More information:
* Both CA certificate and client certificate are x509 v3.
* Client certificate has SAN,CA certificate not.

**Comment by ZhangLei-cn** [comment]
From tcpdump:
![image](https://user-images.githubusercontent.com/59213644/93893140-e40b9800-fd1f-11ea-8550-997e6f3bcb7a.png)
In addition, I can communicate successfully on https://github.com/tikv/grpc-rs when using the same certificate and key.

**Comment by LucioFranco** [comment]
Rustls is much more strict than some other implementations that is likely why you are seeing these errors. I would suggest following up with them or using openssl. https://docs.rs/tonic-openssl/0.1.0/tonic_openssl/ this should work.

**Comment by tdelabro** [comment]
I have been facing this issue for a few hours now, I will try tonic-tls that superseded tonic_openssl.
Could there be a way for the tonic crate to make this explicit somewhere in their doc or example?
The reference is not good enough for this thread. I could have spared a few hours if it had been clearly stated somewhere.

**Comment by LucioFranco** [comment]
I would be open to a PR that adds that as a doc if you're interested.

**Comment by tdelabro** [comment]
@LucioFranco sure. Which part of the doc? Readme or some doc in the `ServerTlsConfig`. There is not really a "tls" module in the crate architecture where the doc can naturally fit

**Comment by LucioFranco** [comment]
In reality the error comes from rustls so it should probably be documented there but we could improve our overall `transport` module docs about tls https://docs.rs/tonic/latest/tonic/transport/index.html

**Comment by tdelabro** [comment]
I get that. But I'm not using rustls, I'm using tonic. So that is where I was looking for answers. 
That's why I really think it should be in your codebase.

I will put it in transport/index as a warning
