### ISSUE TITLE
Well known type in `google/protobuf/wrappers.proto` not work

### ISSUE THREAD

**Issue by UkonnRa** [hyperium/tonic#46]
### Version

tonic-0.1.0-alpha.1

### Platform

Windows 10

### Description

Like this issue, https://github.com/hyperium/tonic/issues/25, but `StringValue` and others in `google/protobuf/wrappers.proto` this time

**Comment by LucioFranco** [comment]
Hi! This #49 should fix your issue! I am going to try to get a new release out this week hopefully.
