### ISSUE TITLE
Allow custom error types in RPC methods

### ISSUE THREAD

**Issue by gardk** [hyperium/tonic#463]
### Motivation

One of the things I love about Rust is it's stellar error-handling capabilities and how it helps write correct code. When writing RPC implementations with this library I've noticed excessive and duplicated use of `map_err` or `unwrap` and no custom error types used in those functions.

For some functions with lots of fallible operations, or when there's several functions that can return many of the same errors. I've extracted those out into separate functions and defined a custom error type so I can use `?` and have some centrally defined error handling strategy for the common ones. This works, but being able to do this straight in the impl would be really nice.

### Proposal

As I see it there's two possibilities here:

- Bake some magic into the `tonic::async_trait` macro (or provide a separate one, maybe a function attribute) that wraps the implementation functions in an outer function that returns `tonic::Status` error like before, but coerces the actual return type based on some trait.
- Allow the user to define an error type for each generated function in the trait and convert it in the generated service stub code. This one I'm not that big a fan of cause it currently requires defining the type for every trait function until `associated_type_defaults` lands...

The trait used for conversion I think could look something like this:

```rust
trait ToStatus {
    fn code(&self) -> Code;

    fn status(&self) -> Status {
        let code = self.code();
        Status::new(code, code.description())
    }
}

impl<T: ToStatus> From<T> for Status {
    fn from(custom: T) -> Self {
        custom.status()
    }
}

// example impl
impl ToStatus for Code {
    fn code(&self) -> Code {
        *self
    }
}
```

What do you guys think? I'd be more than happy to attempt implementing this myself, but I've never written any real macro code before. :)

Thanks for reading!

**Comment by gardk** [comment]
I've cobbled together an attribute macro that seems to get the job done:

[gardk/tonic_rpc_wrapper](https://github.com/gardk/tonic_rpc_wrapper)

**Comment by alce** [comment]
There is some upcoming work to improve internal error handling and I have been thinking about ways to make it easier to use richer error model with `google.rpc.Status`. It may be worth it to look into all this, including your proposal, in an unified way. It will take a little while though, so thank you for your patience.

Personally, I  share your observation about `Status` conversions. I have tried a couple of approaches, none of which I completely like. It's a minor thing and I'm not sure what can be done about it or how but I believe it's worth considering.

**Comment by LucioFranco** [comment]
You likely want to take advantage of `Try` to convert errors into `Status` I believe that should work. Usually, what I see is people will have custom code to convert their internal errors into `Status`, I think this is the correct method.

**Comment by gardk** [comment]
Thank you for the responses! I look forward to seeing any future work you may have in store for this.

As for the comment about using `Try`. This will only work directly (without `Result::map_error`) when the fallible function being called returns a first-party error if I'm not mistaken? What prompted me posting this issue was that I wanted to treat Diesel's errors the same for many of my handlers within a service. And there is no direct conversion from those into `Status` that I'm aware of.

What I ended up doing was mapping any handled third-party errors into a custom error type, then using `?` for conversion to `Status`, which is almost the same.

However, it looks like you're aware of this little snag and may be looking into it, which was really all I wanted :)

**Comment by LucioFranco** [comment]
@gardk Yeah, the intermediate error type imo is great too. I think its always good to funnel errors into a "application" defined one that then can get translated into say `Status` or some other http style error. So I think that is the correct solution!
