### ISSUE TITLE
How to create tls config with default public root certificate.

### ISSUE THREAD

**Issue by anykao** [hyperium/tonic#465]
How to create a client same as below nodejs code
```javascript
const client = new hello_proto.Greeter(
  "myhost:443",
  grpc.credentials.createSsl()
);
```

**Comment by alce** [comment]
I don't know how the nodejs client works but you can take a look at the [transport docs](https://docs.rs/tonic/0.3.1/tonic/transport/index.html). There are also a couple of tls [examples](https://github.com/hyperium/tonic/tree/master/examples/src) available.

**Comment by alce** [comment]
Also, there is a `tls-roots` feature flag that will enable `rustls-native-certs`, maybe that's what you are after?

**Comment by anykao** [comment]
Thank you for your advice.

I just tried 
```rust
    let tls = ClientTlsConfig::new();
    // create channel connect to server
    let channel = tonic::transport::Channel::from_static(
        "https://myhost",
    )
    .tls_config(tls)
    .expect("Couldn't create TLS configuration")
    .connect()
    .await?;
```
but got 
```
Error: tonic::transport::Error(Transport, hyper::Error(Connect, Custom { kind: InvalidData, error: WebPKIError(UnknownIssuer) }))
```
I'll try tls-roots feature.
