### ISSUE TITLE
Add a function to close streaming client.

### ISSUE THREAD

**Issue by ZhangLei-cn** [hyperium/tonic#473]
For example,if the request is an unbounded stream:
```
client.send(unbounded_stream).await.unwrap();
```
The parameters of the `send()` method is required a `Stream Trait` itself (instead of ref), so I will have no way to end the stream client through `drop(unbounded_stream)`.
Maybe I did something wrong?
Sincere thanks.

**Comment by LucioFranco** [comment]
You need to drop all the sender sides of the channel to then cause the unbounded stream to end.
