### ISSUE TITLE
Add option for generating clients which take `self` by value in RPC calls

### ISSUE THREAD

**Issue by Daniel-B-Smith** [hyperium/tonic#478]
### Crates

This should probably be added to tonic-build.

### Motivation

Making concurrent requests to a single client is currently challenging. Here's the code I (more or less) want to write:

```rust
let client = set_up_client();
let futs = futures::FuturesUnordered::new();

for req in generate_requests {
  futs.push(client.call(req));
}

... do something with futs ...
```

The problem is that the generated client takes `&mut self` as the first parameter of `call`, so the borrow checker won't allow the above code. The obvious thing would be to clone the client, but then I have to allocate space to store the cloned clients. That's both clunky and inefficient since I'm already allocating space in `FuturesUnordered`.

Here's my current workaround:

```rust
struct OwningClient {
    client: RpcClient<Channel>,
}

impl OwningClient {
    async fn call(
        mut self,
        request: impl tonic::IntoRequest<Request>,
    ) -> Result<tonic::Response<Response>, tonic::Status> {
        self.client.filter(request).await
    }
}

let client = set_up_client();
let futs = futures::FuturesUnordered::new();

for req in generate_requests {
  futs.push(OwningClient{ client: client.clone() }.call(req));
}
```

### Proposal

My proposal is to add an option to configure tonic-build to output a generated client that takes `mut self` as a value instead of `&mut self`.

### Alternatives

Arguably, since cloning a client is cheap, taking self by value by default could make sense. Unfortunately, that would be a breaking change and would add some overhead for non-concurrent workloads.

**Comment by Daniel-B-Smith** [comment]
Closing this as https://github.com/hyperium/tonic/issues/44 has an example of a better pattern.

**Comment by mieubrisse** [comment]
@Daniel-B-Smith is there any way we could leave this open? I have the same struggle as OP - wanting to pass around a client object, and confused why it takes `&mut self` - and it seems like https://github.com/hyperium/tonic/issues/44 is more focused around benchmarks than the `&mut self` issue

**Comment by Daniel-B-Smith** [comment]
If the clients took `self` by value, you would have to recreate the client each time regardless as calling the method would move `self` into itself.

**Comment by mieubrisse** [comment]
Ah the original says by-value but I was thinking by-ref - i.e. `&self`
