### ISSUE TITLE
version 0.3.1 has undeclared dependency on tower-util 0.3.1

### ISSUE THREAD

**Issue by tkaitchuck** [hyperium/tonic#480]
> I met same error.
> If anyone confuse because of this, try insert below to dependencies section of Cargo.toml.
> ```
> tower-util = "0.3.1"
> ```
_Originally posted by @PG-kura in https://github.com/hyperium/tonic/issues/422#issuecomment-691827551_

This error affects anyone directly depending on `tonic` without declaring a dependency on `tower-util`.

**Comment by LucioFranco** [comment]
Sounds like we just need to bump this version in tonic?

**Comment by LucioFranco** [comment]
running `cargo update` should fix this
