### ISSUE TITLE
Connection refused with grpc rust and go client

### ISSUE THREAD

**Issue by Yepez1997** [hyperium/tonic#485]
As the title says, I am using a go client and a rust gRPC server and get the following: **rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 192.168.7.106:50052: connect: connection refused**". Running the entire setup in a kubernetes env and I am assuming its because run the go client with grpc.WithInsecure(). Is there a equivalent is tonic where I do not have to specify any form of tls ? I will add tls at some point and I just want to know why my connection refused from a go client -> rust tonic grpc server ! 

address in rust server
let addr = "127.0.0.1:50052".parse().unwrap();

address in go client
dns-name:5002

.toml 
tonic = "0.2"
prost = "0.6"
tokio = { version = "0.2", features = ["macros", "sync", "stream", "time"] }

rust version
1.47.0

**Comment by alce** [comment]
To run a server with tls you would need to configure it explicitly:

```rust
Server::builder()
    .tls_config(....)?
    .add_service(Foo)
    .serve(addr)
    .await?;
```

Same server without tls:

```rust
Server::builder()
    .add_service(Foo)
    .serve(addr)
    .await?;
```

Assuming it is not a typo, your server is binding to `50052`, but your client is  trying to connect to `5002`. Other than that, it is hard to say. There are so many possibilities that depend on how your tonic deployment is exposed in the cluster, where is your client running, etc. This is more likely an issue with your setup though.

**Comment by alce** [comment]
Oh, maybe try:

 ```rust 
let addr = "0.0.0.0:50052".parse().unwrap(); 
```

**Comment by Yepez1997** [comment]
5002, was a typo. yes I'm trying out "0.0.0.0:50052". I tried running the server with "[::1]:50052" and **I get the following: Error: tonic::transport::Error(Transport, hyper::Error(Listen, Os { code: 99, kind: AddrNotAvailable, message: "Cannot assign requested address" }))**

**Comment by Yepez1997** [comment]
for some odd reason this: **let addr = "0.0.0.0:50052".parse().unwrap()**; worked over let addr = "[::1]:50052".parse().unwrap(); and let addr = "127.0.0.1:50052".parse().unwrap();

**Comment by otaviopace** [comment]
I had the same issue and `0.0.0.0` instead of `[::1]` solved for me too :tada:

**Comment by gklijs** [comment]
Maybe the examples could be changed? Still trying to get it to work, but changing from `[::1]`->`0.0.0.0` gives me `kind: InvalidData, error: WebPKIError(BadDER)` instead of connection refused, so I'll guess that's progress..

**Comment by jcramb** [comment]
Has anyone looked into why changing to 0.0.0.0 fixes this? This fixes the same issue I had but I'd like to run it only on localhost.

**Comment by keegit** [comment]
Same issue, not sure why it's a thing..

**Comment by gklijs** [comment]
Not sure if it helps anyone, but with the Java client as `BlockingClient client = new BlockingClient("localhost", 50030);` and running the server in docker, it works.

**Comment by nobody5624120** [comment]
How do I connect with termux rust?
