### ISSUE TITLE
Unexpected compression flag/Corrupted data frame

### ISSUE THREAD

**Issue by MarnixKuijs** [hyperium/tonic#492]
### Version

0.3.1

### Platform

Rust: 1.49.0-nightly

OS: Windows 10 version 2004

### Description

I'm writing a custom gRPC client that  is based on top of WinHttp. I'm communicating with a gRPC server that is implemented via Tonic. I'm sending, as far as I know, a valid gRPC request, but I get a response back from the Tonic server that indicates that there was an error:
```
HTTP/1.1 200 
Date: Thu, 12 Nov 2020 19:58:53 GMT
Content-Type: application/grpc
grpc-status: 13
grpc-message: Unexpected compression flag: 64, while sending request
```
Tls is enabled on both my client and server and the HTTP/2 connection is established via the ALPN. I have set all the necessary flags on the WinHttp side to start sending HTTP/2 request.

As far as I know I do have a valid HTTP/2 connection. I am sending over a valid [Http/2 Connection preface](https://httpwg.org/specs/rfc7540.html#ConnectionHeader) and SETTINGS frame and it passes all theses checks on the server My request gets all the way to where tonic starts processing the request, but when it starts [decoding the stream](https://github.com/hyperium/tonic/blob/master/tonic/src/codec/decode.rs#L177) it errors out.

My first thought was simply that I forgot to set the compression flag in my request. I took to the discord of tonic to ask around. I got some answers from the developers and it seems that the my data frames are incorrect somehow. I'm opening this issue per request by @LucioFranco.

**Comment by LucioFranco** [comment]
I believe in this case we need to just expand the error message to state that we are not talking the correct protocol. So it should just be adding some extra message https://github.com/hyperium/tonic/blob/master/tonic/src/codec/decode.rs#L173

**Comment by davidpdrsn** [comment]
@LucioFranco something like this https://github.com/hyperium/tonic/pull/663?
