### ISSUE TITLE
combining interceptors

### ISSUE THREAD

**Issue by tiziano88** [hyperium/tonic#499]
It would be useful to expose methods to combine two (or more) interceptors together into a single one, simply by running one after the other. Currently the [Interceptor](https://docs.rs/tonic/0.3.1/tonic/struct.Interceptor.html) type is completely opaque, so it is not possible to even implement this functionality at all in client code or third party libraries (unless I'm missing something).

**Comment by LucioFranco** [comment]
Potentially, I think interceptors are not as useful as I originally planned. I have some ideas on how to improve this by using tower directly which would allow you to do this type of combining.

**Comment by davidpdrsn** [comment]
@LucioFranco Wanna share what you have in mind? I would be up for helping out 😊

**Comment by aegonz** [comment]
I would assume it will be something similar to what is mentioned in the Interceptor documentation.

`If you would like to apply middleware like features to the body of the request, going through the tower abstraction is recommended.`

**Comment by LucioFranco** [comment]
Yeah @aegonz that is basically it.

**Comment by davidpdrsn** [comment]
This might be drastic but is there anything you can do with interceptors that tower middlewares cannot do? If not what are your thoughts about removing interceptors all together? It seems several users are trying to make interceptors do things better handled by tower, such as logging.

**Comment by davidpdrsn** [comment]
This was fixed in https://github.com/hyperium/tonic/pull/651. The API for adding tower middleware has been simplified quite a bit and interceptors are now based on tower `Service` which means you can add multiple and compose them in the same way you would any other `Service`.

There are some examples here https://github.com/hyperium/tonic/tree/master/examples/src/tower.
