### ISSUE TITLE
How to call add_service in a function

### ISSUE THREAD

**Issue by wllenyj** [hyperium/tonic#503]
I want to implement a func, it receive a Router or Server params and return a Router, eg:
``` Rust
pub fn start_grpc() {
    // ....
    let mut grpc = GrpcServer::builder();
    let greeter = GreeterServer::new(MyGreeter::default());
    let router = add_service(greeter);

    #[cfg(feature = "echo")]
    let router = register_echo(router);

    #[cfg(feature = "xxx")]
    let router = register_xxx(router);

    router.serve(addr).await?;
    // ....
}
pub fn register_echo(router: Router<A, B>) => Router<S, Or<A, B, Request<Body>> {
    let echo = EchoServer::new(MyEcho::default());
    router.add_service(echo)
}
```
Currently, tonic::transport::service::router::Or is private, and how to implement register_echo func. 
Thanks all, please help me.

**Comment by alce** [comment]
There is an `add_optional_service` function that you could use for this. [Example](https://github.com/hyperium/tonic/blob/master/examples/src/optional/server.rs)

**Comment by alce** [comment]
To be clear, the `add_optional_service` allows you to register services conditionally, which is what I understand you ultimately want to do. You could combine this with functions that configure and return (but not register) your services. For example, instead of 
```rust
fn register_echo(router: Router<A, B>) -> Router<S, Or<A, B, Request<Body>>
```
you could have something like
```rust
fn build_echo() -> EchoServer<MyEcho>
```
or even
```rust
fn build_echo(state: Arc<Mutex<MyState>>) -> Option<EchoServer<MyEcho>>
```
or something along those lines.

**Comment by wllenyj** [comment]
> To be clear, the `add_optional_service` allows you to register services conditionally, which is what I understand you ultimately want to do. You could combine this with functions that configure and return (but not register) your services. For example, instead of
> 
> ```rust
> fn register_echo(router: Router<A, B>) -> Router<S, Or<A, B, Request<Body>>
> ```
> 
> you could have something like
> 
> ```rust
> fn build_echo() -> EchoServer<MyEcho>
> ```
> 
> or even
> 
> ```rust
> fn build_echo(state: Arc<Mutex<MyState>>) -> Option<EchoServer<MyEcho>>
> ```
> 
> or something along those lines.

Thank you for your advice.
