### ISSUE TITLE
Support for adding attributes to generated *_client/*_server modules

### ISSUE THREAD

**Issue by tarcieri** [hyperium/tonic#504]
### Crates

`tonic_build`

### Motivation

We're using `tonic_build` to compile both proto and service definitions. However, we'd like to gate the service definitions on a cargo feature (e.g. `grpc`), so it's possible to use the protos independently of Tonic for use in e.g. WASM environments.

### Proposal

Add a new method to `tonic_builder::Builder` similar to the existing `field_attribute` and `type_attribute` methods, but instead: `module_attribute`.

This would make it possible to add an attribute like `#[cfg(feature = "grpc")]` to the generated modules to gate usages of Tonic.

### Alternatives

We managed to "solve" our immediate problem by [munging the output of `tonic_build`](https://github.com/cosmos/cosmos-rust/pull/8/files#diff-58406f56aa9701745b57c8af4adb067401ed9cb97ee7cad24938a905f8314f36R271-R281), however it's something of a brittle hack. A first-class feature for this would be much more robust.

**Comment by davidpdrsn** [comment]
I might be wrong but wouldn't this feature require support for `module_attribute` in prost build?

**Comment by davidpdrsn** [comment]
Fixed by https://github.com/hyperium/tonic/pull/684
