### ISSUE TITLE
mTLS Authorization

### ISSUE THREAD

**Issue by brpatel12** [hyperium/tonic#511]
### Crates

https://docs.rs/tonic/0.3.1/tonic/transport/index.html
ClientTlsConfig, ServerTlsConfig?

### Motivation

This is more of an inquiry if there's a suggested way to handle authorization via tonic's mTLS capabilities. I've seen the [examples](https://github.com/hyperium/tonic/tree/master/examples/src/tls_client_auth) posted for client/server mTLS, but was wondering how you imagined one would handle authorization.

For example, let's say I have the following to set of x509 certs + keys for mTLS, and only client 2 is allowed to communicate with the server. Is there an out-of-the-box way to do this?

Server
- server.pem
- server.key
- server_ca.pem

Client1
- client1.pem
- client1.key
- client_ca.pem

Client2
- client2.pem
- client2.key
- client_ca.pem (same ca as client1)

### Alternatives

One way to handle authorization would be to set a CN/SAN in the client x509 (maybe just SAN: "client1" / "client2") and the server then has a means to check incoming connections and compare the SAN from the incoming request against some allow-list for client connections (or even have that allow list baked into the certificate somehow?). 

This is just an idea, I'm actually not sure how authorization is generally accomplished, and baking the info into the certs gives us integrity.

If this isn't available out-of-the-box, is there a suggested way to do this? interceptor + mTLS combination? other?

**Comment by LucioFranco** [comment]
How to exactly do it usually comes down to the TLS provider you're using. I would suggest maybe opening an issue with them to see how they suggest to approach it. For tonic, generally you can have some interceptor or handle function check the peer cert and reject the request if it doesn't match.

**Comment by brpatel12** [comment]
Gothca, I see #535 gives an example. I tried this out and continually get "None" even with certs specified. I see issue #325 so was just wondering if this is fixed in 0.4?

**Comment by Nako11** [comment]
I am relatively to TLS and don't know if i am missing something, but when i try to match the peer cert in the function i get a completely different cert. For example even though the the client uses "client1.pem" i always get Error "Wrong cert":
`rust
    async fn unary_echo(&self, request: Request<EchoRequest>) -> EchoResult<EchoResponse> {    
        let certs = request    
            .peer_certs()    
            .expect("Client did not send its certs!");    
        let client1_cert = tokio::fs::read("examples/data/tls/client1.pem").await?;    
        let client1_cert = Certificate::from_pem(client1_cert);    
        if certs[0].get_ref() != client1_cert.get_ref() {    
            return Err(Status::unauthenticated("Wrong cert"));    
        }    
    
        let message = request.into_inner().message;    
        Ok(Response::new(EchoResponse { message }))    
    }    

`

**Comment by LucioFranco** [comment]
@brpatel12 its been fixed in 0.4.

@Nako11 can you get this working with just rustls? If so the bug may be in tonic but I am not sure.

**Comment by Nako11** [comment]
@LucioFranco please excuse the late response. I may have found the root of the issue. Rustls saves its certificates in the DER-format (see https://github.com/ctz/rustls/blob/main/rustls/src/key.rs#L15), therefore comparing the pem-bytes like in my example won't be correct. When I convert the pem-file to der via openssl:
`openssl x509 -inform PEM -outform DER -text -in client1.pem -out client1.der`
the code example from above works when exhanging "client1.pem" with "client1.der". Therefore the naming of the pem-field in Certificate: https://github.com/hyperium/tonic/blob/master/tonic/src/transport/tls.rs#L4 is a little unfortunate.

**Comment by LucioFranco** [comment]
So if I understand correctly the actual format within that struct is a `der`? So it would make sense to rename it to that?

**Comment by ian-p-cooke** [comment]
> So if I understand correctly the actual format within that struct is a `der`? So it would make sense to rename it to that?

The certificate Rustls returns for `get_peer_certificates` is [DER-encoded](https://github.com/rustls/rustls/blob/63c5368e57bb6bc6245cdd07b1f505a5a841beeb/rustls/src/key.rs#L15) but when you map it into your own Certificate struct [you use `from_pem`](https://github.com/hyperium/tonic/blob/ddab65ede90f503360b7adb0d7afe6d5b7bb8b02/tonic/src/transport/server/conn.rs#L121) which is why @weigangd had to flip the encodings.  If you know that your Certificate here is actually DER-encoded you can parse it and display the information within like:
```Rust
        println!("Got {} peer certs!", certs.len());

        let (_, client_certificate) = x509_parser::parse_x509_certificate(&certs[0].get_ref()).unwrap();

        // the client's DN
        println!("{}", client_certificate.subject());

        // find email in SAN if available
        for ext in client_certificate.extensions() {
            let parsed_ext = ext.parsed_extension();
            if let ParsedExtension::SubjectAlternativeName(san) = parsed_ext {
                for name in &san.general_names {
                    if let GeneralName::RFC822Name(email) = name {
                        println!("found email SAN: {}", email);
                    }
                }
            }
        }

        let message = request.into_inner().message;
```

So, consider what you want the Certificate in transport::tls to represent... I think now you have it as a PEM-encoded certificate in which case you should stick the Rustls DER-encoded certificate into a different struct.

**Comment by LucioFranco** [comment]
I'd like to deprecate TLS support in tonic to extraction to its own crate so that `axum` and `tonic` can share the implementation. So for now not going to address this issue.

**Comment by Evanfeenstra** [comment]
bump. any plans on supporting `mtls`?
