### ISSUE TITLE
Add rust-analyzer config to faq

### ISSUE THREAD

**Issue by estk** [hyperium/tonic#512]
### Crates

tonic

### Motivation

I noticed rust-analyzer could not find my tonic-build built pb modules unless I turned on `loadOutDirsFromCheck`.

### Proposal

 I think it would be nice if this was in the quickstart.

### Alternatives

idk

**Comment by LucioFranco** [comment]
Yeah, we could add a quick note to the README, I think that is reasonable.

**Comment by tomasol** [comment]
According to the [changelog](https://github.com/rust-analyzer/rust-analyzer.github.io/blob/c31f2c2517fdf3fe859c3f99e398e28e61d810c2/thisweek/_posts/2021-03-08-changelog-67.adoc#new-features), the property has been renamed:
> pr:7868[] rename rust-analyzer.cargo.loadOutDirsFromCheck to rust-analyzer.cargo.runBuildScripts.

However I cannot seem to make it work, the `Go to Definition` only navigates me to `tonic::include_proto!(...)`

**Comment by LucioFranco** [comment]
I am also having some issues with RA and vscode. Will try to debug and update here once I find something.

**Comment by llint** [comment]
> I am also having some issues with RA and vscode. Will try to debug and update here once I find something.

Any updates on this? I'm having a hard time getting this to work (RA + vscode)

**Comment by ParkMyCar** [comment]
Just following up here, I hit this issue of rust-analyzer not being able to "Go to Definition" and it seems like an RA issue with not supporting the `include!` macro which `tonic::include_proto!` uses internally, see https://github.com/rust-lang/rust-analyzer/issues/3767
