### ISSUE TITLE
Can I use Tonic without Protobuff's?

### ISSUE THREAD

**Issue by SilentCicero** [hyperium/tonic#513]
## Feature Request

Hi there, awesome work with Tonic. Is there any examples or code reference for custom encoding / serialization. Say we wanted to use something like XDR or RLP for example.

### Crates

most recent.

### Motivation

Community improvement.

### Proposal

Provide examples of custom encoding / decoding if not already.

**Comment by LucioFranco** [comment]
It is possible if you use the `Codec` trait and wire up the codegen properly. There should be a similar `Service` trait in `tonic-build`.

**Comment by SilentCicero** [comment]
Awesome, I would really like to use some custom codecs and just re-wire the tonic-build a bit. The rest of the RPC infra is very cool. Not sure I need all the HTTP/2 stuff or If I can really benifit.

But in general I just want hyper + my encoding scheme (likely custom Codec/Service).

**Comment by adamrk** [comment]
I was just working on a wrapper around tonic that uses other encodings (json, cbor, bincode, or messagepack): https://github.com/adamrk/tonic-rpc. I was hoping it could support user-defined encodings, but that seems tricky at the moment. But maybe it could work for you if you like one of those encoding options?

**Comment by davidpdrsn** [comment]
I think I'm gonna close this as it seems to be resolved.

@SilentCicero please re-open if you have more questions. You're also very welcome to ask on the [Tokio Discord](https://discord.gg/tokio). There are tonic and hyper channels as well.
