### ISSUE TITLE
Support Prost 0.7.0

### ISSUE THREAD

**Issue by wchargin** [hyperium/tonic#517]
## Feature Request

Upgrade to support Prost 0.7.0.

### Crates

All.

### Motivation

[Prost 0.7.0][rel] is now out. It includes general improvements, like
support for zero-copy deserialization of `bytes` fields, as well as
improvements of specific interest to Tonic, like support for file
descriptor sets to support gRPC reflection.

Applications that use Tonic cannot easily upgrade Prost until Tonic
itself is updated. (When I try to make the obvious change in my
downstream project, I get a slew of trait bound errors because of the
duplicate versions of `prost::message::Message`.)

Prost 0.7.0 depends on `bytes = "1"`, so this may be blocked on
upgrading to v1 of the Tokio ecosystem.

[rel]: https://github.com/danburkert/prost/releases/tag/v0.7.0

**Comment by djc** [comment]
This was done, as part of #530.

**Comment by wchargin** [comment]
Sweet! Thanks @djc for the heads up and thanks to everyone on #530,
#514, and related work for the quick implementation here.

Looks like releasing is probably covered by #443, so I’ll close this.
