### ISSUE TITLE
How to serve multiple servers on same http2 server?

### ISSUE THREAD

**Issue by zakhenry** [hyperium/tonic#52]
Hello, thanks for this library it is so far working very well for me, a nearly complete beginner to rust.

I've got the example hello world server/client all up and running happily and now want to extend that server by adding the [gRPC health check service](https://github.com/grpc/grpc/blob/master/doc/health-checking.md) to the hello world service. I'm got this working correctly _instead of_ the hello world server, but I'm having trouble getting them running side by side. I tried the following, which compiles and runs, but only serves the hello world serve, the health check one simply returns `ERR=Status { code: Unimplemented }`

```rust
#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let addr = "[::1]:50051".parse().unwrap();
    let greeter = MyGreeter::default();

    let greeter_server = Server::builder()
        .serve(addr, GreeterServer::new(greeter));

    let example = ExampleServer::default();
    let health_server = Server::builder()
        .serve(addr, HealthServer::new(example));

    join!(greeter_server, health_server);

    Ok(())
}

```

It seems that the second server is clobbering the endpoints of the first server? I'm not really sure where to go from here, so any pointers would be greatly appreciated!

**Comment by LucioFranco** [comment]
@zakhenry Hi! 

So, unfortunately, this part of tonic and tower is a bit rough at the moment. You can reference https://github.com/hyperium/tonic/issues/29 for the issue tracking this. 

So it is possible to route it is just a bit manual right now https://github.com/hyperium/tonic/blob/master/tonic-interop/src/bin/server.rs#L73 this routes between a `TestService` and an `UnimplementedService`.

Hopefully this helps you out!

**Comment by tjtelan** [comment]
Multiplexed server routing is covered in the examples now.

https://github.com/hyperium/tonic/blob/f9502dfd7ef306fff86c83b711bc96623555ef5c/tonic-examples/src/multiplex/server.rs#L23-L36

**Comment by LucioFranco** [comment]
Yup, thanks for updating this, I think we can close it! Feel free to reopen if your issue is not resolved.

**Comment by zakhenry** [comment]
Hey thanks for the update, I got kinda stuck with the other strategy and ended up working on other projects, but coming back to this one and using the new `.add_service` method works perfectly, thanks!
