### ISSUE TITLE
Should Interceptor be async?

### ISSUE THREAD

**Issue by algermissen** [hyperium/tonic#525]
I am using Interceptor to add authentication token to client request. Periodically, I need to refresh the token, which requires an HTTP request. Since Interceptor function is not asynchronous it does not blend in with an asynchronous request to refresh the token - I'll essentially need to block in the Interceptor until the token is refreshed.

Is there a different desired approach toward such use cases? 

Or, if Interceptor is the right place to add authentication token to request, are there any plans to make the Interceptor async?

**Comment by LucioFranco** [comment]
Interceptors for the moment are not async because they are designed to be simple to use. This will change in the future. I have plans to rewrite the transport and expose things in an easier way.

**Comment by LucioFranco** [comment]
if you need to do async work like fetch a token I suggest doing that outside the request path and using something like `ArcSwap` to bring it back into the handler. Otherwise, you will need to do the async work in the handler which is a bit extra work but will unblock you for now.

**Comment by algermissen** [comment]
thanks a lot for clarification of plans!
