### ISSUE TITLE
Follow redirects in client

### ISSUE THREAD

**Issue by davidpdrsn** [hyperium/tonic#528]
### Motivation

I just ran into an issue where a client was configured to use `http://` which would result in the server sending a 308 redirect to `https://` instead. The client didn't understand that though and returned an error.

### Proposal

Would be cool if there was an option to make the client follow redirects 😊 

### Alternatives

I tried solving it wrapping my client in a tower service that would follow redirects by looking for 308 responses, change the request URI to match the Location header, and `call` the inner service again. However that isn't possible since `Request<BoxBody>` isn't `Clone` so you cannot send the request more than once.

**Comment by LucioFranco** [comment]
This sounds like something hyper is doing in its connector?

**Comment by davidpdrsn** [comment]
Oh yeah I didn't consider hyper. I'll look into what they have.
