### ISSUE TITLE
Stream issue

### ISSUE THREAD

**Issue by mezeipetister** [hyperium/tonic#532]
Hi Guys, I have a microservice, api issue, when using Stream. I use tokio 0.2 and tonic 0.3 on both side.

When on the microservice I write data into a Stream, and using channel(4), so with capacity 4, it only works if the data is less then 4.

Here is my service code:

```rust
async fn get_price_bulk(
    &self,
    request: Request<GetPriceBulkRequest>,
  ) -> Result<Response<Self::GetPriceBulkStream>, Status> {
    // Create channels
    let (mut tx, rx) = tokio::sync::mpsc::channel(4);
    // Get found price objects
    let res = self.get_price_bulk(request.into_inner()).await?;
    // Send found price_objects through the channel
    for price_object in res.into_iter() {
      tx.send(Ok(price_object))
        .await
        .map_err(|_| Status::internal("Error while sending price bulk over channel"))?
    }
    return Ok(Response::new(rx));
  }
```

and on the API(client) side:

```rust
let mut result: Vec<PriceHistoryForm> = Vec::new();

  let res = match services
    .pricing
    .get_price_history(GetPriceRequest { sku })
    .await
  {
    Ok(resp) => Some(resp.into_inner()),
    Err(_) => None,
  };

  if let Some(mut all) = res {
    while let Some(ph) = all.message().await.map_err(|e| ApiError::from(e))? {
      result.push(ph.into());
    }
  }

  Ok(warp::reply::json(&result))
```

I have no idea what is wrong with this. Its based on the examples attached to this repo.

So if the data is less then the given buffer it works, otherwise, the API(client) never ends the while loop to get all the data from the stream.

Could you help me please what I am doing wrong?

Thank you in advance!

**Comment by mezeipetister** [comment]
Ok, so I found, that in the sender side I need to put the sender iteration block into tokio::spawn(...), because as I understand otherwise the channel never close.

But what I dont understand:
Without using spawn(...) if the item number is less then the channel buffer size, it works. Why? How it closes the channel, but after succeeding the channel size, it why not?

**Comment by LucioFranco** [comment]
Because you are blocking the initial handler from replying, which then initiates the whole request basically. The await is stopping the response and initial headers from being sent.

**Comment by davidpdrsn** [comment]
As Lucio said your blocking the server from replying by doing

```rust
let res = self.get_price_bulk(request.into_inner()).await?;
```

I'm gonna close this for now but feel free to re-open if you have more questions.
