### ISSUE TITLE
Should feature transport appears in config.toml?

### ISSUE THREAD

**Issue by smhmayboudi** [hyperium/tonic#533]
### Version

```bash
│   ├── tonic v0.3.1
│   └── tonic v0.3.1 (*)
├── tonic v0.3.1 (*)
├── tonic-health v0.2.0
│   └── tonic v0.3.1 (*)
│   └── tonic-build v0.3.1
└── tonic-build v0.3.1 (*)
```

### Platform

```bash
Darwin local.local 20.2.0 Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64 x86_64
```

### Crates

```bash
tonic = { default-features = false, version = "0.3.1" }
```
### Description

Based on [DOC](https://docs.rs/tonic/0.3.1/tonic/transport/server/struct.Server.html#method.trace_fn), I have to enable transport feature to use method trace_fn, but without it the code cmpiles and runs fine. I think I have to receive a panic message.

**Comment by LucioFranco** [comment]
I'm not quite sure what you're asking? Could you print the error you are getting or what you expect?

**Comment by smhmayboudi** [comment]
```rust
pub fn trace_fn<F>(self, f: F) -> Self
where
    F: Fn(&HeaderMap) -> Span + Send + Sync + 'static, 
```
This is supported on feature="transport" only.

If I use `tonic = { default-features = false, version = "0.3.1" }` instead of `tonic = { default-features = false, features = ["transport"], version = "0.3.1" }` and use trace_fn method in my server bootstrap, Should I receive an error or not?

I think I should receive an error, however, cargo build or run does not complain and everything is fine. Based on other libs, they panic and guide me to enable the needed feature via config.toml. The error is get no error since I am not following the rules.

**Comment by olix0r** [comment]
`tonic-health` enables the `transport` feature by default:
https://github.com/hyperium/tonic/blob/31936e0513a41e83c8137786bd417fe57ecd05eb/tonic-health/Cargo.toml#L17

So, since it's being enabled by a dependency, it's not strictly necessary to enable in your own dependencies (though it's still a good idea).

**Comment by smhmayboudi** [comment]
You are right. Is this behavior apply to all other lilbs as well?
