### ISSUE TITLE
Update routeguide tutorial for tokio 1.0

### ISSUE THREAD

**Issue by homelessnessbo** [hyperium/tonic#540]
## Feature Request
Hola compadres!

Newbie here, was going through the routeguide tutorial and noticed that it uses really old version of tokio. In the same time https://github.com/hyperium/tonic/issues/443 this here states that tonic is ready for v1.0 of tokio, so I was wondering if it is possible to update the tutorial to make it closer to real life example?

Basically the error is:
```
error[E0277]: the trait bound `tokio::sync::mpsc::Receiver<std::result::Result<Feature, Status>>: futures_core::Stream` is not satisfied
   --> src/main.rs:22:5
    |
22  |     type ListFeaturesStream = mpsc::Receiver<Result<Feature, Status>>;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `futures_core::Stream` is not implemented for `tokio::sync::mpsc::Receiver<std::result::Result<Feature, Status>>`
    | 
   ::: /home/ikiselev/git/rust/routeguide/target/debug/build/routeguide-d2cfcf7a92f3d239/out/routeguide.rs:196:34
    |
196 |         type ListFeaturesStream: Stream<Item = Result<super::Feature, tonic::Status>>
    |                                  ---------------------------------------------------- required by this bound in `RouteGuide::ListFeaturesStream`
```

I suggest it's somehow connected to tokio [moving out `stream` feature to a separate crate](https://docs.rs/tokio/1.0.2/tokio/stream/index.html#why-was-stream-not-included-in-tokio-10), but being generally newbie in rust - I couldn't understand how to use it to come up with a solution. Also, if somebody would give me a clue in what direction to dig - I'll happily submit a PR when I find how to fix the thing

### Motivation

Tutorials being up to date and not using outdated libraries/APIs is just always nice thing to have

**Comment by homelessnessbo** [comment]
Ah wait, I see that in the examples Cargo.toml - `tokio` is already `1.0`. So it's that the tutorial itself was not updated! 

That makes it easier!

**Comment by LucioFranco** [comment]
Yeah, we just need to update that, I think I just missed it in the release PR :D

**Comment by andresv** [comment]
I just stumbled upon the same problem while updating my code from tonic 0.3 to 0.4 and to tokio 1. It seems that examples do not contain use case where `type ListFeaturesStream = mpsc::Receiver<Result<Feature, Status>>;` is used like this.

**Comment by andresv** [comment]
Okay I learned something today.
So instead of this: https://github.com/hyperium/tonic/blob/master/examples/src/routeguide/server.rs#L39-L65
```rust
type ListFeaturesStream =
    Pin<Box<dyn Stream<Item = Result<Feature, Status>> + Send + Sync + 'static>>;

async fn list_features(
    &self,
    request: Request<Rectangle>,
) -> Result<Response<Self::ListFeaturesStream>, Status> {
    println!("ListFeatures = {:?}", request);

    let (tx, rx) = mpsc::channel(4);
    let features = self.features.clone();

    tokio::spawn(async move {
        for feature in &features[..] {
            if in_range(feature.location.as_ref().unwrap(), request.get_ref()) {
                println!("  => send {:?}", feature);
                tx.send(Ok(feature.clone())).await.unwrap();
            }
        }

        println!(" /// done sending");
    });

    Ok(Response::new(Box::pin(
        tokio_stream::wrappers::ReceiverStream::new(rx),
    )))
}
```

You can do this:

```rust
type ListFeaturesStream =
    tokio_stream::wrappers::ReceiverStream<Result<Feature, Status>>;

async fn list_features(
    &self,
    request: Request<Rectangle>,
) -> Result<Response<Self::ListFeaturesStream>, Status> {
    println!("ListFeatures = {:?}", request);

    let (tx, rx) = mpsc::channel(4);
    let features = self.features.clone();

    tokio::spawn(async move {
        for feature in &features[..] {
            if in_range(feature.location.as_ref().unwrap(), request.get_ref()) {
                println!("  => send {:?}", feature);
                tx.send(Ok(feature.clone())).await.unwrap();
            }
        }

        println!(" /// done sending");
    });

    Ok(Response::new(Box::pin(
        tokio_stream::wrappers::ReceiverStream::new(rx)
    )))
}
```

**Comment by rumanbsl** [comment]
https://github.com/rumanbsl/tonic-routeguide-code
I was solving the same, haha
