### ISSUE TITLE
Use tonic with hyperlocal

### ISSUE THREAD

**Issue by cemoktra** [hyperium/tonic#544]
Hello,

this is more like a question, is it possible to use tonic with hyperlocal, to support Unix sockets on a local environment for IPC?

**Comment by rdelfin** [comment]
There's already an example for how to use tonic with Unix sockets: https://github.com/hyperium/tonic/tree/master/examples/src/uds

**Comment by cemoktra** [comment]
Actually tried it today but i'm not able to make it work with tokio 1.0 and tonic 0.4. I changed `unix::UnixStream` because it wa snot found, then ending up in

```
.serve_with_incoming(incoming)
    |                              ^^^^^^^^ the trait `Connected` is not implemented for `tokio::net::UnixStream`
```

**Comment by rdelfin** [comment]
@cemoktra take a look further down in the example. They define the `unix` module further down (honestly, I made the same mistake and got extremely confused).
Relevant code: https://github.com/hyperium/tonic/blob/master/examples/src/uds/server.rs#L64-L108

**Comment by davidpdrsn** [comment]
@cemoktra I'm gonna close this for now. Feel free to re-open if you're still having issues.
