### ISSUE TITLE
example tower-client "buffer full; poll_ready must be called first"

### ISSUE THREAD

**Issue by smhmayboudi** [hyperium/tonic#545]
### Version

```bash
│   ├── tonic v0.4.0
├── tonic v0.4.0 (*)
├── tonic-health v0.3.0
│   └── tonic v0.4.0 (*)
│   └── tonic-build v0.4.0
└── tonic-build v0.4.0 (*)
```
### Platform

Darwin local.local 20.2.0 Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64 x86_64

### Description

I tried to run `cargo run --bin tower-client` and I got a panic.
```bash
thread 'main' panicked at 'buffer full; poll_ready must be called first', /Users/smhmayboudi/.cargo/registry/src/github.com-1ecc6299db9ec823/tower-0.4.3/src/buffer/service.rs:132:14
```

**Comment by davidpdrsn** [comment]
This is probably the same issue as https://github.com/tower-rs/tower/issues/547. That issue includes a fix.

**Comment by smhmayboudi** [comment]
Thanks. should I worry about "tower-server" as well. Since it is very similar to this case.
```rust
        let mut svc = self.inner.clone();

        Box::pin(async move {
            // Do async work here....

            svc.call(req).await
        })
```

**Comment by davidpdrsn** [comment]
Yes. That kind of usage of tower might panic. You're very welcome to submit a PR that fixes the examples 😊
