### ISSUE TITLE
how to generate target code

### ISSUE THREAD

**Issue by laik** [hyperium/tonic#562]
I hope to define the protocol in the project, and hope that the rs code of the generated mod will be quoted by other developers, how to do it

**Comment by davidpdrsn** [comment]
Sorry I don’t quite follow. Are you able to provide an example of some sort?

**Comment by laik** [comment]
> Sorry I don’t quite follow. Are you able to provide an example of some sort?

eg in golang, via the binary is used to generate code in the project, and then the project is quoted, but tonic uses the macro reference, which is not friendly to the code reference view when engineering a large number of grpc services.

**Comment by laik** [comment]
eg in go:
  protoc --go_out=. --go_opt=paths=source_relative \
    --go-grpc_out=. --go-grpc_opt=paths=source_relative \
    helloworld/helloworld.proto
If tonic can provide the generated code in the project instead of external code reference, it will be more suitable for developers

**Comment by davidpdrsn** [comment]
I don't understand what you mean by "and then the project is quoted". Are you saying you want the code generated by tonic to be put into actual files in the `src` directory so they can be checked in to version control?

> it will be more suitable for developers

We are all developers here 😅

**Comment by laik** [comment]
> I don't understand what you mean by "and then the project is quoted". Are you saying you want the code generated by tonic to be put into actual files in the `src` directory so they can be checked in to version control?
> 
> 
> 
> > it will be more suitable for developers
> 
> 
> 
> We are all developers here 😅

Sorry, there is something wrong with my description, I mean is that a crate or mod can be generated for better code reference。

**Comment by davidpdrsn** [comment]
The generated code is already public if you make a library crate so you should be able to use that from other crates.

**Comment by cetanu** [comment]
Correct me if I am wrong but the way I interpret the question is that he is asking where the generated code for the protocol buffers can be found.

The answer to which, is that they should be somewhere in the `target` directory, usually with names similar to the protocol buffers that they were generated from. From there, you could just copy them to your `src` directory...

Is that right? I hope so.

**Comment by davidpdrsn** [comment]
You are also able to set the [`out_dir`](https://docs.rs/tonic-build/0.4.2/tonic_build/struct.Builder.html#method.out_dir) in your `build.rs`.

@laik does that help?
