### ISSUE TITLE
add a way to get rpc method http path

### ISSUE THREAD

**Issue by Sherlock-Holo** [hyperium/tonic#565]
### Crates

tonic-build

### Motivation
I define an rpc service and some methods need timeout in 3s, some others timeout 10s, though I can use the `tokio::time::timeout` to do this job, but it may codes complex, so I try to do this with a middleware: it wraps the Channel and also implements the `Service`, but it will check the http path, if the path equals the 3s methods' path, it will return a 3s timeout future, others will return 10s timeout future

### Proposal
when tonic-build generate the .rs files, also generate some const &str which map to the rpc methods' path, for example I define a rpc
```protobuf
package proto;

service S {
    rpc Hello(Req) returns (Resp);
}
```
the tonic-build will generate a cosnt &str like `pub const proto_rpc_Hello: &str = "/proto.rpc/Hello"`

### Alternatives
without this feature, I still can write the middleware and compare the path with hardcode str, but I don't think it is a good idea.

**Comment by davidpdrsn** [comment]
I'm not quite sure how a `const &str` helps here. Changing the path would change the name of the constant and be a breaking change for any clients there might be. Why isn't a tower middleware sufficient?

**Comment by Sherlock-Holo** [comment]
so we need a better way to define the const str…

**Comment by davidpdrsn** [comment]
Sorry but I still don’t quite understand what the string is useful for. Can you show some example code where it’s used?

**Comment by Sherlock-Holo** [comment]
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=d4aa787b2f8d72dad1e1646409e72d63

the middleware saves the HashSet to check so we can check if the path should set a timeout, but now I don't have a good way to get the grpc method's http path to store it into the HashSet.
If the generated `.rs` file defines something the let me get the grpc method's http path easily, I won't need to read the generated `.rs` file to find out what the http path is

**Comment by LucioFranco** [comment]
I don't think this is really the correct way to go about it. This adds runtime overhead (via the mutex/synchronization) where adding the timeout at the callside on the future provides a static way to configure the timeouts. I also am not a huge fan of exposing more inner details of how the h2 -> gRPC protocol works (including full path etc). Currently, behind a trait we expose the service name because its required to provide a basic router which imo is a very important feature.

**Comment by davidpdrsn** [comment]
Think I'm going to close this for now. A tower middleware that matches on the request path and picks an appropriate timeout is probably a reasonable way to handle this. You're welcome to ask further questions in [our Discord](https://discord.gg/6yGkFeN) if you need more help.
