### ISSUE TITLE
Is it bad to re-repeatedly open a new client for every request?

### ISSUE THREAD

**Issue by vedantroy** [hyperium/tonic#567]
Due to some borrow checker shenanigans, I need to repeatedly `connect` to the server endpoint (I want to fetch some data on a background thread & add it to a struct, this requires cloning the `Client`, but the client is not clone-able). Is this bad for performance?

Edit:: Turns out the client is clone-able. Now I have 3 options:
1. create a new client each time
2. clone the client each time
3. have a separate background thread that runs the client (no clone or creating a new client)

I'm not sure if there's a big performance impact to cloning the client.

**Comment by davidpdrsn** [comment]
Cloning the client is totally fine. Its very cheap as it is basically just incrementing a reference count on an `Arc`.

Repeatedly creating new clients doesn't sound optimal.
