### ISSUE TITLE
possible to receive binary through tonic but deserialize in C++?

### ISSUE THREAD

**Issue by comicfans** [hyperium/tonic#568]
### Motivation

I hope to migrate our C++ server side code from grpc++ to tonic , due to that many C++ code directly use grpc generated struct definition , I'd like to keep the structure C++ as it is ,  instead of writing rust=>C++ struct conversion manually,
 I wonder if it is possible to only use tonic as transport layer to receive request binary (instead of using rust struct),  and deserialize binary in C++,  so I can throw grpc++ (and bunch of its dependencies) but still using c++ struct interface ?

**Comment by davidpdrsn** [comment]
You can use tonic without the prost generated types so in theory yeah this should be possible. However it is not something I've done myself.

**Comment by rapus95** [comment]
We're currently wondering the same for the language Julia because that lacks an up-to-date gRPC/HTTP/2 library. Hopefully we'll be able to link Tonic and StructTypes.jl/ProtoBuf.jl into something useful :D

**Comment by davidpdrsn** [comment]
I'm closing this. Feel free to re-open if you have concrete questions.
