### ISSUE TITLE
Tonic expected performance?

### ISSUE THREAD

**Issue by vedantroy** [hyperium/tonic#569]
I'm finding that it takes well over a minute to transfer data (a large string, around 0.1GB) from client to server, where both client/server are on my machine.

Is this expected performance? Am I doing something wrong?

**Comment by algermissen** [comment]
I have a similar question. I am using tonic-generated Google Cloud Datastore client and I am seeing constantly about 300ms read latency for a tiny JSON entity. Should I expect that from the current tonic implementation? Or can I assume it is fast and I should focus on other parts of my system?

This is my generating crate https://crates.io/crates/datastore_grpc

**Comment by cetanu** [comment]
That sounds pretty slow. Do you have some kind of setup you can share to reproduce the issue? (I'm not a contributor on this codebase btw, just curious + it would help)

**Comment by algermissen** [comment]
@cetanu Are you saying 6ms is pretty slow?

**Comment by cetanu** [comment]
> 
> 
> @cetanu Are you saying 6ms is pretty slow?

No 😆 the example in the issue authors post

**Comment by davidpdrsn** [comment]
@vedantroy are you able to provide more details? A reproducible example would be great.

**Comment by davidpdrsn** [comment]
I will close this for now. If someone can provide more details please do so 😊
