### ISSUE TITLE
Please cut a new release

### ISSUE THREAD

**Issue by lovesegfault** [hyperium/tonic#57]
I'm trying to use Tonic, but I keep hitting #43. I've confirmed that tagging master on Cargo.toml solves the issue.

Could a new release be cut?

**Comment by LucioFranco** [comment]
@lovesegfault yup, I can get one out tonight!

**Comment by LucioFranco** [comment]
Done! https://crates.io/crates/tonic/0.1.0-alpha.2

Let me know if you run into any issues!

**Comment by lovesegfault** [comment]
Thanks Lucio!
