### ISSUE TITLE
gRPC call hangs after receiving server response but before returning response to caller

### ISSUE THREAD

**Issue by mieubrisse** [hyperium/tonic#575]
### Version
```
│   └── tonic v0.4.0
│   └── tonic-build v0.4.0
└── tonic v0.4.0 (*)
```

### Platform

Running inside an `alpine:3.12` Docker container

### Description
I have a server exposing a Protobuf API method called `RegisterTestSetupCompletion`. 
I have a consumer, running inside a Docker container, that will call this method. I've generated a client for the Protobuf API using `tonic-build` like so:

```rust
    tonic_build::configure()
        .out_dir(&output_dirpath)
        .compile(&input_proto_filepaths, &[input_dirpath])
        .context("An error occurred generating the .proto files")?;
```

This results in a Rust function inside a `TestExecutionServiceClient` struct:

```rust
        #[doc = " Registers that the testsuite has completed test setup"]
        pub async fn register_test_setup_completion(
            &mut self,
            request: impl tonic::IntoRequest<()>,
        ) -> Result<tonic::Response<()>, tonic::Status> {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::new(
                    tonic::Code::Unknown,
                    format!("Service was not ready: {}", e.into()),
                )
            })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/api_container_api.TestExecutionService/RegisterTestSetupCompletion",
            );
            self.inner.unary(request.into_request(), path, codec).await
        }
```

The consumer constructs a `Channel` for talking to the server and connects it:

```rust
		let endpoint = Channel::from_shared(url)
			.context(format!("An error occurred creating the endpoint to Kurtosis API socket '{}'", &self.kurtosis_api_socket))?;

		// Sometimes the API container is still in the process of starting, so we retry the channel connection a few times
		let channel: Channel;
		let mut connection_attempts: u32 = 0;
		loop {
			if connection_attempts >= MAX_CONNECTION_ATTEMPTS {
				return Err(
					anyhow!(
						"Failed to connect to API container, even after {} retries spaced {}ms apart",
						MAX_CONNECTION_ATTEMPTS,
						TIME_BETWEEN_CONNECTION_RETRIES.as_millis(),
					)
				);
			}
			let channel_or_err = block_on(endpoint.connect());
			match channel_or_err {
				Ok(returned_channel) => {
					channel = returned_channel;
					break;
				}
				Err(err) => {
					debug!(
						"The following error occurred connecting to the API container; retrying in {}ms: {}", 
						TIME_BETWEEN_CONNECTION_RETRIES.as_millis(),
						err.to_string()
					);
				}
			}
			sleep(TIME_BETWEEN_CONNECTION_RETRIES);
			connection_attempts += 1;
		}
```

then creates an instance of the `TestExecutionServiceClient` struct to do the following:

```rust
        let mut registration_client = TestExecutionServiceClient::new(channel.clone());

        // A call to registration_client.some_other_function that succeeds
        // Some work here that takes ~40 seconds

        debug!("Registering test setup completion...");
		block_on(registration_client.register_test_setup_completion(()))
			.context("An error occurred registering the test setup completion with the API container")?;
        debug!("Test setup completion registered");
        info!("Test network set up");
```

The oddity is that the consumer's `registration_client.register_test_setup_completion` never returns - `Registering test setup completion...` is printed, but `Test setup completion registered` is not - it just hangs there. It's not a problem on the server side, because the corresponding server-side both receives the `register_test_setup_completion` call, and exits; it seems to be after the consumer's gRPC client receives the response from the server but before `register_test_setup_completion` returns back to the caller.

I grabbed all the logs from `Registering test setup completion...` onwards ( 
[after-setup-completion-call.log](https://github.com/hyperium/tonic/files/6094125/after-setup-completion-call.log)
 ), but I've been staring at it for hours and can't make head nor tail of what's going on. The very last logline is:

```
22:48:27 [TRACE] (3) h2::proto::streams::streams: [/home/rust/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.3.0/src/proto/streams/streams.rs:1280] drop_stream_ref; stream=Stream { id: StreamId(71), state: State { inner: Closed(EndStream) }, is_counted: false, ref_count: 2, next_pending_send: None, is_pending_send: false, send_flow: FlowControl { window_size: Window(65530), available: Window(0) }, requested_send_capacity: 0, buffered_send_data: 0, send_task: Some(Waker { data: 0x254c5c0, vtable: 0xe3f0d8 }), pending_send: Deque { indices: None }, next_pending_send_capacity: None, is_pending_send_capacity: false, send_capacity_inc: true, next_open: None, is_pending_open: false, is_pending_push: false, next_pending_accept: None, is_pending_accept: false, recv_flow: FlowControl { window_size: Window(2097147), available: Window(2097147) }, in_flight_recv_data: 5, next_window_update: None, is_pending_window_update: false, reset_at: None, next_reset_expire: None, pending_recv: Deque { indices: Some(Indices { head: 1, tail: 0 }) }, recv_task: None, pending_push_promises: Queue { indices: None, _p: PhantomData }, content_length: Omitted } 
22:48:27 [TRACE] (3) h2::proto::streams::counts: [/home/rust/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.3.0/src/proto/streams/counts.rs:136] transition_after; stream=StreamId(71); state=State { inner: Closed(EndStream) }; is_closed=true; pending_send_empty=true; buffered_send_data=0; num_recv=0; num_send=0 
```

This almost seems like the `Channel`/`tower` instance inside the `TestExecutionServiceClient` is getting stuck somehow, maybe due to the 40s pause between usage?

**Comment by mieubrisse** [comment]
I just added debugging to see exactly which line in the generated function it's getting stuck at, and it's this last one:
```
self.inner.unary(request.into_request(), path, codec).await
```

**Comment by mieubrisse** [comment]
I just read up on HTTP2 and stepped through every line in the logfile above - it's still not clear to me why this is hanging, as the behaviour seems to be what I'd expect:

1. The connection (which had sat idle for the 40s) is successfully resumed
2. The consumer sends HEADERS and DATA frames on Stream 71
3. The stream transitions to the HalfClosed state, indicating that the consumer is only receiving data now
4. The server pushes several HEADER and DATA frames on Stream 71
5. The server pushes a HEADER frame with `flags: (0x5: END_HEADERS | END_STREAM)`, indicating the the stream should be closed
6. The stream transitions to Closed state
7. The consumer client calls `drop_stream_ref`, presumably trying to free client memory
8. The `transition_after` line is printed that indicates that Stream 71 is closed:
    ```
    transition_after; stream=StreamId(71); state=State { inner: Closed(EndStream) }; is_closed=true; pending_send_empty=true; buffered_send_data=0; num_recv=0; num_send=0
    ```
9. Yet still, the `self.inner.unary(request.into_request(), path, codec).await` line doesn't complete

Nothing _seems_ out of the ordinary, so it's not clear to me why

**Comment by davidpdrsn** [comment]
Sounds strange indeed 🤔 I'm wondering if the bug could be in h2 and not tonic. 

Are you able to provide a reproduction example that can easily be run? Then I will take a look.

**Comment by mieubrisse** [comment]
Thanks for getting back @davidpdrsn ! I have the consistent repro, but unfortunately it's pretty in-depth. I'll try to see if I can get a simpler repro (I'm guessing it has to do with the dead connection). I also built a local version of `tonic` with some debugging lines, and the exact error seems to be this: https://github.com/hyperium/tonic/blob/fdda5ae26ace4706cb8faf56ccd35513b5de26c5/tonic/src/transport/channel/mod.rs#L192 The `await` that sticks it is this: https://github.com/hyperium/tonic/blob/f58fcf31d1b725416b7f457e2d12e6aaa7e6f327/tonic/src/client/grpc.rs#L185

**Comment by davidpdrsn** [comment]
Hm this sounds similar to https://github.com/hyperium/tonic/issues/515. Could that be it? Not sure there is a fix for it though. I remember @LucioFranco and @seanmonstar talking about it in Discord some weeks ago but don't remember the conclusion.

**Comment by mieubrisse** [comment]
That sounds _very_ similar - I'm also using `grpc-go` on the server side. I'd be keen to hear if @LucioFranco or @seanmonstar found a workaround; nothing I've done has been able to unblock it so far.

**Comment by mieubrisse** [comment]
Just tried to get a minimal repro by simulating that same 40s delay, but no luck - it's caused by something that's not just the delay.

**Comment by mieubrisse** [comment]
Closing the loop for posterity - the ultimate issue was the same as https://github.com/seanmonstar/reqwest/issues/1215 : because I'm a Rust noob I was intermixing `futures::executors::block_on` with #[tokio::main] on my main function, which was causing deadlocks as described by @seanmonstar here: https://github.com/seanmonstar/reqwest/issues/1215#issuecomment-796927554 . I solved this by creating a Tokio runtime via Runtime::new() as close to the async calls as possible, and using runtime.block_on() to force synchronicity on async functions.
