### ISSUE TITLE
Re-export prost Config

### ISSUE THREAD

**Issue by fulmicoton** [hyperium/tonic#585]
## Feature Request

Re-export `prost_build::Config` as `tonic_build::ProstConfig`.

### Crates

tonic_build

### Motivation

The .build_with_config(...) requires passing a prost Config object, but this type is coming from the prost_build dependency.
To use it, clients of tonic_build need to add a dependency to prost_build. Even worse, they need to somehow ensure that
their version is the same as tonic_build to avoid dependency hell, and get seemigly cryptic messages.

### Proposal

Simply re-export prost::Config in tonic_build, maybe with the alias ProstConfig.

### Alternatives

- Expose the entire prost_build deps
- Use a wrapper.

**Comment by davidpdrsn** [comment]
I'm generally not a fan of re-exporting stuff from other crates. That would mean a breaking change in `prost-build` would become a breaking change in tonic as well. I guess since tonic relies heavily on prost that it might be a problem regardless but this feels like it only makes it worse.

It also doesn't solve the version mismatches as users with incorrect versions specified elsewhere would get both versions included and probably still get confusing error messages.

**Comment by fulmicoton** [comment]
> It also doesn't solve the version mismatches as users with incorrect versions specified elsewhere would get both versions included and probably still get confusing error messages.

It solves the following problem:
Let's say I depend on tonic and OtherCrateLikeTonic.
- Both tonic and OtherCrateLikeTonic depend on a different version of prost-build.
- Both tonic and OtherCrateLikeTonic require to pass prost structs to their API but do not re-export these symbols. 
In the current situation, there are no way to get my project to compile.

With a reexport on either OtherCrateLikeTonic or tonic, one could use the reexport to build the right version of the struct.
I understand that re-exports are not ideal. Another popular solution is to expose a tonic specific ProstConfig struct, that tonic will convert to a prost Config.

**Comment by fulmicoton** [comment]
(for full disclosure ... This is not a blocking issue for me.)

**Comment by davidpdrsn** [comment]
I personally don't think we should do this. I have encountered similar problems myself but they are rare. It is also not clear where to draw the line. Tonic also uses things like `futures::Stream` in its public API. Does that mean we should re-export `futures` as well? Probably not.

Feel free to re-open if you want to discuss this further.
