### ISSUE TITLE
Suggestion: Allow users to handle transport errors differently from app errors

### ISSUE THREAD

**Issue by danielzfranklin** [hyperium/tonic#587]
## Feature Request

Thank you for building tonic, it's been great using it so far!

### Motivation

I want to have clients gracefully handle servers throwing errors but quit on servers disappearing, but per #222 tonic handles this by emitting continual Statuses of type Unknown and message "h2 protocol error: broken pipe". I've seen others handle this by parsing the message string, but that isn't stable.

### Proposal

I propose implementing Error for Status.

If that Status was sent by a server/client, the source field is a zero sized marker struct called something like GrpcError. While None would be more correct, this allows users to have code that handles only this case in a forwards-compatible way.

Otherwise, the source field is set to the originating error, if one exists. For example, it might be set to a hyper error.

### Alternatives

The way to solve this that feels most in line with the rust ecosystem to me would be for user-defined methods to return `Result<_, Status>` and for the tonic methods that remotely call those user defined methods to return `Result<_, TonicError>` where `TonicError` has members `Transport`, `Status`, etc which set their source field to the appropriate error.

However, this would be a significant breaking change, and I don't think the benefits merit that

Another alternative is to not implement Error but still add a source field. 

I'm open to working on a PR for this if it's something you think makes sense.

**Comment by davidpdrsn** [comment]
Do you think this would be covered by https://github.com/hyperium/tonic/pull/612?

**Comment by danielzfranklin** [comment]
I think so. With that change the API is "if the Status has a source it isn't application-level"? That solves what I was talking about, although it is a little non-intuitive.
