### ISSUE TITLE
Change Status.details to Any

### ISSUE THREAD

**Issue by danielzfranklin** [hyperium/tonic#589]
### Motivation

I'd like to be able to act based on the details field of a Status, which is an Any.

### Proposal

Prost [allows parsing Any's](https://github.com/danburkert/prost/issues/299) but doing so requires both the type url and bytes. I propose changing the details field on Status to [Any](https://docs.rs/prost-types/0.7.0/prost_types/struct.Any.html)

If this sounds reasonable I'm happy to make a PR.

**Comment by davidpdrsn** [comment]
Does prost actually support this? [The issue](https://github.com/danburkert/prost/issues/299) you're linking to is still open.

**Comment by danielzfranklin** [comment]
You're right, I misunderstood
