### ISSUE TITLE
Can we skip rustfmt because it is not available in beta channel for Raspberry Pi ARMv7

### ISSUE THREAD

**Issue by kevingzhang** [hyperium/tonic#59]
### Motivation
I am trying to run tonic on Raspberry Pi. It failed first at 
rustup component add rustfmt --toolchain beta
I know it runs very well on my Mac, but just not working on Raspberry Pi because it is using Armv7 and the rustfmt is not ready for Armv7 beta yet. 

If I try to ignore it but I had a hard stop when building...

Caused by:
  process didn't exit successfully: `/home/pi/github/trust-engine/docker-api/target/debug/build/docker-api-f5114b92b0e93bfc/build-script-build` (exit code: 101)
--- stdout
out: Output { status: ExitStatus(ExitStatus(256)), stdout: "", stderr: "error: \'rustfmt\' is not installed for the toolchain \'beta-armv7-unknown-linux-gnueabihf\'\nTo install, run `rustup component add rustfmt --toolchain beta-armv7-unknown-linux-gnueabihf`\n" }

--- stderr
thread 'main' panicked at 'assertion failed: out.status.success()', /home/pi/github/tonic/tonic-build/src/lib.rs:185:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

### Proposal

I am not quite sure if rustfmt is a must-have in building tonic. If possible, do we have a walk around?

### Alternatives

I am currently working on the project on RaspBerry Pi. If we do not have a solution on this, I have to give up the Tonic and back to Hyper. I like Tonic so much, and hope we can find a solution soon.

**Comment by kevingzhang** [comment]
BTW, Tower-gRPC compile and works fine. since it doesn't require rustfmt. 
so the worst case I can use Tower-gRPC instead going all the way back to Hyper. :)

**Comment by rlabrecque** [comment]
Hey @kevingzhang, rustfmt can be disabled with a feature flag on tonic-build. You can turn it off like so:
```
[build-dependencies]
tonic-build = { git = "https://github.com/hyperium/tonic", default-features = false, features = ["transport"] }
```

**Comment by kevingzhang** [comment]
thanks, it works !!

**Comment by xmclark** [comment]
Alternatively, can tonic import rustfmt as a library and do the text processing at string-build-time instead of calling the external cli tool? Maybe that has tradeoffs, but at least then consumers of this library who do not want or cannot install rustfmt can get nice error messages.

**Comment by LucioFranco** [comment]
@xmclark last I checked that was not possible, or I couldn't figure it out. If someone could figure that out that would be amazing!

**Comment by davidgraeff** [comment]
I have done that in another crate of mine.

https://github.com/davidgraeff/braintree-payment-graphql-rs/blob/master/braintree-queries-generator/src/generate.rs#L10

```rust
#[cfg(feature = "rustfmt")]
fn format(input_rust_code: String) -> Option<String> {
    use rustfmt_nightly::{Config, Input, Session};

    let mut config = Config::default();

    config.set().emit_mode(rustfmt_nightly::EmitMode::Stdout);
    config.set().verbose(rustfmt_nightly::Verbosity::Quiet);

    let mut out = Vec::with_capacity(input_rust_code.len() * 2);

    let r = Session::new(config, Some(&mut out)).format(Input::Text(input_rust_code));
    match r {
        Err(e) => {
            format_err!("rustfmt error: {:?}", e);
            None
        }
        _ => match out.len() {
            0 => None,
            // Unwrap should be safe here, rustfmt generates utf8 only
            _ => Some(String::from_utf8(out).unwrap()),
        },
    }
}
```

**Comment by LucioFranco** [comment]
@davidgraeff can this code run on stable?

**Comment by davidgraeff** [comment]
To be honest, I don't know. Because of the current async situation in the rust ecosystem I'm on rust nightly. I haven't found a toolchain file in their repo, so I assume it works on stable, but also haven't checked their dependencies.

**Comment by LucioFranco** [comment]
Yeah, unfortunately, this depends on unstable nightly features :(

```
error[E0554]: `#![feature]` may not be used on the stable release channel
   --> /Users/lucio/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-ap-graphviz-606.0.0/lib.rs:277:1
    |
277 | #![feature(rustc_private, nll)]
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: `#![feature]` may not be used on the stable release channel
  --> /Users/lucio/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-0.6.10/lib.rs:33:32
   |
33 | #![cfg_attr(feature = "union", feature(untagged_unions))]
   |                                ^^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: `#![feature]` may not be used on the stable release channel
  --> /Users/lucio/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-0.6.10/lib.rs:35:37
   |
35 | #![cfg_attr(feature = "may_dangle", feature(dropck_eyepatch))]
   |                                     ^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error
```

**Comment by sprhawk** [comment]
I encounter a same situation. 
I'm using yocto with meta-rust-bin to build rust application. a rustfmt doesn't exist in meta-rust-bin. 
Although I can disable rustfmt feature for yocto build, but it will also disabled in normal development environment.

I think there is no way to set to use "rustfmt" in development environment, and no "rustfmt" when build for yocto ( build script is built for HOST same like the development environment )

**Comment by LucioFranco** [comment]
I am not familiar with yocto but is it possible to pass a feature flag to the create that contains tonic build? that way you can do something like:

```rust
[features]
fmt = ["tonic-build/rustfmt"]
```

then you can build it with

```rust
cargo build --features fmt
```

**Comment by sprhawk** [comment]
> I am not familiar with yocto but is it possible to pass a feature flag to the create that contains tonic build? that way you can do something like:
> 
> ```rust
> [features]
> fmt = ["tonic-build/rustfmt"]
> ```
> 
> then you can build it with
> 
> ```rust
> cargo build --features fmt
> ```

I mean meta-rust-bin doesn't include a rustfmt, so I had to disable fmt feature, not enable it.

**Comment by hechaoli** [comment]
> > I am not familiar with yocto but is it possible to pass a feature flag to the create that contains tonic build? that way you can do something like:
> > ```rust
> > [features]
> > fmt = ["tonic-build/rustfmt"]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > then you can build it with
> > ```rust
> > cargo build --features fmt
> > ```
> 
> I mean meta-rust-bin doesn't include a rustfmt, so I had to disable fmt feature, not enable it.

I encountered the same issue with yocto. However, I'm using `meta-rust` which should have `rustfmt`. Yet somehow it complains about `rustfmt` missing. I couldn't figure out a way to configure yocto to work. Eventually, I found that it works if you just disable format using `configure`. That is, change `build.rs` to the following instead of using `tonic_build::compile_protos("proto/helloworld.proto")?;` like in the example.
 
```
fn main() -> Result<(), Box<dyn std::error::Error>> {
   tonic_build::configure()
        .format(false)
        .compile(
            &["proto/helloworld.proto"],
            &["proto/"],
        )?;
   Ok(())
}
```

The side-effect is of course all generated code in one line.
