### ISSUE TITLE
Suggestion: Map oneof to struct-like enum

### ISSUE THREAD

**Issue by danielzfranklin** [hyperium/tonic#592]
## Feature Request

First off, I want to say I'm loving using tonic. Thank you!

### Motivation

Currently, it is more verbose than necessary to generate and match on `oneof`s because each item gets a generated enum member and a generated struct. For example:

```proto
message Msg {
   oneof event {
       Connect connect = 1;
       Disconnect disconnect = 2;
   }
   
   message Connect {
     uint32 id = 1;
   }
   message Disconnect {
     uint32 id = 1;
   }
}
```

```rust
mod event {
  enum Event {
    Connect(Connect),
    Disconnect(Disconnect),
  }

  struct Connect {
    id: u32,
  }

  struct Disconnect {
    id: u32,
  }
}
```

### Proposal

I propose `oneof`s instead translate translate to struct-like enums

```rust
mod event {
  enum Event {
    Connect {
      id: u32,
    },
    Disconnect {
      id: u32,
    }
  }
}
```

### Alternatives

Doing nothing is a reasonable alternative, this isn't a major issue.

I'm interested in working on implementing this if it's something you'd accept.

**Comment by chemicstry** [comment]
This would be problematic if the oneof messages are also used elsewhere, which is a common case. Then you would still have to generate a struct for the message and it would be incompatible with the enum type.

**Comment by danielzfranklin** [comment]
You're right, I didn't think of that. Oh well.

**Comment by davidpdrsn** [comment]
What I usually do is define From implementations to easily convert the structs into the corresponding enum variant.
