### ISSUE TITLE
Waiting for server bootup

### ISSUE THREAD

**Issue by chemicstry** [hyperium/tonic#596]
Thanks for the great project!

I have been using this library with great success, however, I have a usecase which I don't think is covered by the current API.
I'm doing integration tests for my gRPC service, where I launch the server, then connect to it with a client and assert the response. Simplified code:
```rust
    #[tokio::test]
    async fn service_test() {
        // Start server
        tokio::spawn(async move {
            Server::builder()
                .add_service(...)
                .serve("[::1]:50051".parse().unwrap())
                .await
                .unwrap();
        });

        // How to replace this sleep with a signal once server is ready?
        tokio::time::sleep(Duration::from_millis(500)).await;

        // Connect to the service as client
        let mut client = RPCServiceClient::connect("http://[::1]:50051")
            .await
            .expect("Failed to connect to gRPC server");

        let response = client.rpc_method(...).await.expect("Request failed");
        assert!(...);
    }
```

The problem is that if I don't include a delay between server and client, the test fails with `Connection refused`, because the server was not ready yet. Use of delay is not ideal because it can still fail due to server lag and slows down tests in general. Is there a way to somehow wait until server is ready?

**Comment by adamrk** [comment]
I've been doing the same (although waiting only 1ms seems to be enough in my tests).

**Comment by davidpdrsn** [comment]
We actually do the same thing in tonic's test suite but yeah it is kinda annoying.

I haven't tested this (on my phone) but I'm thinking it's possible to use [serve_with_incoming](https://docs.rs/tonic/0.4.1/tonic/transport/server/struct.Router.html#method.serve_with_incoming) to create the tcp listener up front and pass it to the async task. That should remove the need for a sleep and it's what I do with hyper in another project. Should also make it possible to use ephemeral ports.

I'll try it later today unless someone beats me to it.

**Comment by chemicstry** [comment]
> @chemicstry did `serve_with_incoming` work for you?

I have not tried it yet, but the idea is nice. I will share my findings once I have time to test this.

**Comment by chemicstry** [comment]
Reporting to tell that `serve_with_incoming` works! There is a bit of boilerplate to get the ephemeral ports to work.

```rust
    #[tokio::test]
    async fn service_test() {
        let socket = tokio::net::TcpSocket::new_v6().unwrap();
        socket.bind("[::1]:0".parse().unwrap()).unwrap();
        let port = socket.local_addr().unwrap().port();
        let listener = tokio_stream::wrappers::TcpListenerStream::new(socket.listen(1).unwrap());

        // Start server
        tokio::spawn(async move {
            Server::builder()
                .add_service(...)
                .serve_with_incoming(listener)
                .await
                .unwrap();
        });

        // Connect to the service as client
        let mut client = RPCServiceClient::connect(format!("http://[::1]:{}", port))
            .await
            .expect("Failed to connect to gRPC server");

        let response = client.rpc_method(...).await.expect("Request failed");
        assert!(...);
    }
```
