### ISSUE TITLE
client streaming 

### ISSUE THREAD

**Issue by nada-abdelhalim** [hyperium/tonic#601]
I was working with an application that required having bidirectional streaming and I was wondering if there are any way that would enable me to send message then wait for its response without having to prepare all the message queue before hand

**Comment by davidpdrsn** [comment]
The the method on the generated client will look something like this:

```rust
pub async fn bidirectional_stream(
    &mut self, 
    request: impl IntoStreamingRequest<Message = BidirectionalStreamRequest>
) -> Result<Response<Streaming<BidirectionalStreamReply>>, Status>
```

Where [`IntoStreamingRequest`](https://docs.rs/tonic/0.4.1/tonic/trait.IntoStreamingRequest.html) is implemented  for `T: Stream<Item = Message>`. If you don't know all the message upfront you'll normally use [`ReceiverStream`](https://docs.rs/tokio-stream/0.1.5/tokio_stream/wrappers/struct.ReceiverStream.html) to turn a [`tokio::sync::mpsc::Recevier`](https://docs.rs/tokio/1.4.0/tokio/sync/mpsc/struct.Receiver.html) into a [`Stream`](https://docs.rs/futures/0.3.14/futures/stream/trait.Stream.html). That allows you to send messages with the corresponding `Sender` half whenever the server has something to send.

Waiting for responses from the server will require manually coordinating the two streams.

Does that answer your question?

**Comment by nada-abdelhalim** [comment]
I'm not sure, 
what I meant was that my application at the client side have to wait for the next client message to be prepared, after a response for the first client message is attained from the server.
how can I manipulate the request sent to the bidirectional function after sending the first client message in order to put the second client message upon ready in the queue

**Comment by davidpdrsn** [comment]
I don't understand what you mean. Do you mean that you want to wait for the server to send a message after the client sends something? If so that is done by sending a message on the client to server stream and then calling [`Streaming::message`](https://docs.rs/tonic/0.4.1/tonic/struct.Streaming.html). You get a `Streaming` when setting up the bidirectional stream.

**Comment by nada-abdelhalim** [comment]
Not exactly my point,
at the client side I'm currently using `futures::stream::iter` to pass a vector of client messages that I would want to push some messages to after I get the response from the server to the first client message because my second message depends on the server response.
However I can't push new messages to the streaming request that I created after sending it to the bidirectional function

**Comment by nada-abdelhalim** [comment]
shortly if I am using a code like this how can I avoid prefilling the vector and be able to append messages to it after getting server responses
```
let channel = tonic::transport::Channel::from_static("http://[::1]:50051")
            .connect()
            .await?;
        let mut client = SayClient::new(channel);
    // creating a client
        let request = tonic::Request::new(iter(vec![
            SayRequest {
                name: String::from("a"),
            },
            SayRequest {
                name: String::from("b"),
            },
            SayRequest {
                name: String::from("c"),
            },
        ]));
    // calling rpc
        let mut response = client.bidirectional(request).await?.into_inner();
    // listening on the response stream
        while let Some(res) = response.message().await? {
            println!("NOTE = {:?}", res);
        }
        ```

**Comment by davidpdrsn** [comment]
You should be able to do what I was trying to say in my [previous message](https://github.com/hyperium/tonic/issues/601#issuecomment-817346943). Instead of using `futures::stream::iter` use [`ReceiverStream`](https://docs.rs/tokio-stream/0.1.5/tokio_stream/wrappers/struct.ReceiverStream.html). Messages can be put into the stream using the corresponding `Sender` you get when creating the `Receiver`.

Something like this (just off the top of my head and not tested):

```rust
// create the channel
let (tx, rx) = tokio::sync::mpsc::channel(1024);

// setup the stream
let stream = ReceiverStream::new(rx);
let request = tonic::Request::new(stream);
let mut response = client.bidirectional(request).await?.into_inner();

// send some messages
tx.send(SayRequest { name: "a".to_string() }).await?;
tx.send(SayRequest { name: "b".to_string() }).await?;

// wait for a response
while let Some(msg) = response.message().await? {
    dbg!(msg);
}

// send some more messages
tx.send(SayRequest { name: "c".to_string() }).await?;
```

**Comment by nada-abdelhalim** [comment]
the line 
```
let stream = ReceiverStream::new(rx);
```
throws this error
expected struct `tokio::sync::mpsc::bounded::Receiver`, found struct `tokio::sync::mpsc::Receiver` 

I believe that `tokio::sync::mpsc::Receiver`  is already a bounded reciever

**Comment by davidpdrsn** [comment]
Are you pulling in two versions of tokio?

This works for me

```rust
fn main() {
    let (tx, rx) = tokio::sync::mpsc::channel::<()>(1024);
    let stream = tokio_stream::wrappers::ReceiverStream::new(rx);

    // test that `stream` actually implements `Stream`
    assert_is_stream(stream);
}

fn assert_is_stream<T: futures::Stream>(_: T) {}
```

If not please share more of your code.

**Comment by nada-abdelhalim** [comment]
I'm using
    tokio = {version="0.2.18",features = ["stream", "macros"]}
    tokio-stream = "0.1.5"

**Comment by davidpdrsn** [comment]
tokio-stream depends on tokio 1.x so you are pulling in both tokio 0.2 and 1. Are you able to update to tokio 1?

You can also run `cargo tree -i tokio` to see exactly which crates depends on tokio. That'll tell you if you're using two different versions.

**Comment by nada-abdelhalim** [comment]
whenever I edit to the tokio 1.4.0 I can't find stream among the features and I get this error as a result
the trait `futures::Stream` is not implemented for `tokio::sync::mpsc::Receiver<Result<S
erverMessage, tonic::Status>>`

**Comment by davidpdrsn** [comment]
That is what `tokio_stream::wrappers::ReceiverStream` is for. Its a wrapper that turns a `Receiver` into a `Stream.
