### ISSUE TITLE
Achieving better thoughput with tonic clients

### ISSUE THREAD

**Issue by yqmmm** [hyperium/tonic#607]
### Version

0.4.1

### Platform

Linux 4.15.0

### Crates

tonic

### Description

I was trying to do some throughput benchmarking with tonic. The numbers are not good in the beginning, around 30k QPS with 3 servers and 1 client.

Later I found out (from this helpful comment: https://github.com/hyperium/tonic/issues/285#issuecomment-595880400) that you can achieve better performance by opening multiple channels and load balancing between them. On the client, I open 5 channels to each server and achieved around 170k QPS, which is pretty satisfying for me.

-------

So I have two questions:

First, is there anything we can do to improve this? I am not familiar with the codebase, but a tonic channel seems to use `tower:buffer:Buffer` underneath. It seems like that it has a `bound` parameter we could set.  Is this related to throughput performance? The best behavior should be to achieve as much throughput as possible with a single channel.

Second, should we explain this with better documentation? From the original documentation, all I could know is that I could just clone the client or channel to do concurrent requests. But to achieve maximum throughput, I will have to clone multiple clients or channels. Maybe this can be documented better?

**Comment by davidpdrsn** [comment]
> First, is there anything we can do to improve this? I am not familiar with the codebase, but a tonic channel seems to use tower:buffer:Buffer underneath. It seems like that it has a bound parameter we could set. Is this related to throughput performance?

`Buffer` works by spawning an async task and sending it requests via an async mpsc channel. The capacity of that channel is `Buffer`'s capacity. But its not the max number of in-flights requests or something like that (I thought that at first). Once the background service has received a request and produced a response future the channel capacity is freed and the future can run asynchronously.

If instead of opening 5 channels you `clone` the same channel 5 times do you get similar numbers?

**Comment by yqmmm** [comment]
Hey @davidpdrsn, thanks for your reply.

I tried `clone` the same channel 5 times. The throughput is the same as a single channel, lower than that of load balancing between multiple new channels.

My guess is that a channel represents an HTTP2 connection or TCP connection, and a single such connection will become a bottleneck? Maybe I should look into the codebase more.

Also, my machines (the 1 client and 3 servers) are 48-cores, so that may have something to do with a single channel becoming a bottleneck.

**Comment by yqmmm** [comment]
Interesting. This issue from gRPC C++ seems similar

https://github.com/grpc/grpc/issues/19731#issuecomment-514729480
