### ISSUE TITLE
Broken Pipe With Unix Socket

### ISSUE THREAD

**Issue by theduke** [hyperium/tonic#609]
### Version

tonic `0.4.2`

### Platform

Linux

### Description

I'm trying to implement a Kubernetes `CSI` driver, which communicates over Unix sockets.

I'm running into a situation where the server properly handles one request, but then fails with a `connection error: Broken pipe (os error 32)`.

See both server and (grpc-go) client logs below.

Not sure if this is more of a hyper issue or a unix socket issue, but I'm not sure how to proceed debugging here.

(I'm using the  code from the unix socket example)

The most interesting Kubelet log is:

```
Apr 19 13:04:29 kind-control-plane kubelet[646]: I0419 13:04:29.718951     646 clientconn.go:948] ClientConn switching balancer to "pick_first"
Apr 19 13:04:29 kind-control-plane kubelet[646]: I0419 13:04:29.718980     646 clientconn.go:897] blockingPicker: the picked transport is not ready, loop back to repick
```

<details>
<summary>Kubelet Server Log</summary>
<pre>
Apr 19 12:58:28 kind-control-plane kubelet[646]: I0419 12:58:28.676540     646 operation_generator.go:181] parsed scheme: ""
Apr 19 12:58:28 kind-control-plane kubelet[646]: I0419 12:58:28.676563     646 operation_generator.go:181] scheme "" not registered, fallback to default scheme
Apr 19 12:58:28 kind-control-plane kubelet[646]: I0419 12:58:28.676585     646 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{/var/lib/kubelet/plugins_registry/cc.foundational.omni-csi-reg.sock  <nil> 0 <nil>}] <nil> <nil>}
Apr 19 12:58:28 kind-control-plane kubelet[646]: I0419 12:58:28.676596     646 clientconn.go:948] ClientConn switching balancer to "pick_first"
Apr 19 12:58:28 kind-control-plane kubelet[646]: I0419 12:58:28.677441     646 csi_plugin.go:100] kubernetes.io/csi: Trying to validate a new CSI Driver with name: cc.foundational.omni-csi endpoint: /var/lib/kubelet/plugins/omni-csi.foundational.cc/csi.sock versions: 1.0.0
Apr 19 12:58:28 kind-control-plane kubelet[646]: I0419 12:58:28.677470     646 csi_plugin.go:113] kubernetes.io/csi: Register new plugin with name: cc.foundational.omni-csi at endpoint: /var/lib/kubelet/plugins/omni-csi.foundational.cc/csi.sock
Apr 19 12:58:28 kind-control-plane kubelet[646]: I0419 12:58:28.677504     646 clientconn.go:106] parsed scheme: ""
Apr 19 12:58:28 kind-control-plane kubelet[646]: I0419 12:58:28.677514     646 clientconn.go:106] scheme "" not registered, fallback to default scheme
Apr 19 12:58:28 kind-control-plane kubelet[646]: I0419 12:58:28.677563     646 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{/var/lib/kubelet/plugins/omni-csi.foundational.cc/csi.sock  <nil> 0 <nil>}] <nil> <nil>}
Apr 19 12:58:28 kind-control-plane kubelet[646]: I0419 12:58:28.677573     646 clientconn.go:948] ClientConn switching balancer to "pick_first"
I0419 13:04:29.718980     646 clientconn.go:897] blockingPicker: the picked transport is not ready, loop back to repick

</pre>
</details>

<details>
<summary>Tonic Server Log Excerpt (full below)</summary>
<pre>
Apr 19 15:37:26.987 DEBUG server_handshake{io=hyper::common::io::rewind::Rewind<tonic::transport::service::io::ServerIo>}:Connection{peer=Server}:poll:FramedWrite::buffer{frame=Headers { stream_id: StreamId(1), flags: (0x5: END_HEADERS | END_STREAM) }}: h2::codec::framed_write: send frame=Headers { stream_id: StreamId(1), flags: (0x5: END_HEADERS | END_STREAM) }
Apr 19 15:37:26.987 TRACE server_handshake{io=hyper::common::io::rewind::Rewind<tonic::transport::service::io::ServerIo>}:Connection{peer=Server}:poll:FramedWrite::buffer{frame=Headers { stream_id: StreamId(1), flags: (0x5: END_HEADERS | END_STREAM) }}:hpack::encode: h2::hpack::encoder: encoding at pos=82
Apr 19 15:37:26.987 TRACE server_handshake{io=hyper::common::io::rewind::Rewind<tonic::transport::service::io::ServerIo>}:Connection{peer=Server}:poll: h2::proto::streams::prioritize: schedule_pending_open
Apr 19 15:37:26.988 TRACE server_handshake{io=hyper::common::io::rewind::Rewind<tonic::transport::service::io::ServerIo>}:Connection{peer=Server}:poll:FramedWrite::flush: h2::codec::framed_write: queued_data_frame=false
Apr 19 15:37:26.988 TRACE server_handshake{io=hyper::common::io::rewind::Rewind<tonic::transport::service::io::ServerIo>}:Connection{peer=Server}:poll:FramedWrite::flush: h2::codec::framed_write: flushing buffer
Apr 19 15:37:26.988 TRACE server_handshake{io=hyper::common::io::rewind::Rewind<tonic::transport::service::io::ServerIo>}:Connection{peer=Server}:poll: h2::proto::connection: connection.state=Open
Apr 19 15:37:26.988 TRACE server_handshake{io=hyper::common::io::rewind::Rewind<tonic::transport::service::io::ServerIo>}:Connection{peer=Server}:poll:FramedRead::poll_next: h2::codec::framed_read: poll
Apr 19 15:37:26.988 TRACE server_handshake{io=hyper::common::io::rewind::Rewind<tonic::transport::service::io::ServerIo>}:Connection{peer=Server}:poll:FramedRead::poll_next: tokio_util::codec::framed_impl: attempting to decode a frame    
Apr 19 15:37:26.988 TRACE server_handshake{io=hyper::common::io::rewind::Rewind<tonic::transport::service::io::ServerIo>}:Connection{peer=Server}:poll:FramedRead::poll_next: tokio_util::codec::framed_impl: frame decoded from buffer    
Apr 19 15:37:26.989 TRACE server_handshake{io=hyper::common::io::rewind::Rewind<tonic::transport::service::io::ServerIo>}:Connection{peer=Server}:poll:FramedRead::poll_next: h2::codec::framed_read: read.bytes=13
Apr 19 15:37:26.989 TRACE server_handshake{io=hyper::common::io::rewind::Rewind<tonic::transport::service::io::ServerIo>}:Connection{peer=Server}:poll:FramedRead::poll_next:FramedRead::decode_frame{offset=13}: h2::codec::framed_read: decoding frame from 13B
Apr 19 15:37:26.989 TRACE server_handshake{io=hyper::common::io::rewind::Rewind<tonic::transport::service::io::ServerIo>}:Connection{peer=Server}:poll:FramedRead::poll_next:FramedRead::decode_frame{offset=13}: h2::codec::framed_read: frame.kind=WindowUpdate
Apr 19 15:37:26.989 DEBUG server_handshake{io=hyper::common::io::rewind::Rewind<tonic::transport::service::io::ServerIo>}:Connection{peer=Server}:poll:FramedRead::poll_next: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(0), size_increment: 17 }
Apr 19 15:37:26.989 TRACE server_handshake{io=hyper::common::io::rewind::Rewind<tonic::transport::service::io::ServerIo>}:Connection{peer=Server}:poll: h2::proto::connection: recv WINDOW_UPDATE frame=WindowUpdate { stream_id: StreamId(0), size_increment: 17 }
Apr 19 15:37:26.989 TRACE server_handshake{io=hyper::common::io::rewind::Rewind<tonic::transport::service::io::ServerIo>}:Connection{peer=Server}:poll: h2::proto::streams::flow_control: inc_window; sz=17; old=65518; new=65535
Apr 19 15:37:26.989 TRACE server_handshake{io=hyper::common::io::rewind::Rewind<tonic::transport::service::io::ServerIo>}:Connection{peer=Server}:poll:FramedRead::poll_next: h2::codec::framed_read: poll
Apr 19 15:37:26.990 TRACE server_handshake{io=hyper::common::io::rewind::Rewind<tonic::transport::service::io::ServerIo>}:Connection{peer=Server}:poll:FramedRead::poll_next: tokio_util::codec::framed_impl: attempting to decode a frame    
Apr 19 15:37:26.990 TRACE server_handshake{io=hyper::common::io::rewind::Rewind<tonic::transport::service::io::ServerIo>}:Connection{peer=Server}:poll:FramedRead::poll_next: tokio_util::codec::framed_impl: frame decoded from buffer    
Apr 19 15:37:26.990 TRACE server_handshake{io=hyper::common::io::rewind::Rewind<tonic::transport::service::io::ServerIo>}:Connection{peer=Server}:poll:FramedRead::poll_next: h2::codec::framed_read: read.bytes=17
Apr 19 15:37:26.990 TRACE server_handshake{io=hyper::common::io::rewind::Rewind<tonic::transport::service::io::ServerIo>}:Connection{peer=Server}:poll:FramedRead::poll_next:FramedRead::decode_frame{offset=17}: h2::codec::framed_read: decoding frame from 17B
Apr 19 15:37:26.990 TRACE server_handshake{io=hyper::common::io::rewind::Rewind<tonic::transport::service::io::ServerIo>}:Connection{peer=Server}:poll:FramedRead::poll_next:FramedRead::decode_frame{offset=17}: h2::codec::framed_read: frame.kind=Ping
Apr 19 15:37:26.990 DEBUG server_handshake{io=hyper::common::io::rewind::Rewind<tonic::transport::service::io::ServerIo>}:Connection{peer=Server}:poll:FramedRead::poll_next: h2::codec::framed_read: received frame=Ping { ack: false, payload: [2, 4, 16, 16, 9, 14, 7, 7] }
Apr 19 15:37:26.990 TRACE server_handshake{io=hyper::common::io::rewind::Rewind<tonic::transport::service::io::ServerIo>}:Connection{peer=Server}:poll: h2::proto::connection: recv PING frame=Ping { ack: false, payload: [2, 4, 16, 16, 9, 14, 7, 7] }
Apr 19 15:37:26.991 DEBUG server_handshake{io=hyper::common::io::rewind::Rewind<tonic::transport::service::io::ServerIo>}:Connection{peer=Server}:poll:poll_ready:FramedWrite::buffer{frame=Ping { ack: true, payload: [2, 4, 16, 16, 9, 14, 7, 7] }}: h2::codec::framed_write: send frame=Ping { ack: true, payload: [2, 4, 16, 16, 9, 14, 7, 7] }
Apr 19 15:37:26.991 TRACE server_handshake{io=hyper::common::io::rewind::Rewind<tonic::transport::service::io::ServerIo>}:Connection{peer=Server}:poll:poll_ready:FramedWrite::buffer{frame=Ping { ack: true, payload: [2, 4, 16, 16, 9, 14, 7, 7] }}: h2::frame::ping: encoding PING; ack=true len=8
Apr 19 15:37:26.991 TRACE server_handshake{io=hyper::common::io::rewind::Rewind<tonic::transport::service::io::ServerIo>}:Connection{peer=Server}:poll:poll_ready:FramedWrite::buffer{frame=Ping { ack: true, payload: [2, 4, 16, 16, 9, 14, 7, 7] }}: h2::codec::framed_write: encoded ping rem=17
Apr 19 15:37:26.991 TRACE server_handshake{io=hyper::common::io::rewind::Rewind<tonic::transport::service::io::ServerIo>}:Connection{peer=Server}:poll:FramedRead::poll_next: h2::codec::framed_read: poll
Apr 19 15:37:26.991 TRACE server_handshake{io=hyper::common::io::rewind::Rewind<tonic::transport::service::io::ServerIo>}:Connection{peer=Server}:poll:FramedRead::poll_next: tokio_util::codec::framed_impl: attempting to decode a frame    
Apr 19 15:37:26.991 TRACE server_handshake{io=hyper::common::io::rewind::Rewind<tonic::transport::service::io::ServerIo>}:Connection{peer=Server}:poll: h2::proto::connection: codec closed
Apr 19 15:37:26.991 TRACE server_handshake{io=hyper::common::io::rewind::Rewind<tonic::transport::service::io::ServerIo>}:Connection{peer=Server}:poll: h2::proto::streams::streams: Streams::recv_eof
Apr 19 15:37:26.992 TRACE server_handshake{io=hyper::common::io::rewind::Rewind<tonic::transport::service::io::ServerIo>}:Connection{peer=Server}:poll: h2::proto::connection: connection.state=Closing(NO_ERROR)
Apr 19 15:37:26.992 TRACE server_handshake{io=hyper::common::io::rewind::Rewind<tonic::transport::service::io::ServerIo>}:Connection{peer=Server}:poll: h2::proto::connection: connection closing after flush
Apr 19 15:37:26.992 TRACE server_handshake{io=hyper::common::io::rewind::Rewind<tonic::transport::service::io::ServerIo>}:Connection{peer=Server}:poll:FramedWrite::flush: h2::codec::framed_write: queued_data_frame=false
Apr 19 15:37:26.992 DEBUG hyper::server::conn::spawn_all: connection error: connection error: Broken pipe (os error 32)
Apr 19 15:37:26.992 TRACE h2::proto::streams::streams: Streams::recv_eof
Apr 19 15:37:26.992 TRACE mio::poll: deregistering event source from poller    
</pre>
</details>

Tonic server logs: [log.txt](https://github.com/hyperium/tonic/files/6336443/log.txt)

**Comment by davidpdrsn** [comment]
@theduke Did you manage to solve this on your side?

**Comment by theduke** [comment]
Ah, forgot to comment.

Yes, it turns out the "broken pipe" error was just a symptom of the client closing the connection.
Functionality is not impacted.
