### ISSUE TITLE
[Question] Unable to Compile: --experimental_allow_proto3_optional was not set.

### ISSUE THREAD

**Issue by TENX-S** [hyperium/tonic#627]
Hi, I am following the [helloworld](https://github.com/hyperium/tonic/blob/master/examples/helloworld-tutorial.md) tutorial.
Everything is the same except the proto file (simply marking a field as optional):

```proto
syntax = "proto3";
package helloworld;

service Greeter {
    rpc SayHello (HelloRequest) returns (HelloReply);
}

message HelloRequest {
    optional string name = 1;
}

message HelloReply {
    string message = 1;
}

```

Then the compiler complains this error:
```shell
error: failed to run custom build command for `helloworld-tonic v0.1.0 (C:\Users\Ares\Desktop\helloworld-tonic)`

Caused by:
  process didn't exit successfully: `C:\Users\Ares\Desktop\helloworld-tonic\target\debug\build\helloworld-tonic-62132d288b771e7f\build-script-build` (exit code: 1)
  --- stderr
  Error: Custom { kind: Other, error: "protoc failed: helloworld.proto: This file contains proto3 optional fields, but --experimental_allow_proto3_optional was not set.\r\n" 
}
The terminal process "C:\Program Files\PowerShell\7\pwsh.exe -Command cargo run --package helloworld-tonic --bin helloworld-server --all-features" terminated with exit code: 1.
```

```powershell
$ protoc --version
3.15.8

$ rustc --version
rustc 1.53.0-nightly (42816d61e 2021-04-24)
```
Platform: Windows 10 20H2

How can I fix it ? Thanks !

**Comment by akiradeveloper** [comment]
How is your build.rs? In [my project](https://github.com/akiradeveloper/lol) I can compile the proto with `optional` modifier by setting the config as below

```rust
    let mut config = prost_build::Config::new();
    // ...
    config.protoc_arg("--experimental_allow_proto3_optional");
```

**Comment by TENX-S** [comment]
> How is your build.rs? In [my project](https://github.com/akiradeveloper/lol) I can compile the proto with `optional` modifier by setting the config as below
> 
> ```rust
>     let mut config = prost_build::Config::new();
>     // ...
>     config.protoc_arg("--experimental_allow_proto3_optional");
> ```

Hi, this my `build.rs`, still not work, how should I use this `config` ?:

```rust
fn main() -> Result<(), Box<dyn std::error::Error>> {
    let mut config = prost_build::Config::new();
    config.protoc_arg("--experimental_allow_proto3_optional");
    tonic_build::compile_protos("../proto/helloworld.proto")?;
    Ok(())
}
```

Cargo.toml:
```toml
[package]
name = "helloworld-tonic"
version = "0.1.0"
edition = "2018"

[[bin]] # Bin to run the HelloWorld gRPC server
name = "helloworld-server"
path = "src/server.rs"

[[bin]] # Bin to run the HelloWorld gRPC client
name = "helloworld-client"
path = "src/client.rs"

[dependencies]
tonic = "0.4"
prost = "0.7"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }

[build-dependencies]
tonic-build = "0.4"
prost-build = "0.7.0"
```

**Comment by TENX-S** [comment]
@akiradeveloper I just found your [build.rs](https://github.com/akiradeveloper/lol/blob/master/lol-core/build.rs), and it's working now, thanks!

**Comment by Courtcircuits** [comment]
> @akiradeveloper I just found your [build.rs](https://github.com/akiradeveloper/lol/blob/master/lol-core/build.rs), and it's working now, thanks!

Hey, sorry to open it again your build.rs file directs to a 404. Can you send it again ?

**Comment by markus-work** [comment]
Here is the permalink: https://github.com/akiradeveloper/lol/blob/b49ceffb46169794666bd598dda3be112fbbb9d5/lol-core/build.rs
But it was removed here for some reason: https://github.com/akiradeveloper/lol/pull/303

**Comment by Courtcircuits** [comment]
Thanks ! Actually, I was using an old version of protoc. The latest version of protoc provides `optionnal` support so I just had to upgrade to solve this issue
