### ISSUE TITLE
generated message struct miss #[derive(Debug)] 

### ISSUE THREAD

**Issue by derust** [hyperium/tonic#631]
## Bug Report

tonic generated
```rust
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RuleSetResp {}
```

as in [prost](https://github.com/danburkert/prost) readme, it should be
```rust
#[derive(Clone, Debug, PartialEq, Message)]
pub struct RuleSetResp {}
```

### Version

└── tonic v0.4.1
└── tonic-build v0.4.1

### Platform
MacOs 11.4  arm64

**Comment by davidpdrsn** [comment]
Prost actually handles that as part of `#[derive(::prost::Message)]`. `Message` is actually a subtrait of `Debug` as seen [here](https://github.com/danburkert/prost/blob/master/src/message.rs#L14).

It does indeed also work if you do something like:

```rust
fn main() {
    let msg = proto::Message { value: false };
    is_debug(msg);
}

fn is_debug<T: std::fmt::Debug>(_: T) {}
```

I'll close this for now but feel free to re-open if you're still running into this.

**Comment by derust** [comment]
the problem is :
 when I try to 

```rust
    let msg = .. //some tonic generate message type 
    log::debug!("send  msg {:?}",msg);
```

It wont compile
```
`MetricsResp` doesn't implement `Debug` (required by {:?})
```

It's not very convenience, Is there any workaround?

**Comment by davidpdrsn** [comment]
Are you able to share a minimal reproduction example?

**Comment by wuhx** [comment]
I found it was my IDE (Intellij Rust)'s mistake, It show red wavy line under msg instance , suggest it doesn't implement Debug. 
but is a false positive.

**Comment by derust** [comment]
I found it was my IDE (Intellij Rust)'s mistake, It show red wavy line under msg instance , suggest it doesn't implement Debug.
but actually is a false positive.
