### ISSUE TITLE
Is `Sync` for `Iter` necessary?

### ISSUE THREAD

**Issue by kornelski** [hyperium/tonic#636]
https://github.com/hyperium/tonic/blob/4a917a32f05c70c99d608be5ae3fc58f130ee4df/tonic/src/metadata/map.rs#L1247

`http::header::Iter` implements `Sync` if the element is `Sync`, and `HeaderValue` is `Sync`. So this unsafe `impl` seems unnecessary. I suggest removing it just in case, because if any future change made anything not actually `Sync`, it could end up incorrectly overriding it.

**Comment by davidpdrsn** [comment]
Yeah looks like that could be removed. Same goes for `IterMut`.

I'm not familiar with that part of the code so would like to hear what @LucioFranco thinks.

**Comment by LucioFranco** [comment]
Yeah, we could probably remove it but we should make sure it continues to be Sync/Send via a test.
