### ISSUE TITLE
How do I use an existing Rust struct as a message in a gRPC service?

### ISSUE THREAD

**Issue by GregOwen** [hyperium/tonic#649]
### Crates
Probably a `tonic_build` feature, possibly `prost`. This may already exist.

### Motivation
I have an existing service that I'd like to expose via a gRPC interface using Tonic. The service currently has request/response structs defined as vanilla Rust structs. I know that I can get Prost to build proto equivalents for these structs like so:

```
use prost::{self, Message};

#[derive(Message)]
pub struct RequestOne {
  #[prost(uint32, tag = "1")]
  pub f1: u32,
  ...
}

#[derive(Message)]
pub struct ResponseOne {
  #[prost(uint32, tag = "1")]
  pub f1: u32,
  ...
}
```

How do I use the resulting protos from within a gRPC service definition? For example, I have a proto file that looks like this:

```
syntax = "proto3";
package myservice;

service MyService {
  rpc ReqOne(RequestOne) returns (ResponseOne);
}
```

But when I try to build it in my `build.rs`:
```
fn main() -> Result<(), Box<dyn std::error::Error>> {
  tonic_build::compile_protos("proto/myservice.proto")?;
  Ok(())
}
```

I get the error
```
$ cargo build
error: failed to run custom build command for `foo v0.1.0 (/Users/greg/foo)`

Caused by:
  process didn't exit successfully: `/Users/greg/foo/target/debug/build/foo-7b891a7d35c99239/build-script-build` (exit code: 1)
  --- stderr
  Error: Custom { kind: Other, error: "protoc failed: myservice.proto:5:19: \"RequestOne\" is not defined.\nmyservice.proto:5:41: \"ResponseOne\" is not defined.\n" }
```

Which makes sense, since `myservice.proto` doesn't include or import those proto defs.

How do I import the derived proto definitions? My mental model is that `build.rs` is executed before the project code is compiled, which means that the derived `Message` implementations for `RequestOne` and `ResponseOne` don't exist yet. 

### Proposal
I don't actually have a proposal here; I'm just wondering if this is already supported and if so how to make it work.

Thanks!

**Comment by davidpdrsn** [comment]
And I asked in the prost Discord channel and someone wrote back that its probably not possible. Perhaps you could try opening an issue in the prost repo and see what they say https://github.com/danburkert/prost

I think I'll close this for now as this is more of a prost issue than a tonic issue.

**Comment by rtumac** [comment]
@GregOwen Where you able to find a workaround? I'm having the same dilemma

I'm also not sure I'm buying the fact that this is a prost issue. It seems that all that is needed to be done is to add the relevant use statement (e.g. `use crate::RequestOne;`) in the `.rs` file that is generated from the `.proto` file.
