### ISSUE TITLE
How do you implement a multi-threaded server?

### ISSUE THREAD

**Issue by tonnyk00** [hyperium/tonic#653]
Hi,

I'm new to rust, and I'm trying to create a multi-threaded gRPC server, but I'm not sure how to do that, could someone help me with that?

I saw one suggestion is to use the .serve_with_incoming() function, but I got the following error:

85 |                 .serve_with_incoming(stream)
   |                                      ^^^^^^ the trait `tonic::codegen::futures_core::Stream` is not implemented for `tokio::net::TcpStream`

Code snippet:
    let mut listener = TcpListener::bind(&addr).await?;
    let mut handlers = Vec::new();

    info!("Starting gRPC server");
    for (stream, _) in listener.accept().await {
        handlers.push(tokio::spawn(async move {
            let server = StoreServer { addr };
            let server_worker = Server::builder()
                .add_service(store::store_server::StoreServer::new(server))
                .serve_with_incoming(stream)
                .await;
        }));
    }

**Comment by davidpdrsn** [comment]
If you enable tokio's `rt-multi-thread` feature it will use multiple threads under the hood. So you shouldn't need to manually create an accept loop.

```toml
# Cargo.toml
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
```

Starting the server is then done with

```rust
#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let addr = "[::1]:50051".parse()?;
    let greeter = MyGreeter::default();

    Server::builder()
        .add_service(GreeterServer::new(greeter))
        .serve(addr)
        .await?;

    Ok(())
}
```

as shown in the tutorial https://github.com/hyperium/tonic/blob/master/examples/helloworld-tutorial.md

Does that answer your question?

**Comment by tonnyk00** [comment]
Thanks David. Yes that answer my question. I have tried it out and it's working.
