### ISSUE TITLE
How to return pass channel into streaming function.

### ISSUE THREAD

**Issue by d0u9** [hyperium/tonic#656]
In sample `routeguide`, [list_features()] function returns a stream to its client and holds sender endpoint for transmitting data.

This function creates a pair of endpoints inside:

```
#[tonic::async_trait]
impl RouteGuide for RouteGuideService {
    async fn list_features(
        &self,
        request: Request<Rectangle>,
    ) -> Result<Response<Self::ListFeaturesStream>, Status> {
        println!("ListFeatures = {:?}", request);

        let (tx, rx) = mpsc::channel(4);
        let features = self.features.clone();

        tokio::spawn(async move {
            for feature in &features[..] {
                if in_range(feature.location.as_ref().unwrap(), request.get_ref()) {
                    println!("  => send {:?}", feature);
                    tx.send(Ok(feature.clone())).await.unwrap();
                }
            }
        });

        Ok(Response::new(ReceiverStream::new(rx)))
    }
}
```

It is fine for "simple" applications that data generation logical is fairly trivial. For my situation, the data is produced somewhere in another module, and then be sent directly via the `rx` endpoint or pass in via some methods. However, it seems there is no way to return `rx` from this async call or pass in a pair of channel endpoints.

I have tried:

1. create channel endpoints when `RouteGuideService` is creating:

```
struct RouteGuideService {
    tx: mpsc:Sender<T>,
    rx: mpsc::Receiver<T>,
}

impl RouteGuideService {
    pub fn new() -> Self {
        let (tx, rx) = mpsc::channel(3);
        RouteGuideService {
            tx: tx,
            rx: rx,
        }
    }
}
```

Then, use this endpoints in stream. It is obviously not working due to Rust's borrow checker.

2. Assign `rx` to RouteGuideService's member variable. 

This is failed again that `&self` is not mutable.

So, is there any way to solve this puzzle?

[list_features()]: https://github.com/hyperium/tonic/blob/4d2667d1cb1b938756d20dafa3cccae1db23a831/examples/src/routeguide/server.rs#L42

**Comment by davidpdrsn** [comment]
I would probably use a [broadcast channel](https://docs.rs/tokio/1.6.0/tokio/sync/broadcast/index.html). `broadcast::Sender<T>` is clone which allows you to create one clone for your gRPC service to create new receivers and another clone which the producer system can use to send messages to all the receivers.

Creating a new receiver can be done with [`Sender::subscribe`](https://docs.rs/tokio/1.6.0/tokio/sync/broadcast/struct.Sender.html#method.subscribe) which returns a new `Receiver` that can be converted into a stream with [`tokio_stream::wrappers::BroadcastStream`](https://docs.rs/tokio-stream/0.1.6/tokio_stream/wrappers/struct.BroadcastStream.html).

Does that answer your question?

**Comment by d0u9** [comment]
`broadcast::Sender<T>` is ok but not good enough. From semantic perspective, I need a single-in single-out channel other than a "broadcast" channel.

**Comment by d0u9** [comment]
I have another module which waits for some specific "events". When a new event is received, this modules parses this event and generate a message which is sent over GPRC to clients.

I hope the event processing module can hold the channel's transmission endpoint, and once the message is ready, it can be sent over this endpoint.

This processing module and grpc server run in two tikio tasks, and communicates with each other with this channel.

**Comment by d0u9** [comment]
```
pub mod hello_world {
    tonic::include_proto!("hello");
}

// This is my server's implementation.
pub struct MyGreeter {
    // The new data is sent over to gRPC server via this mpsc::Receiver channel.
    notifer: mpsc::Receiver<i32>,
}


#[tonic::async_trait]
impl Greeter for MyGreeter {

    type SayHelloStream = ReceiverStream<Result<HelloReply, Status>>;

    async fn say_hello(
        &self,
        request: Request<HelloRequest>,
    ) -> Result<Response<Self::SayHelloStream>, Status> {
        println!("Got a request from {:?}", request.remote_addr());

        // compiling error here: this data with lifetime `'life0`...
        let (api_tx, api_rx) = mpsc::channel(3);

        tokio::spawn(async move {

            // compiling error here: ...and is required to live as long as `'static` here
            self.notifer.recv().await.unwrap();

            api_tx.send(Ok(HelloReply {
                message: format!("Hello {}!", request.into_inner().name),
            })).await.unwrap();
        });

        Ok(Response::new(ReceiverStream::new(api_rx)))
    }
}

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let addr = "[::1]:50051".parse().unwrap();

    // Create a pair of channel endpoint
    // tx is used somewhere for sending new data.
    let (tx, rx) = mpsc::channel(3);

    let greeter = MyGreeter {
        // the receiver endpoint
        notifer: rx,
    };

    println!("GreeterServer listening on {}", addr);

    Server::builder()
        .add_service(GreeterServer::new(greeter))
        .serve(addr)
        .await?;

    Ok(())
}
```

Something like this.

**Comment by davidpdrsn** [comment]
> I hope the event processing module can hold the channel's transmission endpoint, and once the message is ready, it can be sent over this endpoint.

If there can be multiple consumers of the gRPC stream then I think broadcast channels are the way to go.

If there can only ever be one consumer then you could share an `Arc<Mutex<Option<Sender<T>>>>` between the service and the producer system. Once someone calls `say_hello` you create the sender stick it into the shared sender and once the producer wants to send a message you check if there is a Sender in the Option and if so send to it. Then you wouldn't need a background task forwarding between two pairs of channels.

**Comment by d0u9** [comment]
Woo. that works. Thank you for your patience.
