### ISSUE TITLE
way how to perform half-close operation on grpc stream

### ISSUE THREAD

**Issue by adambezecny** [hyperium/tonic#659]
## Feature Request

GRPC describes half-close operaration: https://grpc.github.io/grpc/core/md_doc_core_transport_explainer.html
This kind of operation is used by google NLP detect_streaming API to indicate that all audio data have been pushed and NLP engine should start doing NLP analysis: https://cloud.google.com/dialogflow/es/docs/how/detect-intent-stream#detect-intent-stream-go

Go example on page above describes this:

```
if err == io.EOF {
                                streamer.CloseSend()
                                break
                        }
```

### Crates

I am trying to build crate for google speech-to-text  that will be providing high-level API and wrap underlying GRPC/Tonic complexity: https://github.com/jabber-tools/google-cognitive-apis/blob/main/src/dialogflow/sessions_client.rs#L209

### Motivation

To enable closeSend operation as per go example above.

Example Rust code where half-close would be sent:
https://github.com/jabber-tools/google-cognitive-apis/blob/main/examples/sessions_client_streaming_detect_intent.rs#L85-L91

**Comment by adambezecny** [comment]
correct link where half-close should be used:

https://github.com/jabber-tools/google-cognitive-apis/blob/main/src/dialogflow/sessions_client.rs#L175

**Comment by adambezecny** [comment]
hi, any update here?

**Comment by sfackler** [comment]
You can drop the sender.
