### ISSUE TITLE
feature: Start server on arbitrary free port

### ISSUE THREAD

**Issue by danielzfranklin** [hyperium/tonic#667]
## Feature Request

I want to be able to start a tonic server on an arbitrary free port and get back the port chosen.

### Crates

* tonic

### Motivation

* I want to start many servers in tests
* I want to bundle the server in a cli that runs on a users machine and doesn't make them pick a port

### Proposal

`tonic::transport::server::Router::{serve, serve_*}` should return `Result<SocketAddr, ...>` instead of `Result<(), ...>`. The `SocketAddr` will be the [local_addr](https://doc.rust-lang.org/std/net/struct.TcpListener.html#method.local_addr) of the listener. If the user provides a normal port this will be identical to what they provided. If the user provides an addr with the port `0` to the builder this will contain the port chosen.

### Alternatives

Check for a free port, and then provide that port to tonic. It's vulnerable to toctou issues and won't work on macos: https://github.com/rust-lang-nursery/rust-cookbook/issues/500

**Comment by davidpdrsn** [comment]
The recommended way to do that is to create the listener and bind to port `0`. Then the OS assigned you a port which you can get back with `.local_addr()`. You can then wrap the listener in `tokio_stream::wrappers::TcpListenerStream` and pass it to tonic using `serve_with_incoming`.

There is an example [here](https://github.com/hyperium/tonic/blob/master/tests/integration_tests/tests/timeout.rs#L77-L89).

**Comment by danielzfranklin** [comment]
Thanks
