### ISSUE TITLE
Doc: Review workflow for new users

### ISSUE THREAD

**Issue by blittable** [hyperium/tonic#67]
New users need a good on-boarding experience.  Opening an issue in support of that.

A couple scenarios for validation/enhancement:

1 - A user is familiar with using protobufs, clones, builds, runs hello world example, and starts crafting their own protobufs in tonic.

2 - A user is looking for a client/server architecture and is un-familar with with the stack.

3 - A user familiar with tokio/tower but new to grpc.

**Comment by LucioFranco** [comment]
👍 love this. I'm not sure though how to approach this? Would it make sense to provide multiple guides?

**Comment by blittable** [comment]
Multiple guides would be confusing.  

We can log individual issues in doc or group them in one.

So, 20+ - like:
"Tonic-build Readme should not  highlight version number in red  "https://github.com/hyperium/tonic/tree/master/tonic-build"

**Comment by RetWolf** [comment]
As a new user with (a little bit) of experience with Rust and gRPC, I had some trouble getting an example running without cloning this repo. I tried following along with the HelloWorld example on the README, but there weren't any commands specifying how to run. The Cargo.toml example didn't include the [[bin]] for client or server.

Personally I believe the on-boarding experience could be improved, I'm happy to make contributions when I can.

**Comment by LucioFranco** [comment]
@RetWolf hey! So we have an in progress guide #21, would you be able to check it out to see if that would have improved your experience? This is 100% something I want to work on :)

**Comment by RetWolf** [comment]
@LucioFranco I believe that tutorial would have improved my experience, and would be a good in-depth dive into some of the advanced features of the library and ecosystem. Would you be interested in a PR which includes a simple tutorial to take new users from scratch to a running HelloWorld server+client? I think it would be beneficial to have a tutorial that just shows the basics first, and then maybe have an advanced tutorial help illustrate the full capabilities of the library.

**Comment by LucioFranco** [comment]
@RetWolf I would absolutely love that! I think that is a great idea! And thank you for the feedback!

**Comment by LucioFranco** [comment]
This has been done.

**Comment by xsoheilalizadeh** [comment]
@LucioFranco I just had a bad experience in getting started with tonic, the hello world example didn't mention about out_dir, I was looking for generated files for hours, then after checking issues I found #62 which mentioned about out_dir.

**Comment by LucioFranco** [comment]
@xsoheilalizadeh if I may ask what was the reason to need to look at the generated code?
