### ISSUE TITLE
tonic-web incompatible with tonic 0.4.3 because of changes in BodyBox

### ISSUE THREAD

**Issue by CptCrispyCrunchy** [hyperium/tonic#674]
### Version
0.4.3
- tonic = { version = "0.4.3", git = "https://github.com/hyperium/tonic" }
- tonic-web = { git = "https://github.com/hyperium/tonic" }

### Platform

Linux ******** 5.8.0-53-generic #60-Ubuntu SMP Thu May 6 07:46:32 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Crates
tonic-web

### Description
Some functions from [body.rs](https://github.com/hyperium/tonic/blob/master/tonic/src/body.rs) were moved/deprecated, including `BodyBox::empty()` which is used by `tonic-web` [service module](https://github.com/hyperium/tonic/blob/9cc14b79fba9e789e215f7ea3fa40ccfaecc8e59/tonic-web/tonic-web/src/service.rs#L68) and [here](https://github.com/hyperium/tonic/blob/9cc14b79fba9e789e215f7ea3fa40ccfaecc8e59/tonic-web/tonic-web/src/service.rs#L80).

To fix this problem, it can be replaced with the `empty_body` method found in [`codegen`](https://github.com/hyperium/tonic/blob/9cc14b79fba9e789e215f7ea3fa40ccfaecc8e59/tonic/src/codegen.rs#L35)

**Comment by davidpdrsn** [comment]
This will be fixed by https://github.com/hyperium/tonic/pull/670. I'm gonna merge that now.

**Comment by CptCrispyCrunchy** [comment]
Oh great, thank you! :)
I guess this issue can be closed then?

**Comment by davidpdrsn** [comment]
Yes :)
