### ISSUE TITLE
tonic-build: Regression in generated code dependency surface area

### ISSUE THREAD

**Issue by olix0r** [hyperium/tonic#683]
## Bug Report

https://github.com/hyperium/tonic/commit/6c898a239fd5e0000ec8120ef29a0444f3680f2e appears have to introduced a regression of sorts in tonic-build: now that `futures_core` is explicitly referenced in generated code, code that would previously compile now fails with, e.g.:

```
error[E0433]: failed to resolve: use of undeclared crate or module `futures_core`
    |
277 | ...erve method."] type ObserveStream : futures_core :: Stream < Item = Result < super :: TapEvent , tonic :: Status >> + Send + Sync + 's...
    |                                        ^^^^^^^^^^^^ use of undeclared crate or module `futures_core`
```

I assume that this means that applications need to pull in a dependency on `futures-core` explicitly? It seems preferable for tonic to re-export everything generated code depends on so that applications don't have to worry about these dependencies. I.e., generated code should depend on something like `::tonic_codegen::Stream`

**Comment by davidpdrsn** [comment]
Totally! We should make Stream part of the codegen module and use that re-export from the generated code.

**Comment by olix0r** [comment]
Actually, I was wrong about the cause: I updated tonic-build without updating tonic (thanks, Dependabot). So, the `futures_core` re-export was missing in generated code.

I think technically 6c898a2 was an API breakage, but I'm okay now that I've just updated tonic.
