### ISSUE TITLE
Using arena for memory allocation per request.

### ISSUE THREAD

**Issue by Jason5Lee** [hyperium/tonic#686]
### Motivation

Recently I found some arena libraries. I really like the idea behind it. I can use an arena through an rpc call. I can allocate data and shared the reference across many types as long as they are local to the rpc call. I don't need to worry too much about lifetime, as all the data lives through the call. 
Unfortunately, this method does not work well for tonic, as the return type is an owned value instead of borrows. 

### Proposal

When a certain feature is enable

* For protobuf generation, the generated type will have a lifetime `'a` , referencing any non-copy type. For example, protobuf string maps to `&'a str`, the repeated field maps to `&'a [T]` , the following message:

```
message Request {
    string username = 1;
    string password = 2;
}
```

maps to

```
pub struct Request<'a> {
    username: &'a str,
    password: &'a str,
}
```

* Each rpc method accepts an arena parameter so that the implementation can alloc data which lives through the rpc call. For example, the following service

```
service LoginService {
    rpc Login (Request) returns (Respond);
}
```

maps to

```
#[async_trait]
pub trait LoginService {
    async fn login<'a>(arena: &'a Arena, request: Request<'a>) -> Respond<'a>;
}
```
* For underlining implementation, A new arena is created at the beginning of an rpc call, and dropped after the rpc call is finished. It passes the arena reference into the service.

**Comment by davidpdrsn** [comment]
Are there any other examples of Rust web related crates that do this and have seen significant performance/memory improvements?

It feels to me like this is something that would require _lots_ of work to implement. It would most likely also require changes to hyper, h2, and prost. So there should be a very clear benefit in building it.

**Comment by Jason5Lee** [comment]
I think it may not worth it. I'll close this issue. If you find a great benefit feel free to reopen it.
