### ISSUE TITLE
helloworld-tonic "error": "14 UNAVAILABLE: failed to connect to all addresses"

### ISSUE THREAD

**Issue by garygan89** [hyperium/tonic#688]
### Version

v0.4.2

### Platform

Windows x64

### Description

Followed the helloword-tutorial exactly from https://github.com/hyperium/tonic/blob/master/examples/helloworld-tutorial.md, but encounter gRPC connection failed when using both `BloomRPC GUI` and `grpcurl`. Also disabled Firewall just to check if that is the culprit, no avail. Strange that even the simplest helloworld failed. And yes I triple check that the server port matches. Even changed to 5001.

![image](https://user-images.githubusercontent.com/2649703/122779137-99518900-d27b-11eb-81ea-90581ca136eb.png)

**Comment by garygan89** [comment]
Ok turned out that it's because the tutorial was listening at Ipv6 address, had to change to Ipv4 manually to make it works. Not sure if this is the intended behaviour?

Before (ipv6)
```
...
let addr = "[::1]:50001".parse()?;
...
```

After (ipv4)
```
...
use std::net::{IpAddr, Ipv4Addr, SocketAddr};
...
let addr = SocketAddr::new(IpAddr::V4(Ipv4Addr::new(127,0,0,1)),50001); 
...
```

**Comment by davidpdrsn** [comment]
I just went through the tutorial and everything worked fine for me. I had to add quotes around around the address when calling grpcurl but thats zsh's fault:

```
grpcurl -plaintext -import-path ./proto -proto helloworld.proto -d '{"name": "Tonic"}' "[::]:50051" helloworld.Greeter/SayHello
```

@garygan89 Are you able to double check?
