### ISSUE TITLE
Middleware tracking

### ISSUE THREAD

**Issue by rlabrecque** [hyperium/tonic#69]
I would like to obtain parity with the go-grpc-middleware repo. By obtaining parity we can be more confident that tonic can accomplish anything gprc-go can.

We should create a new project `tonic-middleware` to provide a repository of both "official" middlware, and links to other middleware.

https://github.com/grpc-ecosystem/go-grpc-middleware

#### Auth
   * [`grpc_auth`](https://github.com/grpc-ecosystem/go-grpc-middleware/tree/master/auth) - a customizable (via `AuthFunc`) piece of auth middleware 
       * Closest we have: https://github.com/hyperium/tonic/tree/master/tonic-examples/src/authentication
        We need to be able to chain Interceptor functions for this to reach parity. Call a user defined function with less information than the whole request.

#### Logging
   * `grpc_ctxtags` - a library that adds a `Tag` map to context, with data populated from request body
   We need to be able to chain Interceptor functions for this to reach parity.

   * `grpc_zap` - integration of [zap](https://github.com/uber-go/zap) logging library into gRPC handlers.
   * `grpc_logrus`- integration of [logrus](https://github.com/sirupsen/logrus) logging library into gRPC handlers.
   Should have a `https://github.com/tokio-rs/tracing` middleware which can output the following information: https://github.com/grpc-ecosystem/go-grpc-middleware/blob/master/logging/logrus/doc.go

#### Monitoring
   * `grpc_prometheus` - Prometheus client-side and server-side monitoring middleware
   * `otgrpc` - [OpenTracing](http://opentracing.io/) client-side and server-side interceptors
   * `grpc_opentracing` - [OpenTracing](http://opentracing.io/) client-side and server-side interceptors with support for streaming and handler-returned tags

#### Client
   * `grpc_retry` - a generic gRPC response code retry mechanism, client-side middleware

#### Server
   * `grpc_validator` - codegen inbound message validation from `.proto` options
   * `grpc_recovery` - turn panics into gRPC errors
   * `ratelimit` - grpc rate limiting by your own limiter

**Comment by LucioFranco** [comment]
@rlabrecque would we want to create our own specific grpc middleware library? Ideally, I'd like these middleware to be very closely tied to the tower middleware. That said, Id love to explore these. Some may be more difficult than others.

**Comment by davidpdrsn** [comment]
With https://github.com/hyperium/tonic/pull/651 Tower middleware are now much easier to use Tonic. Tower is definitely the right abstraction for middleware like this. I think a good place to start is to write some cool middleware and release them as stand alone libraries on crates.io. Over time if some of them gain traction we can consider moving them into tonic or perhaps [tower-http](https://github.com/tower-rs/tower-http).

I'm going to close this but feel free to reopen if you have further questions.
