### ISSUE TITLE
How to handle client interrupts?

### ISSUE THREAD

**Issue by guskovd** [hyperium/tonic#691]
Let's say there is a simple service:

```proto
rpc Some(SomeRequest) returns (SomeResponse)
```

what is converted to

```rust
    async fn some(
        &self,
        request: Request<SomeRequest>,
    ) -> Result<Response<SomeResponse>, Status> {
    ...
    }
```

Service works, everything is fine

But what if I need to handle client interrupts? I tried to simulate this situation and I have a feeling that in this case the `some` method just exits immediately

**Comment by LucioFranco** [comment]
When you say interrupts you mean when the client disconnects? Can you explain your use case a bit more because of the way hyper works its hard to detect when you have on write errors.
