### ISSUE TITLE
Running into issue with UDS example

### ISSUE THREAD

**Issue by mymddoan** [hyperium/tonic#698]
https://github.com/hyperium/tonic/blob/master/examples/src/uds/server.rs

When I pull the whole tonic repo and run this example, it works. However, I'm trying to build from this example in my own directory and I keep getting the on line 81 of the example: 
error[E0437]: type `ConnectInfo` is not a member of trait `Connected` 

I copied the server.rs file along with some dependencies in Cargo.toml and a basic build.rs. Not really sure why this is happening.

**Comment by davidpdrsn** [comment]
Some changes have been made on `master` that have not yet been released on crates.io. Here is the example from version 0.4.3 https://github.com/hyperium/tonic/tree/v0.4.3/examples/src/uds.

**Comment by mymddoan** [comment]
Oh I see. Thank you!

Solved with using
tonic = { git = "https://github.com/hyperium/tonic.git", features = ["tls"] }
instead of 
tonic = {version ="0.4.0", features=["tls"]}
