### ISSUE TITLE
Middleware registration

### ISSUE THREAD

**Issue by rlabrecque** [hyperium/tonic#70]
## Feature Request

Currently tonic provides [interceptor_fn](https://github.com/hyperium/tonic/blob/8db3961491c35955c76bf2da6a17bf8a60e3b146/tonic/src/transport/server.rs#L136) but this is a little lower level than a lot of other solutions provide.

Ideally I could chain middleware functions without manually building my own stack inside an interceptor_fn.

See: #69, https://github.com/tower-rs/tower-grpc/issues/86, https://github.com/grpc-ecosystem/go-grpc-middleware

**Comment by LucioFranco** [comment]
Yeah so ideally we would use something like https://docs.rs/tower-layer/0.3.0-alpha.1/tower_layer/trait.Layer.html which achieves this. The issue right now is the extra api's around making these easier to define are not yet done. The interceptor_fn was the first attempt at trying to make an easy api for this. I would love to find a better one.

**Comment by mawenqi** [comment]
so how could I do this in version 0.1.1? thanks

**Comment by LucioFranco** [comment]
There is now this https://docs.rs/tonic/0.1.1/tonic/struct.Interceptor.html

**Comment by davidpdrsn** [comment]
This was solved as part of https://github.com/hyperium/tonic/pull/651. The API for adding tower middleware to tonic clients and servers has been simplified quite a bit. Interceptors are now also based on tower `Service` so they are composable in the same way any `Service` is.
