### ISSUE TITLE
unable to use `type_attribute` multiple times

### ISSUE THREAD

**Issue by horacimacias** [hyperium/tonic#717]
## Bug Report
I'm building .rs files from .proto files and using `type_attribute` to add some extra attributes to the .rs files.
Trying to use `type_attribute` multiple times seems to not work. Only the last type_attribute set is kept.
I'm using the same path on both type attributes; not sure if this is related to the issue or this is a misuse of such method.

Doing the same using tonic-build 0.4 shows the expected behaviour.

### Version
tonic-build v0.5.0

### Platform

Darwin computer.local 19.2.0 Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64 x86_64
### Crates

tonic-build

### Description

I tried this code:

```rust
fn main() -> Result<(), Box<dyn std::error::Error>> {
    tonic_build::configure()
        .out_dir("proto/helloworld/")
        .type_attribute(".", "// first attribute")
        .type_attribute(".", "// second attribute")
        .build_server(false)
        .compile(
            &["proto/helloworld/helloworld.proto"],
            &["proto/helloworld"],
        )?;
    Ok(())
}
```

This is a brand new `cargo new tonic-build` project with only tonic-build as dependency:

```toml
[package]
name = "tonic-build"
version = "0.1.0"
edition = "2018"

[dependencies]
tonic-build = "0.5.0"
```
I expected to see both "// first attribute" and "// second attribute" on the generated code.

Instead, I only see "// second attribute" on the generated code.
If I swap the type_attribute invocations, I only see "// first attribute" and not "// second attribute".

am I doing something wrong? Same code is working on tonic-build 0.4

as a workaround, I'm using something like:

```rust
.type_attribute(".", "// first attribute\n// second attribute")
```

**Comment by davidpdrsn** [comment]
That appears to be a bug in prost then. Tonic just forwards those attributes directly [here](https://github.com/hyperium/tonic/blob/master/tonic-build/src/prost.rs#L408-L410). If you use prost-build directly, without tonic-build, does it work as expected?

**Comment by horacimacias** [comment]
thanks, and sorry I did not realise that.

Indeed, using the same sample project with `prost-build = "0.8.0"` dependency shows the same issue, so it does not look like it's caused by tonic.

I'll open an issue on prost.

**Comment by horacimacias** [comment]
FYI, issue already existed in prost:  https://github.com/tokio-rs/prost/issues/502

**Comment by davidpdrsn** [comment]
Thanks! It can sometimes be hard to know where the boundaries is between prost and tonic.
