### ISSUE TITLE
Tonic::Async_trait performances

### ISSUE THREAD

**Issue by Leanerz** [hyperium/tonic#728]
Hi

Does tonic::async_trait similar to async_trait crate?

https://rust-lang.github.io/async-book/07_workarounds/05_async_in_traits.html

`Note that using these trait methods will result in a heap allocation per-function-call. This is not a significant cost for the vast majority of applications, but should be considered when deciding whether to use this functionality in the public API of a low-level function that is expected to be called millions of times a second.`

It seem from this link it is depreciated for low latency apps.

Any suggestion please?

**Comment by MikailBag** [comment]
> Does tonic::async_trait similar to async_trait crate?

Yes, it is re-export from `async-trait` actually.

> It seem from this link it is depreciated for low latency apps.

I think this allocation cost will likely be negligible when compared to network latencies, HTTP & Protobuf parsing, etc.

**Comment by davidpdrsn** [comment]
> [..] that is expected to be called millions of times a second

Do you have an RPC that is called millions of times a second? 😅

But yeah. The cost should be negligible.
