### ISSUE TITLE
RPC Name Conflict with Client Generated Code

### ISSUE THREAD

**Issue by SkamDart** [hyperium/tonic#747]
### Version

└── tonic v0.5.2
└── tonic-build v0.5.2

### Platform

Linux chowder 5.11.0-27-generic #29~20.04.1-Ubuntu SMP Wed Aug 11 15:58:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
### Crates

tonic-build

### Description
Service name `connect` creates conflict with generated client `connect` function.

Sample proto
```
syntax = "proto3";

package request;

message ConnectRequest {}

message ConnectResponse {}

service Connector {
    rpc Connect(ConnectRequest) returns (ConnectResponse) {}
}
```

[Full repro](https://github.com/SkamDart/tonic-connect-repro/tree/main)

A fix might be to check the [generated service definitions](https://github.com/hyperium/tonic/blob/master/tonic-build/src/client.rs#L133-L140) for reserved identifiers like [tokio/prost](https://github.com/tokio-rs/prost/blob/28e4522f8ae738d4574cce104da6fd88d9ce0c14/prost-build/src/ident.rs#L12-L28) does.

**Comment by LucioFranco** [comment]
To work around this you should be able to just disable the transport feature of `tonic-build`.

**Comment by chancila** [comment]
@LucioFranco isn't it more desirable to just fix the issue instead of using this workaround?
