### ISSUE TITLE
Support deadlines with the grpc-timeout header

### ISSUE THREAD

**Issue by thomasetter** [hyperium/tonic#75]
The [official protocol definition](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md) mentions the `"grpc-timeout"` header which is a way for the client to tell the server what deadline it has.
As I understand it, the timeout should be converted into a deadline as soon as the header is read (before the rest of the payload).

Using this, when the server is overloaded, requests can just be dropped with `DEADLINE_EXCEEDED` or `CANCELLED` (not sure which one should be picked on the server side) if it takes too long until they are processed.
E.g. in C++, There is the [`ServerContext::IsCancelled()`](https://grpc.github.io/grpc/cpp/classgrpc__impl_1_1_server_context.html#ac0fe2a9425b18b724f910adbe0e3c17a) function which can be used to exit early: [Blog post on gRPC deadlines](https://grpc.io/blog/deadlines/)

How can this be achieved with tonic?
Are there features in tower/hyper which could be used?

**Comment by LucioFranco** [comment]
Hi Yes, this should be possible by implementing a custom service layer that reads the initial headers and wraps its inner future with a timeout.

**Comment by ParkMyCar** [comment]
I think this would be pretty interesting to build, if no one else is already working on it, I can try to put up a PR in a bit?

Aside from timeouts, there's also [cancelation](https://grpc.io/docs/guides/concepts/#rpc-termination). Is there a story around this yet in tonic?

**Comment by LucioFranco** [comment]
I think the right method would be to create a version of https://github.com/tower-rs/tower/tree/master/tower/src/timeout that gets the timeout from a header rather than a static value.

**Comment by Maher4Ever** [comment]
@LucioFranco Hi, is there an update regarding cancellation support in `tonic`?

**Comment by LucioFranco** [comment]
No updates from my end yet, its easy to support cancellation by dropping the task but we currently do not parse the headers for a timeout automatically.

**Comment by Sushisource** [comment]
Huge +1 here. In particular I need support for setting them on the client. Adding them manually appears to not work, since it looks like all the `GRPC_RESERVED_HEADERS` are silently stripped (which isn't so fun) as mentioned in #516. If there's anything I can do do help @LucioFranco I am happy to do so.

**Comment by liufuyang** [comment]
I feel I need to set deadline or timeout on client as well, otherwise my Rust client cannot talk to our Java gRPC servers as they are build to require having deadline specified.
