### ISSUE TITLE
tonic build generates empty google.protobuf.rs file

### ISSUE THREAD

**Issue by maoueh** [hyperium/tonic#757]
## Bug Report

When a protobuf definitions imports one of the well-known protobuf types (e.g. `import "google/protobuf/any.proto";`), it generates an empty `google.protobuf.rs` file in the output folder.

Repro repository: https://github.com/maoueh/bug-tonic-build-spurious-types

### Version

- `tonic 0.5.1` 

### Platform

```
$ uname -a
Darwin TBD6.localdomain 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64
```

**Comment by LucioFranco** [comment]
I believe this is a prost issue rather than a tonic one. If you could open this issue in there that would be helpful.

**Comment by maoueh** [comment]
Already reported there: https://github.com/tokio-rs/prost/issues/228
