### ISSUE TITLE
[import/reuse local proto]

### ISSUE THREAD

**Issue by 51yu** [hyperium/tonic#768]
n00b question, I am trying to import message definition from another local proto

other.proto
```
syntax = "proto3"
package other;
message FooRequest {}
message FooResponse {}
```
this.proto
```
import "other.proto"

service HelloWord {
       rpc HelloFoo(other.FooRequest) returns(other.FooResponse)
}
```
^^ proto files, both located in same folder of local repository, run build script for codegen throw exception
```
process didn't exit successfully: `LOCAL_PATH/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: "protoc failed: other.proto: File not found.\nthis.proto:4:1: Import \"other.proto\" was not found or had errors.\this.proto:7:15: \"other.FooRequest\" is not defined.\nthis.proto:7:44: \"other.FooResponse\" is not defined.\n" }', other.rs:5:10
```
Any example I could reference for `local proto import` ? Thanks for helping 😄

**Comment by Siceberg** [comment]
Have any answers? I have the same need.

**Comment by LucioFranco** [comment]
The `other.proto` must be in the same dir as the original proto, you can look at the gcp example which uses this to import local protos.
