### ISSUE TITLE
add Single-threaded runtime（double performance improve）

### ISSUE THREAD

**Issue by zhuxiujia** [hyperium/tonic#784]
In my tests, use tokio-current_thread_runtime(), tonic Grpc Performance and QPS can be improved by at double performance。(test by  [ghz](https://github.com/bojand/ghz) benchmark)

can you add an option  feature  to support current_thread_runtime( just like actix-web/  actix-rt ，Number of threads: number of CPU cores x 2) ?  This change can greatly improve QPS scores

![641633933803_ pic_hd](https://user-images.githubusercontent.com/3481148/136742983-90a642d6-89c7-4afb-9a63-da400f28b547.jpg)

**Comment by chengzh2008** [comment]
@zhuxiujia 
Hi, just curious how did you run the grpc server? What kind of computer did you run the test on? 

I have tested the grpc server by running the example helloworld grpc server on my laptop (macbookpro 2019). However, ghz test result shows that the server can handle only up to about 4000 requests/sec. I am not sure why I could not see the  good performance shown here and other blogs. 

Thanks

**Comment by mahdibaghdadi** [comment]
@chengzh2008

**Comment by mahdibaghdadi** [comment]
@chengzh2008 
Same, did you find an answer?

**Comment by LucioFranco** [comment]
Its likely an issue with ghz and not tonic.

**Comment by gitmalong** [comment]
> Tonic should already support the tokio single threaded runtime, is there something you see missing?

How can this be activated?
