### ISSUE TITLE
tonic cargo build problems

### ISSUE THREAD

**Issue by apiscerena** [hyperium/tonic#789]
I tried to compile the following message 

`message BlockExecuteReq { 
    uint64 block_number = 1;
    Block block = 2;
}`

but i got the following result

`#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BlockExecuteReq {
    #[prost(uint64, tag = "1")]
    pub block_number: u64,
    #[prost(message, optional, tag = "2")]
    pub block: ::std::option::Option<Block>,
}`

The problem is, i didn't specify the Block message as optional, why i got the option Block segement?

**Comment by leontoeides** [comment]
Thank you for the answer. I couldn't understand why `tonic` was giving me an `Option<T>` for a non-optional field.
