### ISSUE TITLE
How can I use tonic build with buf.build

### ISSUE THREAD

**Issue by insanebaba** [hyperium/tonic#793]
Hi team,

I have an existing project in golang that I want to migrate to tonic, can you suggest how to use code gen with but.build ? We generate multiple stubs for different language, so we'd like to keep using buf for code gen, but it'd be great if we could generate tonic stubs too.

Thank you

**Comment by davidpdrsn** [comment]
What is buf?

**Comment by insanebaba** [comment]
It's a tool to optimize codegen process for multiple languages. But they use codegen binaries to generate code. and I don't see any tutorial for tonic to generate code using cli.
