### ISSUE TITLE
Migrate to Rust 2021 edition

### ISSUE THREAD

**Issue by LucioFranco** [hyperium/tonic#806]

**Comment by abergmeier** [comment]
I am confused - it seems like tonic is still using 2018: https://github.com/hyperium/tonic/blob/1f5bc9b9d55f814d1cb83de6f43239e275122265/tonic/Cargo.toml#L23

Have currently a project where I use 2021 and I get a ton of errors - so not sure whether tonic does work with 2021 at all.

**Comment by davidpdrsn** [comment]
I believe we went back to 2018 because moving to a new edition is a breaking change.

You won't get errors by using a crate from an older edition. That's part of how editions are designed. So something else must be going on.
