### ISSUE TITLE
Generated Clients should have a trait defining the methods it implements for proper mocking

### ISSUE THREAD

**Issue by Jake-S6** [hyperium/tonic#809]
## Feature Request

Generated Clients should have a trait defining the methods it implements for proper mocking. The important case being any code that utilizes these clients cannot mock it out properly to make focused unit tests without additional overhead dev work. We have to add boilerplate code defining a trait with the same method signatures and implementing that new trait with the generated tonic client ourselves per client instead of having it done as part of the code generation step. This approach is more brittle and has higher dev effort for anyone using Tonic Clients that want to test their code properly.

We already have this for the generated Server code, so adding it to Client seems to fall in line with the design.

### Crates

* tonic-build

### Motivation

Being able to follow the standard unit test approach using proper mocking by default. 

### Proposal

For a service
```
service Greeter {
  rpc SayHello (HelloRequest) returns (HelloReply) {}
}
```

instead of having 

```
    impl<T> GreeterClient<T>
    where ...
    {
...
        pub async fn say_hello(
            &mut self,
            request: tonic::Request<super::HelloRequest>,
        ) -> Result<tonic::Response<super::HelloReply>, tonic::Status> {
           ...
        }
    }
```

we should have something along the lines of

```
   pub trait Greeter: ... {
        async fn say_hello(
            &self,
            request: tonic::Request<super::HelloRequest>,
        ) -> Result<tonic::Response<super::HelloReply>, tonic::Status>;
    }

    impl Greeter for GreeterClient<T>
    where ...
    {
...
        pub async fn say_hello(
            &mut self,
            request: tonic::Request<super::HelloRequest>,
        ) -> Result<tonic::Response<super::HelloReply>, tonic::Status> {
           ...
        }
    }
```

### Alternatives

The only alternative I see is to stick to the current state and require the additional overhead on the devs using tonic Clients.

**Comment by Sushisource** [comment]
@LucioFranco I'll just throw out there one other reason besides just mocking is to enable wrapper types. Right now for example this is how I implement some retry logic reasonably generically as a workaround for the issues mentioned here: https://github.com/hyperium/tonic/issues/733
