### ISSUE TITLE
Endpoint::new Fixme comment

### ISSUE THREAD

**Issue by elpiel** [hyperium/tonic#822]
## Feature Request
As a user of the crate, I can say that the `Endpoint::new()` assoc. function is very handy.

### Crates
`tonic`

### Motivation

While the `from_shared` returns an `InvalidUri` error directly, the `fn new()` returns `tonic::transport::Error`.
When creating an endpoint I'd like to return `tonic::transport::Error` directly or use it to build my own error if needed.

### Proposal

Unhide `Entrypoint::new()` from the docs.

## Code
https://github.com/hyperium/tonic/blob/debcafe08cd64f03bff2fee0eaa1521e47794a8a/tonic/src/transport/channel/endpoint.rs#L46-L49

**Comment by LucioFranco** [comment]
I wonder if we should just change `from_shared` to return `transport::Error`?

**Comment by elpiel** [comment]
This will introduce a breaking change and the other impls should be changed as well `TryFrom`.
I think there is a case where you'd want to handle only the `InvalidUri` and use that in your API (e.g. a custom error) instead of `tonic::transport::Error`, however, in order to use the `InvalidUri` in your custom error you'd have to add the `http` crate as a dependency too.

Re-exporting `InvalidUri` & just making the new assoc. fn public is sufficient to me.

Side note: `impl From<InvalidUri> for Error` could also be useful to crate users. E.g. I currently use 1 endpoint that I pass to all generate services in my struct, however, I might want to create multiple endpoints for each service and still return a `tonic::transport::Error`
