### ISSUE TITLE
Serde feature to derive Serialize & Deserialize

### ISSUE THREAD

**Issue by elpiel** [hyperium/tonic#823]
## Feature Request

Add a feature to `tonic-build` to derive `serde::Serialize` & `serde::Deserialize`

### Crates

`tonic-build`

### Motivation

It can be really useful to have a feature for deriving `serde::Serialize` & `serde::Deserialize` when you want to use or record the Requests & Responses in another format, e.g. json.

**Comment by davidpdrsn** [comment]
This can be done with [`tonic_build::Builder::type_attribute`](https://docs.rs/tonic-build/0.6.0/tonic_build/struct.Builder.html#method.type_attribute) which is a wrapper around [`prost_build::Config::type_attribute`](https://docs.rs/prost-build/0.9.0/prost_build/struct.Config.html#method.type_attribute).

**Comment by elpiel** [comment]
> This can be done with [`tonic_build::Builder::type_attribute`](https://docs.rs/tonic-build/0.6.0/tonic_build/struct.Builder.html#method.type_attribute) which is a wrapper around [`prost_build::Config::type_attribute`](https://docs.rs/prost-build/0.9.0/prost_build/struct.Config.html#method.type_attribute).

I'm aware of this method but currently, it's very inefficient to collect all the names of structs, responses, requests, etc. and add the attributes using `type_attribute` calls.

I'm perfectly fine with leaving it as is, however, it could make a good feature for the crate to support adding serialize & dserialize automatically.

**Comment by davidpdrsn** [comment]
I think some version of that feature would be nice. Probably wouldn't wanna special case serde's traits but have some more general system. However this is something that needs to be implemented in prost as thats what tonic uses to compile your protos. I suggest you open an issue there.

**Comment by elpiel** [comment]
Ok @davidpdrsn 
Thank you for your time :yum:
