### ISSUE TITLE
tonic::build problem

### ISSUE THREAD

**Issue by apiscerena** [hyperium/tonic#833]
My directory structure follows: 

```

tonic-demo
    |---common
        |---db
        |---protos
            |---executor
                 |---exec.proto
            |---trans.proto
            |---block.proto
    |---network
    |---broker
        |---src
        |---build.rs


```

i wanna build 3 proto files (exec.proto, trans.proto, block.proto) in build.rs, how should I write the build.rs code?

**Comment by Rustixir** [comment]
hi 
`
fn main() -> Result<(), Box<dyn std::error::Error>> {

    tonic_build::compile_protos("protos/executor/exec.proto")?;
    tonic_build::compile_protos("protos/trans.proto")?;
    tonic_build::compile_protos("protos/block.proto")?;

    Ok(())

}

`

good luck !
