### ISSUE TITLE
After many Test ... tonic serialize/deserialize is Slow !!??

### ISSUE THREAD

**Issue by Rustixir** [hyperium/tonic#834]
### Version
edition = "2021"
tonic = "0.6"
prost = "0.9"
tokio = "1.0"

### Platform
Ubuntu 20

### Description

I wrote a service, after many test.
I saw that my code runs in a maximum of **48 microseconds**

But when writing a very simple grpc layer
My code runs at least **12 milliseconds**

Why ??

its mean 
with tonic        ==> 83 rps
without tonic  ==> 20_833 rps

difference is high

`

async fn produce_event(&self,  request : Request<ProduceEventRequest> ) -> Result<Response<Empty>, Status> { 
            
        let msg = request.into_inner();
        let res = self.service.as_ref().write().await.produce_event(msg.node_name, msg.event);
        
        match res {
            Ok(_)  => Ok(Response::new(Empty{})),
            Err(_) => Err(Status::not_found("Not found Node"))
        }
    }

`

`

    let addr = "127.0.0.1:8089".parse().unwrap();

    let service = Arc::new(tokio::sync::RwLock::new(TeslaQ::open()));
    let jerry = Jerry {
        service
    };
            
    Server::builder()
        .add_service(EngineServer::new(jerry))
        .serve(addr)
        .await.unwrap();
    

    Ok(())
`

When I switch to REST API with Actix_web my service running almost always under **10 milliseconds**

**Comment by davidpdrsn** [comment]
I'm sorry but I understand what you mean. Are you able to elaborate and provide more examples?

Also, please format your code using triple backticks:

```
```rust
// your code here
```
```

**Comment by Rustixir** [comment]
I'm Sorry my format was bad .

actually one function is called per request for log event
to disk, and for that I use **std::fs::File**,   not use **tokio::fs::File**. 

 ```
pub fn push(&mut self, event: &mut String) {
            event.push_str(" \n");
            let bytes = event.as_bytes();
            self.find_avail_disk(bytes.len());
            let _ = self.writer.write_all(bytes);
}

// struct of vnode.push calling this **pub fn push**  internally 

pub struct TeslaQ {
....
} 


impl TeslaQ {

pub fn produce_event(&mut self, vn_name: String, mut event: String) -> Result<(), Error> {
            match self.vnodes.get_mut(&vn_name) {
                None => Err(Error::NotFound),
                Some(vnode) => {
                   vnode.push(&mut event);
                    Ok(())
                }
            }
        }
}

```

upper is codes of behind **produce_event** call from bellow code


```
async fn produce_event(&self, request : Request <ProduceEventRequest>) -> Result<Response<Empty>, Status> {

    let msg = request.into_inner();
    let res = self.service.write().await.produce_event(msg.node_name, msg.event);
    
    match res {
        Ok(_)  => Ok(Response::new(Empty{})),
        Err(_) => Err(Status::not_found("Not found Node"))
    }
}


``` 

And rpc call in proto for That is this 

```
rpc ProduceEvent (ProduceEventRequest) returns  (Empty);

message ProduceEventRequest {
    string node_name = 1;
    string event   = 2;
}


message Empty {}


```


and I tested this on a **current-thread scheduler** 
and use ```Arc<tokio::sync::RwLock>```

```

let addr = "127.0.0.1:8089".parse().unwrap();

let service = Arc::new(tokio::sync::RwLock::new(TeslaQ::open()));
let jerry = Jerry {
    service
};
        
Server::builder()
    .add_service(EngineServer::new(jerry))
    .serve(addr)
    .await.unwrap();


Ok(()) 


```

but when i tested that function, always done under **40 microseconds**
and when use tonic done between (12 ~ 18) milliseconds
I said serialize/deserialize because code work fast
when use that codes in tonic service difference occur.


Excuse me if my description was not very good. Thanks .

**Comment by LucioFranco** [comment]
That seems odd but without a full repo maybe to reproduce this it is hard to figure out what may be wrong.

**Comment by Rustixir** [comment]
I rewrote that system in Rest but now rewrote it again in 
And I created a repository: [https://github.com/Rustixir/Teslaq]()

**Comment by Rustixir** [comment]
I tested on my own gRPC client. It is always done below 7 milliseconds.
 I suggest do not use ** https: //github.com/riok/Kreya/**  latency is not predictable, I used it in the test before
