### ISSUE TITLE
Slightly confusing wording in the helloworld tutorial

### ISSUE THREAD

**Issue by mfonism** [hyperium/tonic#835]
[Line 128 of the tonic helloworld tutorial](https://github.com/hyperium/tonic/edit/master/examples/helloworld-tutorial.md#L128) says, "At the root of your crate, create a `build.rs` file and...".

Should that really be the root of the __crate__?

It was really confusing to me as a Rust newbie. I made an educated guess and created the file under my `src` directory, because in my little experience crates go in there (and I'd never seen a `.rs` file outside the `src` directory, yet).

It was not until I hit an error that I realized the build script was actually to go into what I'd say is the package/project root so that the proto's can be built.

I'm suggesting the tutorial rewords that part [and line 35](https://github.com/hyperium/tonic/edit/master/examples/helloworld-tutorial.md#L35) to say "root of your project" or "root of your package".

**Comment by mfonism** [comment]
I'm happy to create a PR for this.

**Comment by davidpdrsn** [comment]
Good point. Thats not obvious if you haven't worked with build scripts before. A PR would be much appreciated 😊
