### ISSUE TITLE
how to generate trait with #[async_trait(?Send)]

### ISSUE THREAD

**Issue by zojw** [hyperium/tonic#844]
## Feature Request

Hi, I'm investigating how to use [tokio-uring](https://github.com/tokio-rs/tokio-uring) to read/write file system in a GRPC server.

tokio-uring [return future always `!Send`](https://github.com/tokio-rs/tokio-uring/pull/1/files#diff-3dc5dd454e080eb849ee5efaf79df2585fbe0a06804d69249b4c81da05a63875R138)

so the first question, I meet is #[async_trait] need change to [#[async_trait(?Send)]](https://docs.rs/async-trait/0.1.51/async_trait/#non-threadsafe-futures) and current_thread runtime.

but it seems tonic generate code always be #[async_trait]

https://github.com/hyperium/tonic/blob/master/tonic-build/src/server.rs#L189

do we have any advice about this~? or do we have the advice to integrate tonic with tokio-uring? 😄 

### Crates

- tonic-build
- not sure whether "current_thread runtime" can works well with other tonic crate too - - 

### Motivation

read_at a file by tokio-uring(or other io-uring libs) in tonic server-side

### Proposal

n/a

### Alternatives

n/a

**Comment by davidpdrsn** [comment]
Tonic currently doesn't support `!Send` futures so generating the traits with `#[async_trait(?Send)]` isn't supported either. Not quite sure if its feasible to support both `Send` and `!Send` futures 🤔

As far as workarounds, honestly not sure. Maybe someone in `#tokio-users` in the tokio discord is able to give advice?

**Comment by zojw** [comment]
for my situation, it seems I can use more simple network protocol and raw TCP to workaround, so close this first :)
