### ISSUE TITLE
tonic server and client position?

### ISSUE THREAD

**Issue by apiscerena** [hyperium/tonic#854]
i was wondering if all tonic client and server should be under the [#tokio::main] tag? 
if not, any example in the repo?

**Comment by davidpdrsn** [comment]
I don't understand what you mean? Nothing special is required to use tonic inside `#[tokio::main]`.

**Comment by zbysir** [comment]
> i was wondering if all tonic client and server should be under the [#tokio::main] tag? if not, any example in the repo?

I may understand what you mean, [#tokio::main] is used for the asynchronous main method, which has nothing to do with tonic. More information should refer to tokio.
