### ISSUE TITLE
Reasoning for prost rather than rust-protobuf?

### ISSUE THREAD

**Issue by hugecheese** [hyperium/tonic#86]
Although I don't know much about the two libraries, on it's surface `rust-protobuf` appears to be more maintained than `prost`. What was the reasoning behind that choice?

**Comment by LucioFranco** [comment]
@hugecheese Hi! In general, I find I prefer `prost` and iirc it is much faster. Don't quote me on that though. We've been using `prost` both in `linkerd` and `vector` so in general, I am very happy with that library. I have not really used `rust-protobuf` that much though. The other thing is that `prost` uses the `bytes` crate which is very important for us.
