### ISSUE TITLE
Mock example fails when shutdown signal is set

### ISSUE THREAD

**Issue by SuperFluffy** [hyperium/tonic#867]
## Bug Report

When adding a shutdown signal to the [mock example](https://github.com/hyperium/tonic/blob/e78a2d832fdab61e82586cc1cf954f31b16da02a/examples/src/mock/mock.rs) the client channel stream is accessed twice, leading to a panic.

### Version

0.6.2 and recent master e78a2d832fdab61e82586cc1cf954f31b16da02a

### Platform

```
Darwin MPB 20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:20 PDT 2021; root:xnu-7195.141.6~3/RELEASE_ARM64_T8101 arm64
```

### Description

This branch contains the slightly altered code to start the server with a shutdown signal: https://github.com/SuperFluffy/tonic/tree/mock_shutdown_fails

Running the server with the shutdown signal leads to this error:

```shell
❯ cargo run -p examples --bin mock
    Finished dev [unoptimized + debuginfo] target(s) in 0.07s
     Running `target/debug/mock`
thread 'tokio-runtime-worker' panicked at 'tried accessing client twice', examples/src/mock/mock.rs:47:40
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Error: Status { code: Unknown, message: "transport error", source: Some(tonic::transport::Error(Transport, Closed)) }
```

The only change is in how the server is spawned:

```rust
    let mut shutdown_signal = signal(SignalKind::terminate()).unwrap();
    tokio::spawn(async move {
        Server::builder()
            .add_service(GreeterServer::new(greeter))
            .serve_with_incoming(futures::stream::iter(vec![Ok::<_, std::io::Error>(
                mock::MockStream(server),
            )]))
            .serve_with_incoming_shutdown(
                futures::stream::iter(vec![Ok::<_, std::io::Error>( mock::MockStream(server),)]),
                async move {
                    shutdown_signal.recv().await;
                    println!("shutting down");
                },
            )
            .await
    });
```

This error was previously reported on discord: https://discord.com/channels/500028886025895936/628706823104626710/857777118048944128

**Comment by SuperFluffy** [comment]
This still happens with #923 merged (which makes sense, because that `MockStream` was just a wrapper around `DuplexStream`).

**Comment by LucioFranco** [comment]
Ok I opened https://github.com/hyperium/tonic/pull/926. So in this case because the server shutdown the client now returns an error instead of the panic on the unwrap. The reason it tries to take the client twice is that the server disconnects and the client tries to reconnect.

**Comment by SuperFluffy** [comment]
Oh, that's interesting and not at all what I would have assumed. Any chance you can point me to the code where this happens so I can try and understand that?

**Comment by LucioFranco** [comment]
Here is the code that reconnects by calling make_service https://github.com/hyperium/tonic/blob/master/tonic/src/transport/service/reconnect.rs.

I am going to close this issue though (we can continue to discuss here) since I think this has been resolved.
