### ISSUE TITLE
Asynchronous interceptor

### ISSUE THREAD

**Issue by thekeenant** [hyperium/tonic#870]
I'm working with Tonic (+tokio) trying to introduce authentication/authorization for my gRPC server. I can see a simple example of this [here](https://github.com/hyperium/tonic/blob/master/examples/src/authentication/server.rs). However, I think auth would typically involve dispatching some additional request (e.g. http, rpc, or some database request) to make the decision to return Ok or Err (to check db for presence of some token, or username/password, etc.)

Is it possible to call such an async function from a Tonic interceptor? Or maybe it's necessary to use Tower to accomplish this and if that's the case, any plans to make regular Tonic interceptors async capable?

**Comment by davidpdrsn** [comment]
Async interceptors currently requires writing a tower service middleware.

Several people have asked about it so probably does make sense to have a convenient API for 😊

**Comment by jdahlq** [comment]
FYI I have published v0.1.0 of [tonic-async-interceptor](https://crates.io/crates/tonic-async-interceptor) which uses tonic v0.8.1. Hope it is useful!

**Comment by liufuyang** [comment]
@jdahlq Do you know if it is possible to also use your tonic-async-interceptor for a client/Channel?  For now we have an [Interceptor](https://github.com/liufuyang/bigtable_rs/blob/154caed2a12a7deba282732bcb22d9d027d0f509/bigtable_rs/src/bigtable.rs#L426) and used it on a client with the generated [.with_interceptor() method](https://github.com/liufuyang/bigtable_rs/blob/154caed2a12a7deba282732bcb22d9d027d0f509/bigtable_rs/src/google/google.bigtable.v2.rs#L1072)

Later we might need to switch the interceptor with [some auth manager](https://github.com/hrvolapeter/gcp_auth/blob/a3edad5f7c2f0cc2c3e8d2b8c0cbcbbfa43cdc95/examples/simple.rs) that seems only providing an async API. But now I am not sure how we can switch it to an async interceptor. (Or perhaps there are other ways to do this?) cc @LucioFranco

**Comment by talksik** [comment]
is this not supported? I feel like this is a fundamental feature for allowing production rust grpc

**Comment by rthomas** [comment]
> @jdahlq Do you know if it is possible to also use your tonic-async-interceptor for a client/Channel? For now we have an [Interceptor](https://github.com/liufuyang/bigtable_rs/blob/154caed2a12a7deba282732bcb22d9d027d0f509/bigtable_rs/src/bigtable.rs#L426) and used it on a client with the generated [.with_interceptor() method](https://github.com/liufuyang/bigtable_rs/blob/154caed2a12a7deba282732bcb22d9d027d0f509/bigtable_rs/src/google/google.bigtable.v2.rs#L1072)
> 
> Later we might need to switch the interceptor with [some auth manager](https://github.com/hrvolapeter/gcp_auth/blob/a3edad5f7c2f0cc2c3e8d2b8c0cbcbbfa43cdc95/examples/simple.rs) that seems only providing an async API. But now I am not sure how we can switch it to an async interceptor. (Or perhaps there are other ways to do this?) cc @LucioFranco
> 
> Or maybe in short, how can one uses a token generated by [an async method](https://github.com/hrvolapeter/gcp_auth/blob/a3edad5f7c2f0cc2c3e8d2b8c0cbcbbfa43cdc95/src/default_service_account.rs#L38) in [the simple client example](https://github.com/hyperium/tonic/blob/master/examples/src/authentication/client.rs)

Hi @liufuyang did you find a solution here? I've hit the same issue trying to make a k8s call to validate a service account token.

**Comment by liufuyang** [comment]
I am not  sure if it can help but I seemed solved it by using a tower service, like this:

https://github.com/liufuyang/bigtable_rs/blob/3784be482e9d7892c7e8c2d7dd822f43f2e06a87/bigtable_rs/src/auth_service.rs#L35

Then that service (with some auth middleware) then is used to create a grpc client.
https://github.com/liufuyang/bigtable_rs/blob/3784be482e9d7892c7e8c2d7dd822f43f2e06a87/bigtable_rs/src/bigtable.rs#L324C1-L327C42

Not sure if this helps and whether this is the recommended way to do such thing nowadays.

**Comment by teimuraz** [comment]
I also stuck finding good example is using async interceptor / middleware. Managed to do it with Tower. Made little lib to simplify creation of async interceptors / and "Full" Middlewares (intercept whole service call) . Hopefully, it can help someone else out too!   https://github.com/teimuraz/tonic-middleware

**Comment by felipellrocha** [comment]
Any updates on this? I also just got stuck here having to hack around in order to use an async interceptor

**Comment by ladd-a** [comment]
For anyone else stumbling upon this, consider using [futures crate](https://docs.rs/futures/0.3.30/futures/index.html) to call asynchronous code inside the regular interceptor functions.

It can be as simple as:
```rust
fn blocking_fn() {
    futures::executor::block_on(my_async_function());
}
```

**Comment by dallinwright-tradecrit** [comment]
I got it to work, also with app state propagated to the async interceptor as well. Hard to get it stitched but it works, using crate `tonic-async-interceptor = "0.12.0"`


```rust
    let app_state_clone = app_state.clone();
    let auth_interceptor = move |req: Request<()>| {
        let app_state = app_state_clone.clone();
        async move { check_auth(req, app_state).await }
    };

    Server::builder()
        .layer(async_interceptor(auth_interceptor))
        .add_service(health_service)
        .serve(addr)
        .await?;
```

and an example of what the interceptor looks like

```rust
pub async fn check_auth(req: Request<()>, app_state: AppState) -> Result<Request<()>, Status> {
    let token: &MetadataValue<Ascii> = req.metadata().get("authorization").unwrap();

    tracing::debug!("Checking auth token: {:?}", token);

    let auth_url = app_state.auth_url.clone();

    let authentication_client = AuthenticationClient::connect("http://localhost:50051").await.unwrap();

  // do the auth stuff, Ok the req on success or return an error if not

 Ok(req)
}
```

**Comment by daniele-solutiontech** [comment]
Any update on this? Native support for async interceptor would be extremely useful!
