### ISSUE TITLE
Server/Router type signatures are not grok-able

### ISSUE THREAD

**Issue by iitalics** [hyperium/tonic#874]
### Version

0.6.2

### Platform

any

### Crates

tonic

### Description

The type signatures in the `Server`/`Router` builders are convoluted and reference private types, which makes them completely un-understandable to users.

For example, from `tonic::transport::server::Router`:

```rs
pub async fn serve<ResBody>(self, addr: SocketAddr) -> Result<(), Error> where
    L: Layer<Routes<A, B, Request<Body>>>,
    L::Service: Service<Request<Body>, Response = Response<ResBody>> + Clone + Send + 'static,
    <<L as Layer<Routes<A, B, Request<Body>>>>::Service as Service<Request<Body>>>::Future: Send + 'static,
    <<L as Layer<Routes<A, B, Request<Body>>>>::Service as Service<Request<Body>>>::Error: Into<Box<dyn Error + Send + Sync>> + Send,
    ResBody: Body<Data = Bytes> + Send + 'static,
    ResBody::Error: Into<Box<dyn Error + Send + Sync>>, 
```

Besides this just being an incredibly complex type signature, users can't derive any information out of it because the type `Routes` is private. In particular, you can't figure out what the associated types mean (or what the constraints imply) without going to the source code.

**Comment by davidpdrsn** [comment]
What specific questions do you have?

The trait bounds are not intentionally complicated but exist to enable other features. You're welcome to make suggestions on how to simplify them.

The `Routes` type is private because users shouldn't have to use it. That'll be changed in https://github.com/hyperium/tonic/pull/830 which makes the routing simpler, including simplifying some types.

**Comment by LucioFranco** [comment]
The compiler errors produced from these bounds are what is important. Most of these bounds just add send requirements and in reality can be mostly ignored. Once rust gets proper trait aliases we can consider using those to reduce it. Going to close this but feel free to reopen it if you have any more questions!
