### ISSUE TITLE
tonic-build: use prettyplease to format generate code instead of rustfmt

### ISSUE THREAD

**Issue by pymongo** [hyperium/tonic#889]
### Crates

tonic-build

### Motivation

current tonic-build/prost codegen is using rustfmt to format code

https://github.com/hyperium/tonic/blob/7179f7ae6a5186bb64e4c120302084f56c053206/tonic-build/src/lib.rs#L232

rustfmt's performance is slow, and require user install rustfmt component

### Proposal

use the syn/quote ecosystem new formatting crate: https://github.com/dtolnay/prettyplease

prettyplease performance is better than rustfmt and doesn't require rustfmt component

### Alternatives

None

**Comment by davidpdrsn** [comment]
Maybe this is a silly question why do people care so much about the formatting of the generated code? Because it's committed to git? If so couldn't you format it yourself without tonic-build doing it for you?
