### ISSUE TITLE
Is there plan to support rdma?

### ISSUE THREAD

**Issue by zhucan** [hyperium/tonic#896]

**Comment by zhucan** [comment]
@LucioFranco

**Comment by davidpdrsn** [comment]
What is rdma?

**Comment by zhucan** [comment]
@davidpdrsn https://github.com/tensorflow/networking

**Comment by davidpdrsn** [comment]
That says very little about what it actually is 😅 and the linked readme (https://github.com/yahoo/tensorflow/blob/verbs_rdma/tensorflow/contrib/verbs/README.md) is gone 🤷 

I'm not aware of any plans to support rdma and dunno whether we should have such plans or not.

**Comment by microyahoo** [comment]
tonic only has gRPC implementations. Maybe supports multiple communication protocols such as gRPC over TCP, and RDMA over Converged Ethernet is better. 
https://github.com/tensorflow/tensorflow/issues/2916

**Comment by zhucan** [comment]
https://github.com/tensorflow/networking/blob/master/README.md  The transport layer of the grcp that can not only use http2(tcp/Ip), maybe can use rdma.

**Comment by zhucan** [comment]
![image](https://user-images.githubusercontent.com/13997135/150310398-804a82e0-5353-46c6-ac39-60493e25246e.png)
@davidpdrsn

**Comment by zhucan** [comment]
There is a reports of the tensorflow over the rdma and normal tcp/ip, you can take a look: http://hidl.cse.ohio-state.edu/performance/rdma-tensorflow/

**Comment by davidpdrsn** [comment]
Tonic already supports other transports than h2/tcp through [`Endpoint::connect_with_connector`](https://docs.rs/tonic/latest/tonic/transport/channel/struct.Endpoint.html#method.connect_with_connector) and [`Server::serve_with_incoming`](https://docs.rs/tonic/latest/tonic/transport/server/struct.Router.html#method.serve_with_incoming).

**Comment by zhucan** [comment]
The rdma is over the UDP/IP, but need the Hardware device to support.

**Comment by LucioFranco** [comment]
Tonic will not support RDMA out of the box. As a user you can hook in RDMA yourself via the link @davidpdrsn posted. Tonic does very little with the transport and allows users to provide their own if the basic one out of the box doesn't work.
