### ISSUE TITLE
Make `Channel::connect` async

### ISSUE THREAD

**Issue by LucioFranco** [hyperium/tonic#90]
Currently, when you attempt to create a channel it does not connect when you would expect it too. https://docs.rs/tonic/0.1.0-alpha.3/tonic/transport/struct.Endpoint.html#method.channel this currently is sync.

This causes issues when you want to make sure you're connected before you make the first RPC call. Due to how `tower-reconnect` is implemented it becomes lazy and thus attempts to connect on the first rpc call which is a bit annoying. 

To change this we should make our own version of the reconnect middleware that allows us to create a channel, check that it is open/valid and then lazily reconnect if it fails.

**Comment by abdul-rehman0** [comment]
@LucioFranco this is done in [Change channel connect to be async](#107), right?

**Comment by LucioFranco** [comment]
Yup I thought this got closed with the PR thanks for checking!
