### ISSUE TITLE
Inconsistent Server Builder api - timeout func returns &mut Self instead of Self

### ISSUE THREAD

**Issue by jdahlq** [hyperium/tonic#900]
### Crates

tonic

### Motivation

Similar functions in the Builder return `Self` rather than `&mut Self` enabling move semantics, but `timeout` doesn't, leading to quirky behavior.

```rust
// This compiles because `add_service` takes a `&mut Self` and clones it.
let router = Server::builder()
  .accept_http1(true)
  .timeout(Duration::from_secs(10))
  .add_service(my_svc);

// This does NOT compile because `accept_http1` takes a `Self` but cannot move or copy it.
let router = Server::builder()
  .timeout(Duration::from_secs(10))
  .accept_http1(true)
  .add_service(my_svc);
```

Issue #115 changed most of these functions to return `Self`, but `timeout` was (re-)introduced in PR #199 and (presumably unintentionally) uses the old behavior of returning `&mut Self`.

### Proposal

Make `timeout` consistent with other funcs like `accept_http1`, `concurrency_limit_per_connection`, etc.

**Comment by jdahlq** [comment]
TODO: Update this PR to avoid the CORS issue described in Issue #911 once PR #912 is submitted.

**Comment by LucioFranco** [comment]
Nice catch! Yeah, we should get this fixed :)
