### ISSUE TITLE
Release version of auxiliary crates to crates.io with 2018 revert

### ISSUE THREAD

**Issue by matze** [hyperium/tonic#902]
### Crates

tonic-health, tonic-reflection, tonic-types, …

### Description

Auxiliary crates that have not seen a new release (e.g. tonic-health 0.5, tonic-reflection 0.3, …) since #847 are incompatible with tonic 0.6.2 in builds that use an edition 2018-only compiler, i.e. anything lower than Rust 1.56.

Releasing new versions of these crates should mitigate this issue.

**Comment by matze** [comment]
Is there anything blocking minor releases for these crates? Performance issues are still unresolved in the current stable Rust compiler and this issue here effectively prevents us from upgrading tonic entirely without swallowing the cost of a newer Rust.

**Comment by LucioFranco** [comment]
Oh yup this was a miss! If this is something still required I can try to get a patch release out otherwise I'd like to get these updated in the next release. As a workaround you should be able to use patching via git to overcome this issue since they are fixed on github.
