### ISSUE TITLE
Implement Serde::{Serialize, Deserialize}

### ISSUE THREAD

**Issue by mezeipetister** [hyperium/tonic#903]
Hi Guys,

currently is it available somehow to implement Serde Serialize and Deserialize traits for the tonic-build generated rust types?

Currently I have a project where I would use the rust types for RPC communication, but I would use the same objects for the public rest API, and for that it would be nice the serde auto implementation.

Now I need to create my public api request response structs and convert the rpc request response and vica versa.

Thank you in advance.

Best wishes,
Peter Mezei.

**Comment by davidpdrsn** [comment]
You can use https://docs.rs/tonic-build/0.6.2/tonic_build/struct.Builder.html#method.type_attribute which delegates to https://docs.rs/prost-build/0.9.0/prost_build/struct.Config.html#method.type_attribute which has an example for deriving `Serialize` and `Deserialize`.
