### ISSUE TITLE
Build `tonic-build` with different compiler flags.

### ISSUE THREAD

**Issue by BratSinot** [hyperium/tonic#918]
## Bug Report
Greetings!

I have build machinve without AVX512 SMID and server with AVX512. So, when I'm trying to build like this:
```
RUSTFLAGS="-C target-cpu=x86-64-v4" cargo build --release --bin <name>
```
of course I will get error about illegal instruction.

Also, because of `tonic-build` in `build-dependencies` I can't build it like this:
```
cargo build --package tonic-build
RUSTFLAGS="-C target-cpu=x86-64-v4" cargo build --release --bin <name>
```

P.S. Of course, I know it `cargo` problem most of, but still.

**Comment by BratSinot** [comment]
Seems like I can build `grpc` stuff first:
```
cargo build --release --package grpc
RUSTFLAGS="-C target-cpu=x86-64-v4" cargo build --release --bin <name>
```

Since `grpc` most of all have structs, I'm hoping build without SMID doesn't affect so much.

**Comment by davidpdrsn** [comment]
I don't understand what you mean. Are you making a feature request or reporting a bug?

**Comment by BratSinot** [comment]
> I don't understand what you mean. Are you making a feature request or reporting a bug?

I think the closest subject is cross building.
`RUSTFLAGS` is specifying for all project (build, dev), so, `tonic-build` builds compiler binary with these flags and runs after. So, if you specify flags with unsupported instructions, you will get an error.

**Comment by BratSinot** [comment]
I found the solution =) I must specify build target, then flags won't be passing to build scripts.
```
RUN CARGO_BUILD_TARGET="x86_64-unknown-linux-musl" \
RUSTFLAGS="-C target-cpu=x86-64-v4" \
cargo build --release
```
