### ISSUE TITLE
Support customize `poll_ready` for generated servers

### ISSUE THREAD

**Issue by tisonkun** [hyperium/tonic#927]
### Crates

`tonic_build`

### Motivation

Ref: https://github.com/hyperium/tonic/discussions/924

I can see some real-world requirement to add callback when the server is ready. The most likely cutting point I can find is `poll_ready`.

### Proposal

The generated servers can hold a ctor to set up the customized logic and call it when `poll_ready` was called. The default behavior is `Poll::Ready(Ok())`.

### Alternatives

Maybe the customized function can directly receive the `Poll` state and decide what to do if it's ready.

If we can callback at a more precise point, it's desired.

**Comment by davidpdrsn** [comment]
You can wrap you services in a new middleware that handles readiness. See https://github.com/hyperium/tonic/blob/master/examples/src/tower/server.rs.

**Comment by tisonkun** [comment]
@davidpdrsn thanks for your reply. Let me try to achieving for the exact requirement...

**Comment by tisonkun** [comment]
closed as information delivered.
