### ISSUE TITLE
Reduce dependencies

### ISSUE THREAD

**Issue by LucioFranco** [hyperium/tonic#93]
We should attempt to use feature flags to reduce dependencies that we don't use.

**Comment by blittable** [comment]
Quick question here - feature flags to narrow the import scope of the upstream dependencies or features flags in the tonic code (e.g. put cfg attributes on handful of trace crate usages?)

I looked at the upstream dependencies, but didn't see any good opportunities to factor out features.

**Comment by LucioFranco** [comment]
@blittable as of right now there are not many but that is because we pull in the whole world with the `transport` feature. I think we can revisit this issue once tokio/hyper get a stable release.
