### ISSUE TITLE
TcpStream

### ISSUE THREAD

**Issue by Ilqjx** [hyperium/tonic#940]
Can `tonic::transport::Server` accept `tokio::net::TcpStream` as a parameter to generate a server or request?

I saw this api, but it requires  the parameter `stream` to implement `futures::Stream`.
```rust
tonic::transport::Server::builder().add_service(GreeterServer::new(greeter)).serve_with_incoming(stream).await;
```

Do you have any other APIs or any good suggestions?

**Comment by davidpdrsn** [comment]
You can use https://docs.rs/tokio-stream/0.1.8/tokio_stream/wrappers/struct.TcpListenerStream.html to convert it into a stream.

**Comment by Ilqjx** [comment]
Hello, is there any other API, this API transfers the ownership of TcpListener not what I want.

**Comment by davidpdrsn** [comment]
I don't think so. Tonic needs to own the stream.

**Comment by Ilqjx** [comment]
I got it, thanks for your reply.
