### ISSUE TITLE
tonic_build: _.rs is generated

### ISSUE THREAD

**Issue by dthusian** [hyperium/tonic#945]
### Version

```
tonic = "0.6.2"
prost = "0.9.0"
tonic-build = "0.6.2"
```

### Platform

`Linux hostname 5.13.13-200.fc34.x86_64 #1 SMP Thu Aug 26 17:06:39 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

### Description

When using tonic_build to build protobuf files, the output file is always named `_.rs`, which causes it to be unable to be included with `tonic::include_proto`.

Expected behavior: `tonic::include_proto` does not cause an error.

Actual behavior: `tonic::include_proto` causes an error as it cannot find `${OUT_DIR}/thing.rs`

`lib.rs`
```
mod thing {
  tonic::include_proto!("thing");
}
```

`build.rs`
```
extern crate tonic_build;

use std::error::Error;

fn main() -> Result<(), Box<dyn Error>> {
  println!("cargo:rerun-if-changed=thing.proto");
  tonic_build::configure()
    .build_server(true)
    .compile(
      &["./thing.proto"],
      &["./"])?;
  Ok(())
}
```

`thing.proto`
```
syntax = "proto3";

service Thing {

}
```

Exact Error (when `cargo build` is run)
```
error: couldn't read /path/projects/test1/target/debug/build/test1-6c26acb609960d4b/out/thing.rs: No such file or directory (os error 2)
 --> src/lib.rs:2:3
  |
2 |   tonic::include_proto!("thing");
  |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: this error originates in the macro `include` (in Nightly builds, run with -Z macro-backtrace for more info)

error: could not compile `test1` due to previous error
```

**Comment by neoeinstein** [comment]
It looks like you haven't specified a package name for `thing.proto`. If a package name isn't provided, the default package filename is used instead, which is `_.rs` by default. If your `lib.rs` were instead to do `tonic::include_proto!("_");`, then compilation should succeed.

If you want to produce `thing.rs`, then add `package thing;` into your proto file.

**Comment by dthusian** [comment]
Thanks. It seems to be working now.
