### ISSUE TITLE
tonic-health misbehaves when no service specified

### ISSUE THREAD

**Issue by bjchambers** [hyperium/tonic#963]
From https://github.com/grpc/grpc/blob/master/doc/health-checking.md (emphasis mine):

> **The server should use an empty string as the key for server's overall health status, so that a client not interested in a specific service can query the server's status with an empty request.** The server can just do exact matching of the service name without support of any kind of wildcard matching. However, the service owner has the freedom to implement more complicated matching semantics that both the client and server agree upon.

However, the code in `tonic-health` reports "service not registered". This is particularly misleading, since it makes it sound (possibly) like the Health service itself is the problem when received from the grpc-health-check. I believe this could be fixed by combining the statuses, and returning `SERVING` if all services are `SERVING` and returning `NOT_SERVING` if any service is `NOT_SERVING`.

**Comment by LucioFranco** [comment]
This has been fixed in the latest 0.6 release of tonic-health
