### ISSUE TITLE
After updating to v0.7 with prost-types v0.10 "google.protobuf.rs" is not available

### ISSUE THREAD

**Issue by g0hl1n** [hyperium/tonic#964]
### Version

```
$ cargo tree | grep -e tonic -e prost
├── prost v0.10.0
│   └── prost-derive v0.10.0 (proc-macro)
├── prost-types v0.10.0
│   └── prost v0.10.0 (*)
└── tonic v0.7.1
    ├── prost v0.10.0 (*)
    ├── prost-derive v0.10.0 (proc-macro) (*)
├── tonic-build v0.7.0
│   ├── prost-build v0.10.0
│   │   ├── prost v0.10.0
│   │   │   └── prost-derive v0.10.0 (proc-macro) (*)
│   │   ├── prost-types v0.10.0
│   │   │   └── prost v0.10.0 (*)
```

### Platform

`Fedora release 35 (Thirty Five)`

`Linux 5.16.16-200.fc35.x86_64`

### Crates

* tonic-build

### Description

After updating to tonic{,-build} v0.7 and prost{,-types} v0.10 cargo build fails with

```
error: couldn't read /.../target/debug/build/.../out/google.protobuf.rs: No such file or directory (os error 2)
 --> /.../target/debug/build/.../out/grpc_api_mod.rs:3:9
  |
3 |         include!("google.protobuf.rs");
  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: this error originates in the macro `include` (in Nightly builds, run with -Z macro-backtrace for more info)

error: could not compile `...` due to previous error
```

build.rs calls:
```
fn gen_grpc_srv(include_file: &str, protos: Vec<String>) -> Result<(), Box<dyn std::error::Error>> {
    let proto_path = env::var("OUT_DIR").unwrap() + "/proto";
    tonic_build::configure()
        .build_server(true)
        .include_file(&include_file)
        .compile(&protos, &[proto_path])?;
    Ok(())
}
```

The `google.protobuf.rs` isn't available in the target directory:
```
$ find target -name google.protobuf.rs | wc -l
0
```

Using tonic-build's `.compile_well_known_types(true)` instead of prost-types works.

**Comment by LucioFranco** [comment]
@g0hl1n do you have the protobuf you're trying to build? I'd like to see if I can reproduce this bug.

**Comment by g0hl1n** [comment]
It seems it is related to `include_file()` of the Builder as building my proto with following build.rs works fine:

```
tonic_build::configure()
    .build_server(true)
    .compile(&["proto/test.proto"], &["proto"])?;
```

Where building with the following returns the described include error:

```
tonic_build::configure()
    .build_server(true)
    .include_file("gen_test.rs")
    .compile(&["proto/test.proto"], &["proto"])?;
```

The used proto is:
```
syntax = "proto3";

/*******************************************************************************
 * 1. Package */
package com.skidata.test.v1;

/*******************************************************************************
 * 2. Imports */
import "google/protobuf/empty.proto";

/*******************************************************************************
 * 3. File Options */

/*******************************************************************************
 * 4. service */

/* test service for https://github.com/hyperium/tonic/issues/964 */
service Test {
  /* test method */
  rpc GetTest(google.protobuf.Empty) returns (GetTestResponse);
}

/******************************************************************************
 * 5. resource "message" definitions */

/* Test application configuration */
message TestConfig {
}

/******************************************************************************
 * 6. request & response "message" definitions */

/* Test response */
message GetTestResponse {
  /* Test config */
  TestConfig conf = 1;
}

/******************************************************************************
 * 7. enum */

```

**Comment by LucioFranco** [comment]
I have not had a chance to full debug it and its not exactly obvious to me. I would suggest as a work around for the moment I would swap out the use of Empty for your own `message Empty {}` that should solve the issue for now.

**Comment by g0hl1n** [comment]
Replacing Empty in an existing API isn't that easy. Furthermore it also affects other well-known-types like Duration and Wrappers. :disappointed:

**Comment by LucioFranco** [comment]
You're totally right, let me try to take a look at this soon. Even though there is a work around I think we should solve this.

**Comment by g0hl1n** [comment]
fyi, i tried reverting https://github.com/tokio-rs/prost/commit/c577d3f96815b0c1dad5df1678401ac7b7c75121 on prost's v0.10.1 tag for the `prost` and `prost-types` dependencies but it didn't change anything.

**Comment by g0hl1n** [comment]
@LucioFranco I've added a test for this problem in my repository and bisected it through the history. According to the bisect the problem was introduced by c78274e3fe5763cba291a605979cd7175ad6c38f (feat: Update prost to 0.10 (#948)).

**Comment by g0hl1n** [comment]
Thanks for the fix @LucioFranco!

When now adding the patch to my Cargo.toml it works :partying_face: 
```
[patch.crates-io]
prost-build = { git = "https://github.com/tokio-rs/prost", rev = "b0cbe9c0a3bcb195e61fdfde32ee6cff9ced6de4" }
```

When do you expect a prost bugfix release (v0.10.2) to happen?
