### ISSUE TITLE
Sporadic build failures after upgrading tonic

### ISSUE THREAD

**Issue by bruceg** [hyperium/tonic#971]
### Version

Before upgrade: 
```
├── tonic v0.6.2
└── tonic-build v0.6.2
```

After upgrade:
```
├── tonic v0.7.1
└── tonic-build v0.7.0
```

### Platform

We've encountered this issue on both Linux (Ubuntu) and 64-bit Windows.

### Description

We are seeing sporadic build failures after upgrading tonic via bumping prost to 0.10.0. Examples:
https://github.com/vectordotdev/vector/runs/5983786518?check_suite_focus=true (Linux)
https://github.com/vectordotdev/vector/runs/5978329668?check_suite_focus=true (Windows)

It appears that a header file is being included multiple times, but the Linux build succeeds more times than it fails, so it's more likely a build race.

**Comment by LucioFranco** [comment]
Huh this feels really odd...maybe this is something to do with the toolchain provided by the build env. 

One work around would be to write a script to pull down `protoc` from the releases on github and set it in the path. This will enable `prost-build` to not have to build `protoc` from source. I would recommend this method.

**Comment by LucioFranco** [comment]
This is also probably an issue we should open in prost rather than tonic.

**Comment by bruceg** [comment]
Agreed, moving to prost.
