### ISSUE TITLE
Cannot use TraceLayer with GrpcService

### ISSUE THREAD

**Issue by conradludgate** [hyperium/tonic#973]
### Version

tonic: 0.7.1
prost: 0.10
tonic-build: 0.7.0
tower: 0.4
tower-http: 0.2.5

### Platform

N/A

### Crates

tonic/tower-http

### Description

`tower-http`'s `trace::TraceLayer` is incompatible with a tonic client GrpcService. It's `Response` does not implement `Default`, but since [this change](https://github.com/hyperium/tonic/pull/842/files) it's now required.

[Demo](https://github.com/conradludgate/tonic-tracing-repro/blob/main/src/main.rs)

We use this layer to automatically propagate our opentelemetry contexts

**Comment by LucioFranco** [comment]
cc @davidpdrsn

**Comment by davidpdrsn** [comment]
If you box the response body like this it works:

```rust
let mut tester_client = TesterClient::new(
    ServiceBuilder::new()
        .layer(tower_http::map_response_body::MapResponseBodyLayer::new(http_body::Body::boxed_unsync))
        .layer(tower_http::trace::TraceLayer::new_for_grpc())
        .service(conn),
);
```

Requires adding the `map-response-body` feature to tower-http.

**Comment by davidpdrsn** [comment]
Also, looking at https://github.com/NAlexPear/tonic/blob/2a61ea0e3e7e746f21a1f82f7d6e34bff58640c0/tonic-build/src/client.rs#L61 I think the `T::ResponseBody: Default` default bound should only be on `with_interceptor` and not on `new`. That'd be worth looking into I think. I believe default bodies are only used for interceptors errors.

**Comment by conradludgate** [comment]
I think you are correct. I've forked locally and can confirm that `new` does not seem to need it, shall I make a PR?

**Comment by davidpdrsn** [comment]
Sure!

**Comment by davidpdrsn** [comment]
Fixed by https://github.com/hyperium/tonic/pull/974
