### ISSUE TITLE
grpc-web

### ISSUE THREAD

**Issue by theduke** [hyperium/tonic#975]
## Feature Request

Implement the [grpc-web](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-WEB.md) specification to allow directly connecting to tonic driven servers from the browser.

### Motivation

Exposing grpc-web is currently possible with [grpc-gateway](https://github.com/grpc-ecosystem/grpc-gateway). 

But that's another moving part to deploy and maintain, and also makes local development more complicated.

Having upstream grpc-web support directly in tonic would both be awesome.

====

I'm willing to work on this, also as a third party crate if need be.

But I wanted to ask if there is general interest in having this upstream, or if someone already has thought about / worked on this.

**Comment by davidpdrsn** [comment]
Isn't that what [tonic-web](https://crates.io/crates/tonic-web) is?

**Comment by theduke** [comment]
> Isn't that what [tonic-web](https://crates.io/crates/tonic-web) is?

Well... indeed. 

My Google fu failed me on that one...
