### ISSUE TITLE
Decouple codegen from `prost`

### ISSUE THREAD

**Issue by LucioFranco** [hyperium/tonic#98]
`prost` is a great library and has already set a very good foundation for `tonic`. That said, we shoud look into enabling other types of codegen "drivers". This would allow us to have codegen that can create flatbuffers and json based grpc services.

- Do we want to have codegen drivers live in their own crate or feature gated behind `tonic-build`?

cc @cpcloud

**Comment by carllerche** [comment]
Feature gated imo

**Comment by RetWolf** [comment]
I'm partial to have codegen not 100% tied into tonic-build. If it is, I believe it should be developed in a way that allows it to easily be decoupled and extracted to its own crate if the community wants. Feature-gated at first will probably be easier, and provides a simpler experience for users.

**Comment by rlabrecque** [comment]
Agreed^ It would be nice to try out rust-protobuf instead of prost for example. Or use JSON with serde_json by generating the services/models via OpenAPI, etc.

**Comment by blittable** [comment]
Agreed.  Most want a rust-grpc stack that does everything that tonic does.  The protobuf compiler piece is convenient until it's not and then it can be a blocker.

https://github.com/hyperium/tonic/issues/30#issuecomment-549720037

**Comment by LucioFranco** [comment]
I am going to drop this from `0.1` looks like we will get a `prost` 0.6 soon and we can release more releases to support this.

**Comment by LucioFranco** [comment]
This has been done over the course of a few PRs.
