### ISSUE TITLE
`tonic_build` unusable without rustfmt

### ISSUE THREAD

**Issue by TheBlueMatt** [hyperium/tonic#982]
When trying to compile a project that uses `tonic_build` to compile protobufs ([1]) on a machine without rustup (i.e. rustfmt is not available) I initially get the "error running rustfmt" error in the build script. I tried disabling default-features and re-enabling the "transport" and "prost" features and building that way, but it doesn't seem to actually compile things when doing that.

It depends on `tonic-build` version 0.6 for the build-script. The error is platform-independent (at least on Linux).

[1] https://github.com/L2-Technology/sensei/

**Comment by TheBlueMatt** [comment]
Looks like this will be resolved once  #904 ships.

**Comment by davidpdrsn** [comment]
That shipped in [tonic-build 0.7](https://crates.io/crates/tonic-build/0.7.0/dependencies)
