### ISSUE TITLE
tonic-build invalid version number

### ISSUE THREAD

**Issue by Morgadoooo** [hyperium/tonic#987]
## Bug Report
Invalid version number for tonic-build

### Version

tonic v0.7.1 (*)
tonic v0.7.1 (*)
tonic-build v0.7.0 (*)

### Description

After the release of tonic 0.7.1, it seems that you forgot to update the version of tonic-build that don't allow us to use the fix made in this PR [https://github.com/hyperium/tonic/pull/974].

**Comment by LucioFranco** [comment]
Oh good catch, I wish this stuff was a bit more automated not sure how I missed that. Will get a release out asap.

**Comment by davidpdrsn** [comment]
I can probably write a little shell script for CI that checks the versions are always the same.

**Comment by LucioFranco** [comment]
@davidpdrsn we could prob setup automatic releases?
