### ISSUE TITLE
[help] question on embedded grpc-web and http service

### ISSUE THREAD

**Issue by clintjedwards** [hyperium/tonic#989]
Hey! I'm having a difficult time trying to replicate something I've written in Go. Hoping someone with a bit more understanding of the tonic package can help.

In general what I'm trying to do is have normal http requests go to a normal http handler and grpc/grpc-web requests go to a grpc handler. This allows me to embed the frontend and the backend into a single binary.

In Go, I've achieved this using:

```go
// WrapServer turns normal grpc server object into one capable of handling grpc-web requests
wrappedGrpc := grpcweb.WrapServer(server)

router := mux.NewRouter()

frontend := frontend.NewFrontend()
frontend.RegisterUIRoutes(router)

combinedHandler := http.HandlerFunc(func(resp http.ResponseWriter, req *http.Request) {
if strings.Contains(req.Header.Get("Content-Type"), "application/grpc") || wrappedGrpc.IsGrpcWebRequest(req) {
	wrappedGrpc.ServeHTTP(resp, req) // If we think it's a grpc request we just pass it to be handled by the grpc server
	return
}
router.ServeHTTP(resp, req) // else we pass it to the regular service
})

      httpServer := http.Server{
	      Addr:         config.URL,
	      Handler:      combinedHandler,
	      WriteTimeout: 15 * time.Second,
	      ReadTimeout:  15 * time.Second,
      }

httpServer.ListenAndServeTLS(config.TLSCertPath, config.TLSKeyPath))
...
```
Go's `http.HandlerFunc` interface makes this a bit easy to grok how the pieces fit together, but I'm having trouble understanding what I would need for the equivalent using tonic. 

What I have so far is just a normal tonic grpc-web service. Looking through the docs though I'm unable to understand if tonic-web is capable of being called as a handler within some other http router:

```rust
let reflection = Builder::configure()
    .register_encoded_file_descriptor_set(tonic::include_file_descriptor_set!("reflection"))
    .build()
    .expect("could not build reflection server");

info!("started grpc-web service"; "address" => &self.conf.server.url);

Server::builder()
    .accept_http1(true)
    .add_service(reflection)
    .add_service(BasecoatServer::new(self.clone()))
    .serve_with_incoming(incoming)

    .serve(self.conf.server.url.parse().unwrap())
    .await
    .unwrap();
```

**Comment by davidpdrsn** [comment]
In axum (a web framework with the same foundations as tonic) we're working on an example of this exact thing actually. See https://github.com/tokio-rs/axum/pull/967

**Comment by clintjedwards** [comment]
Oh wow that PR is exactly spot on for what I needed. Thanks @davidpdrsn, saved me hours of stumbling around in the dark.
