### ISSUE TITLE
Small change to wording in helloworld-tutorial.md

### ISSUE THREAD

**Issue by josephleblanc** [hyperium/tonic#991]
### Version
helloworld-tonic v0.1.0
└── tonic v0.7.1
└── tonic-build v0.7.1

### Platform
UNIX

### Description

This is my first time opening an issue, I hope this is the correct way to suggest an improvement on something that confused me while doing the helloworld-tutorial.

When doing the tutorial in tonic/examples/helloworld-tutorial.md, I got to the point of trying to build the server with `cargo run --bin helloworld-server`, only to see the following error:
```
error: environment variable `OUT_DIR` not defined
 --> src/server.rs:7:5
  |
7 |     tonic::include_proto!("helloworld"); // The string specified here must match the proto package name
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: this error originates in the macro `env` (in Nightly builds, run with -Z macro-backtrace for more info)
```
I had erroneously put build.rs in my /src instead of in the project root. The tutorial does say to put the build.rs in project root, but it was easy for me to miss because I'm new to using a build.rs and have not used .rs files in project root before. Before finding the problem by googling and seeing that someone else had the same difficulty in this [blog post](https://kvwu.io/posts/setting-up-a-grpc-protobuf-server-with-tonic/), I looked through all my code to find what I'd done wrong, since I was unfamiliar with the error quoted above.

I suggest changing the wording in the "Generating Server and Client code" section of helloworld-tutorial.md from
> At the root of your project, create a build.rs file and add the following code:

to

> At the root of your project **(not /src)**, create a build.rs file and add the following code:

or otherwise emphasize that build.rs should not go in /src.

**Comment by LucioFranco** [comment]
Hi! Yeah, I would be happy to accept a PR that updates our docs to reflect this a bit better. Feel free to tag me in it.

**Comment by josephleblanc** [comment]
Sweet! Ok, I'll submit my Pull Request (first ever for me) and tag you in it.
